// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: log.sql

package pg

import (
	"context"
	"time"
)

const batchDeleteLogs = `-- name: BatchDeleteLogs :exec
DELETE FROM sys_log WHERE id = ANY($1::text[])
`

func (q *Queries) BatchDeleteLogs(ctx context.Context, ids []string) error {
	_, err := q.db.Exec(ctx, batchDeleteLogs, ids)
	return err
}

const countLogs = `-- name: CountLogs :one
SELECT COUNT(*) FROM sys_log
WHERE ($1::text   IS NULL OR module = $1)
  AND ($2::text IS NULL OR (content LIKE $2 OR request_uri LIKE $2))
  AND ($3::timestamptz IS NULL OR create_time >= $3)
  AND ($4::timestamptz   IS NULL OR create_time <= $4)
`

type CountLogsParams struct {
	Module     *string
	Keywords   *string
	CreateFrom *time.Time
	CreateTo   *time.Time
}

func (q *Queries) CountLogs(ctx context.Context, arg CountLogsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countLogs,
		arg.Module,
		arg.Keywords,
		arg.CreateFrom,
		arg.CreateTo,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createLog = `-- name: CreateLog :exec
INSERT INTO sys_log (
    id, module, request_method, request_params, response_content, content,
    request_uri, method, ip, province, city, execution_time,
    browser, browser_version, os, create_by, create_time
) VALUES (
    $1, $2, $3, $4, $5, $6,
    $7, $8, $9, $10, $11, $12,
    $13, $14, $15, $16, $17
)
`

type CreateLogParams struct {
	ID              string
	Module          string
	RequestMethod   string
	RequestParams   string
	ResponseContent string
	Content         string
	RequestUri      string
	Method          string
	Ip              string
	Province        string
	City            string
	ExecutionTime   int64
	Browser         string
	BrowserVersion  string
	Os              string
	CreateBy        string
	Now             time.Time
}

func (q *Queries) CreateLog(ctx context.Context, arg CreateLogParams) error {
	_, err := q.db.Exec(ctx, createLog,
		arg.ID,
		arg.Module,
		arg.RequestMethod,
		arg.RequestParams,
		arg.ResponseContent,
		arg.Content,
		arg.RequestUri,
		arg.Method,
		arg.Ip,
		arg.Province,
		arg.City,
		arg.ExecutionTime,
		arg.Browser,
		arg.BrowserVersion,
		arg.Os,
		arg.CreateBy,
		arg.Now,
	)
	return err
}

const deleteLog = `-- name: DeleteLog :exec
DELETE FROM sys_log WHERE id = $1
`

func (q *Queries) DeleteLog(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteLog, id)
	return err
}

const getLog = `-- name: GetLog :one

SELECT id, module, request_method, request_params, response_content, content, request_uri, method, ip, province, city, execution_time, browser, browser_version, os, create_by, create_time FROM sys_log WHERE id = $1
`

// log.sql
// SQL for the operation audit log (sys_log). Dynamic filters use sqlc.narg;
// date-range bounds are passed as timestamptz (parsed in Go). Ordering is fixed
// to create_time DESC — the previous GORM default.
func (q *Queries) GetLog(ctx context.Context, id string) (SysLog, error) {
	row := q.db.QueryRow(ctx, getLog, id)
	var i SysLog
	err := row.Scan(
		&i.ID,
		&i.Module,
		&i.RequestMethod,
		&i.RequestParams,
		&i.ResponseContent,
		&i.Content,
		&i.RequestUri,
		&i.Method,
		&i.Ip,
		&i.Province,
		&i.City,
		&i.ExecutionTime,
		&i.Browser,
		&i.BrowserVersion,
		&i.Os,
		&i.CreateBy,
		&i.CreateTime,
	)
	return i, err
}

const listLogs = `-- name: ListLogs :many
SELECT id, module, request_method, request_params, response_content, content, request_uri, method, ip, province, city, execution_time, browser, browser_version, os, create_by, create_time FROM sys_log
WHERE ($1::text   IS NULL OR module = $1)
  AND ($2::text IS NULL OR (content LIKE $2 OR request_uri LIKE $2))
  AND ($3::timestamptz IS NULL OR create_time >= $3)
  AND ($4::timestamptz   IS NULL OR create_time <= $4)
ORDER BY create_time DESC
LIMIT  $6
OFFSET $5
`

type ListLogsParams struct {
	Module     *string
	Keywords   *string
	CreateFrom *time.Time
	CreateTo   *time.Time
	Offset     *int32
	Limit      *int32
}

func (q *Queries) ListLogs(ctx context.Context, arg ListLogsParams) ([]SysLog, error) {
	rows, err := q.db.Query(ctx, listLogs,
		arg.Module,
		arg.Keywords,
		arg.CreateFrom,
		arg.CreateTo,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SysLog{}
	for rows.Next() {
		var i SysLog
		if err := rows.Scan(
			&i.ID,
			&i.Module,
			&i.RequestMethod,
			&i.RequestParams,
			&i.ResponseContent,
			&i.Content,
			&i.RequestUri,
			&i.Method,
			&i.Ip,
			&i.Province,
			&i.City,
			&i.ExecutionTime,
			&i.Browser,
			&i.BrowserVersion,
			&i.Os,
			&i.CreateBy,
			&i.CreateTime,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
