// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package pg

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type SysDownloadTask struct {
	ID            int64
	QueueTaskID   int64
	TaskID        string
	Hash          string
	Name          string
	Url           string
	Downloader    string
	Status        string
	Total         int64
	Downloaded    int64
	DownloadSpeed int64
	Uploaded      int64
	UploadSpeed   int64
	SavePath      string
	ErrorMessage  string
	OwnerID       string
	CreatedAt     pgtype.Timestamptz
	UpdatedAt     pgtype.Timestamptz
	DeletedAt     pgtype.Timestamptz
}

type SysLog struct {
	ID              string
	Module          string
	RequestMethod   string
	RequestParams   string
	ResponseContent string
	Content         string
	RequestUri      string
	Method          string
	Ip              string
	Province        string
	City            string
	ExecutionTime   int64
	Browser         string
	BrowserVersion  string
	Os              string
	CreateBy        string
	CreateTime      pgtype.Timestamptz
}

type SysTask struct {
	ID                     int64
	Type                   string
	Status                 string
	CorrelationID          string
	OwnerID                string
	PrivateState           string
	PublicRetryCount       int32
	PublicExecutedDuration int64
	PublicError            string
	PublicErrorHistory     string
	PublicResumeTime       int64
	CreatedAt              pgtype.Timestamptz
	UpdatedAt              pgtype.Timestamptz
	DeletedAt              pgtype.Timestamptz
}

type TConfig struct {
	ID          string
	ConfigName  string
	ConfigKey   string
	ConfigValue string
	Remark      string
	CreateTime  pgtype.Timestamptz
	CreateBy    string
	UpdateTime  pgtype.Timestamptz
	UpdateBy    string
	IsDeleted   int32
}

type TDept struct {
	ID         string
	Name       string
	Code       string
	ParentID   string
	TreePath   string
	Sort       int32
	Status     int32
	CreateBy   string
	CreateTime pgtype.Timestamptz
	UpdateBy   string
	UpdateTime pgtype.Timestamptz
	IsDeleted  int32
}

type TDict struct {
	ID         string
	DictCode   string
	Name       string
	Status     int32
	Remark     string
	CreateBy   string
	CreateTime pgtype.Timestamptz
	UpdateBy   string
	UpdateTime pgtype.Timestamptz
	IsDeleted  int32
}

type TDictItem struct {
	ID         string
	DictCode   string
	Label      string
	Value      string
	TagType    string
	Sort       int32
	Status     int32
	Remark     string
	CreateBy   string
	CreateTime pgtype.Timestamptz
	UpdateBy   string
	UpdateTime pgtype.Timestamptz
	IsDeleted  int32
}

type TMember struct {
	ID            string
	TenantID      string
	Username      string
	Email         string
	Mobile        string
	Password      string
	Nickname      string
	Avatar        string
	Gender        int32
	Status        int32
	LastLoginTime pgtype.Timestamptz
	LastLoginIp   string
	CreateTime    pgtype.Timestamptz
	UpdateTime    pgtype.Timestamptz
	IsDeleted     int32
}

type TMenu struct {
	ID         string
	ParentID   string
	TreePath   string
	Name       string
	Type       int32
	RouteName  string
	RoutePath  string
	Component  string
	Perm       string
	AlwaysShow int32
	KeepAlive  int32
	Visible    int32
	Sort       int32
	Icon       string
	Redirect   string
	Params     string
	CreateTime pgtype.Timestamptz
	UpdateTime pgtype.Timestamptz
}

type TNotice struct {
	ID            string
	Title         string
	Content       string
	Type          int32
	Level         string
	TargetType    int32
	TargetUserIds string
	PublisherID   string
	PublishStatus int32
	PublishTime   pgtype.Timestamptz
	RevokeTime    pgtype.Timestamptz
	CreateBy      string
	CreateTime    pgtype.Timestamptz
	UpdateBy      string
	UpdateTime    pgtype.Timestamptz
	IsDeleted     int32
}

type TRole struct {
	ID         string
	Name       string
	Code       string
	Sort       int32
	Status     int32
	DataScope  int32
	CreateBy   string
	CreateTime pgtype.Timestamptz
	UpdateBy   string
	UpdateTime pgtype.Timestamptz
	IsDeleted  int32
}

type TRoleMenu struct {
	RoleID string
	MenuID string
}

type TTenant struct {
	ID         string
	Code       string
	Name       string
	Status     int32
	CreateTime pgtype.Timestamptz
	CreateBy   string
	UpdateTime pgtype.Timestamptz
	UpdateBy   string
	IsDeleted  int32
}

type TUser struct {
	ID         string
	Username   string
	Nickname   string
	Gender     int32
	Password   string
	DeptID     string
	Avatar     string
	Mobile     string
	Status     int32
	Email      string
	CreateTime pgtype.Timestamptz
	CreateBy   string
	UpdateTime pgtype.Timestamptz
	UpdateBy   string
	IsDeleted  int32
	Openid     string
}

type TUserNotice struct {
	ID         string
	NoticeID   string
	UserID     string
	IsRead     int32
	ReadTime   pgtype.Timestamptz
	CreateTime pgtype.Timestamptz
	UpdateTime pgtype.Timestamptz
	IsDeleted  int32
}

type TUserRole struct {
	UserID string
	RoleID string
}
