// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queue_task.sql

package pg

import (
	"context"
)

const createQueueTask = `-- name: CreateQueueTask :one

INSERT INTO sys_tasks (
    type, status, correlation_id, owner_id, private_state,
    public_retry_count, public_executed_duration, public_error,
    public_error_history, public_resume_time, created_at, updated_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, NOW(), NOW()
)
RETURNING id, type, status, correlation_id, owner_id, private_state, public_retry_count, public_executed_duration, public_error, public_error_history, public_resume_time, created_at, updated_at, deleted_at
`

type CreateQueueTaskParams struct {
	Type                   string
	Status                 string
	CorrelationID          string
	OwnerID                string
	PrivateState           string
	PublicRetryCount       int32
	PublicExecutedDuration int64
	PublicError            string
	PublicErrorHistory     string
	PublicResumeTime       int64
}

// queue_task.sql
// SQL for the framework-agnostic pkg/queue engine over sys_tasks. Unlike the admin
// Job module (task.sql), these queries honour soft-delete: reads filter
// `deleted_at IS NULL`, Create/Update touch only live rows, and Delete is a soft
// delete (sets deleted_at) — preserving the previous gorm.DeletedAt behaviour of
// the engine's GORM TaskRepository. The sqlc implementation of queue.TaskRepository
// lives in the application layer (lib) and is injected into pkg/queue.
func (q *Queries) CreateQueueTask(ctx context.Context, arg CreateQueueTaskParams) (SysTask, error) {
	row := q.db.QueryRow(ctx, createQueueTask,
		arg.Type,
		arg.Status,
		arg.CorrelationID,
		arg.OwnerID,
		arg.PrivateState,
		arg.PublicRetryCount,
		arg.PublicExecutedDuration,
		arg.PublicError,
		arg.PublicErrorHistory,
		arg.PublicResumeTime,
	)
	var i SysTask
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.Status,
		&i.CorrelationID,
		&i.OwnerID,
		&i.PrivateState,
		&i.PublicRetryCount,
		&i.PublicExecutedDuration,
		&i.PublicError,
		&i.PublicErrorHistory,
		&i.PublicResumeTime,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getQueueTask = `-- name: GetQueueTask :one
SELECT id, type, status, correlation_id, owner_id, private_state, public_retry_count, public_executed_duration, public_error, public_error_history, public_resume_time, created_at, updated_at, deleted_at FROM sys_tasks WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetQueueTask(ctx context.Context, id int64) (SysTask, error) {
	row := q.db.QueryRow(ctx, getQueueTask, id)
	var i SysTask
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.Status,
		&i.CorrelationID,
		&i.OwnerID,
		&i.PrivateState,
		&i.PublicRetryCount,
		&i.PublicExecutedDuration,
		&i.PublicError,
		&i.PublicErrorHistory,
		&i.PublicResumeTime,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listPendingQueueTasks = `-- name: ListPendingQueueTasks :many
SELECT id, type, status, correlation_id, owner_id, private_state, public_retry_count, public_executed_duration, public_error, public_error_history, public_resume_time, created_at, updated_at, deleted_at FROM sys_tasks
WHERE deleted_at IS NULL
  AND status IN ('queued', 'processing', 'suspending')
  AND ($1::text[] IS NULL OR type = ANY($1::text[]))
ORDER BY id
`

func (q *Queries) ListPendingQueueTasks(ctx context.Context, types []string) ([]SysTask, error) {
	rows, err := q.db.Query(ctx, listPendingQueueTasks, types)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SysTask{}
	for rows.Next() {
		var i SysTask
		if err := rows.Scan(
			&i.ID,
			&i.Type,
			&i.Status,
			&i.CorrelationID,
			&i.OwnerID,
			&i.PrivateState,
			&i.PublicRetryCount,
			&i.PublicExecutedDuration,
			&i.PublicError,
			&i.PublicErrorHistory,
			&i.PublicResumeTime,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteQueueTask = `-- name: SoftDeleteQueueTask :exec
UPDATE sys_tasks SET deleted_at = NOW() WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) SoftDeleteQueueTask(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, softDeleteQueueTask, id)
	return err
}

const updateQueueTask = `-- name: UpdateQueueTask :one
UPDATE sys_tasks SET
    type                     = $2,
    status                   = $3,
    correlation_id           = $4,
    owner_id                 = $5,
    private_state            = $6,
    public_retry_count       = $7,
    public_executed_duration = $8,
    public_error             = $9,
    public_error_history     = $10,
    public_resume_time       = $11,
    updated_at               = NOW()
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, type, status, correlation_id, owner_id, private_state, public_retry_count, public_executed_duration, public_error, public_error_history, public_resume_time, created_at, updated_at, deleted_at
`

type UpdateQueueTaskParams struct {
	ID                     int64
	Type                   string
	Status                 string
	CorrelationID          string
	OwnerID                string
	PrivateState           string
	PublicRetryCount       int32
	PublicExecutedDuration int64
	PublicError            string
	PublicErrorHistory     string
	PublicResumeTime       int64
}

func (q *Queries) UpdateQueueTask(ctx context.Context, arg UpdateQueueTaskParams) (SysTask, error) {
	row := q.db.QueryRow(ctx, updateQueueTask,
		arg.ID,
		arg.Type,
		arg.Status,
		arg.CorrelationID,
		arg.OwnerID,
		arg.PrivateState,
		arg.PublicRetryCount,
		arg.PublicExecutedDuration,
		arg.PublicError,
		arg.PublicErrorHistory,
		arg.PublicResumeTime,
	)
	var i SysTask
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.Status,
		&i.CorrelationID,
		&i.OwnerID,
		&i.PrivateState,
		&i.PublicRetryCount,
		&i.PublicExecutedDuration,
		&i.PublicError,
		&i.PublicErrorHistory,
		&i.PublicResumeTime,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
