// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: task.sql

package pg

import (
	"context"
	"time"
)

const batchDeleteTasks = `-- name: BatchDeleteTasks :exec
DELETE FROM sys_tasks WHERE id = ANY($1::bigint[])
`

func (q *Queries) BatchDeleteTasks(ctx context.Context, ids []int64) error {
	_, err := q.db.Exec(ctx, batchDeleteTasks, ids)
	return err
}

const countTasks = `-- name: CountTasks :one
SELECT COUNT(*) FROM sys_tasks
WHERE ($1::text           IS NULL OR type = $1)
  AND ($2::text         IS NULL OR status = $2)
  AND ($3::text IS NULL OR correlation_id = $3)
  AND ($4::text       IS NULL OR (
        type LIKE $4 OR correlation_id LIKE $4 OR public_error LIKE $4))
  AND ($5::timestamptz IS NULL OR created_at >= $5)
  AND ($6::timestamptz   IS NULL OR created_at <= $6)
`

type CountTasksParams struct {
	Type          *string
	Status        *string
	CorrelationID *string
	Keywords      *string
	CreateFrom    *time.Time
	CreateTo      *time.Time
}

func (q *Queries) CountTasks(ctx context.Context, arg CountTasksParams) (int64, error) {
	row := q.db.QueryRow(ctx, countTasks,
		arg.Type,
		arg.Status,
		arg.CorrelationID,
		arg.Keywords,
		arg.CreateFrom,
		arg.CreateTo,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteTask = `-- name: DeleteTask :exec
DELETE FROM sys_tasks WHERE id = $1
`

func (q *Queries) DeleteTask(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteTask, id)
	return err
}

const getTask = `-- name: GetTask :one

SELECT id, type, status, correlation_id, owner_id, private_state, public_retry_count, public_executed_duration, public_error, public_error_history, public_resume_time, created_at, updated_at, deleted_at FROM sys_tasks WHERE id = $1
`

// task.sql
// SQL for the admin Job module over sys_tasks. These queries intentionally do NOT
// filter deleted_at (models/system.Task has no DeletedAt field), and Delete is a
// hard DELETE — preserving the previous admin behaviour, which differs from the
// pkg/queue engine's soft-delete view of the same table. Ordering is fixed to
// created_at DESC; dynamic filters use sqlc.narg.
func (q *Queries) GetTask(ctx context.Context, id int64) (SysTask, error) {
	row := q.db.QueryRow(ctx, getTask, id)
	var i SysTask
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.Status,
		&i.CorrelationID,
		&i.OwnerID,
		&i.PrivateState,
		&i.PublicRetryCount,
		&i.PublicExecutedDuration,
		&i.PublicError,
		&i.PublicErrorHistory,
		&i.PublicResumeTime,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listTaskStatusCounts = `-- name: ListTaskStatusCounts :many
SELECT status, COUNT(*) AS count FROM sys_tasks GROUP BY status
`

type ListTaskStatusCountsRow struct {
	Status string
	Count  int64
}

func (q *Queries) ListTaskStatusCounts(ctx context.Context) ([]ListTaskStatusCountsRow, error) {
	rows, err := q.db.Query(ctx, listTaskStatusCounts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTaskStatusCountsRow{}
	for rows.Next() {
		var i ListTaskStatusCountsRow
		if err := rows.Scan(&i.Status, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTaskTypes = `-- name: ListTaskTypes :many
SELECT DISTINCT type FROM sys_tasks
`

func (q *Queries) ListTaskTypes(ctx context.Context) ([]string, error) {
	rows, err := q.db.Query(ctx, listTaskTypes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var type_ string
		if err := rows.Scan(&type_); err != nil {
			return nil, err
		}
		items = append(items, type_)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTasks = `-- name: ListTasks :many
SELECT id, type, status, correlation_id, owner_id, private_state, public_retry_count, public_executed_duration, public_error, public_error_history, public_resume_time, created_at, updated_at, deleted_at FROM sys_tasks
WHERE ($1::text           IS NULL OR type = $1)
  AND ($2::text         IS NULL OR status = $2)
  AND ($3::text IS NULL OR correlation_id = $3)
  AND ($4::text       IS NULL OR (
        type LIKE $4 OR correlation_id LIKE $4 OR public_error LIKE $4))
  AND ($5::timestamptz IS NULL OR created_at >= $5)
  AND ($6::timestamptz   IS NULL OR created_at <= $6)
ORDER BY created_at DESC
LIMIT  $8
OFFSET $7
`

type ListTasksParams struct {
	Type          *string
	Status        *string
	CorrelationID *string
	Keywords      *string
	CreateFrom    *time.Time
	CreateTo      *time.Time
	Offset        *int32
	Limit         *int32
}

func (q *Queries) ListTasks(ctx context.Context, arg ListTasksParams) ([]SysTask, error) {
	rows, err := q.db.Query(ctx, listTasks,
		arg.Type,
		arg.Status,
		arg.CorrelationID,
		arg.Keywords,
		arg.CreateFrom,
		arg.CreateTo,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SysTask{}
	for rows.Next() {
		var i SysTask
		if err := rows.Scan(
			&i.ID,
			&i.Type,
			&i.Status,
			&i.CorrelationID,
			&i.OwnerID,
			&i.PrivateState,
			&i.PublicRetryCount,
			&i.PublicExecutedDuration,
			&i.PublicError,
			&i.PublicErrorHistory,
			&i.PublicResumeTime,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
