// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: user_role.sql

package pg

import (
	"context"
)

const batchCreateUserRoles = `-- name: BatchCreateUserRoles :exec
INSERT INTO t_user_role (user_id, role_id)
SELECT unnest($1::text[]), unnest($2::text[])
ON CONFLICT (user_id, role_id) DO NOTHING
`

type BatchCreateUserRolesParams struct {
	UserIds []string
	RoleIds []string
}

// Single-statement bulk insert via array unnest, keeping the whole batch atomic.
func (q *Queries) BatchCreateUserRoles(ctx context.Context, arg BatchCreateUserRolesParams) error {
	_, err := q.db.Exec(ctx, batchCreateUserRoles, arg.UserIds, arg.RoleIds)
	return err
}

const countUserRoles = `-- name: CountUserRoles :one
SELECT COUNT(*) FROM t_user_role
WHERE ($1::text   IS NULL OR user_id = $1)
  AND ($2::text[] IS NULL OR user_id = ANY($2::text[]))
`

type CountUserRolesParams struct {
	UserID  *string
	UserIds []string
}

func (q *Queries) CountUserRoles(ctx context.Context, arg CountUserRolesParams) (int64, error) {
	row := q.db.QueryRow(ctx, countUserRoles, arg.UserID, arg.UserIds)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createUserRole = `-- name: CreateUserRole :exec
INSERT INTO t_user_role (user_id, role_id) VALUES ($1, $2)
ON CONFLICT (user_id, role_id) DO NOTHING
`

type CreateUserRoleParams struct {
	UserID string
	RoleID string
}

func (q *Queries) CreateUserRole(ctx context.Context, arg CreateUserRoleParams) error {
	_, err := q.db.Exec(ctx, createUserRole, arg.UserID, arg.RoleID)
	return err
}

const deleteUserRolesByRoleID = `-- name: DeleteUserRolesByRoleID :exec
DELETE FROM t_user_role WHERE role_id = $1
`

func (q *Queries) DeleteUserRolesByRoleID(ctx context.Context, roleID string) error {
	_, err := q.db.Exec(ctx, deleteUserRolesByRoleID, roleID)
	return err
}

const deleteUserRolesByUserID = `-- name: DeleteUserRolesByUserID :exec
DELETE FROM t_user_role WHERE user_id = $1
`

func (q *Queries) DeleteUserRolesByUserID(ctx context.Context, userID string) error {
	_, err := q.db.Exec(ctx, deleteUserRolesByUserID, userID)
	return err
}

const getRoleIDsByUserID = `-- name: GetRoleIDsByUserID :many
SELECT role_id FROM t_user_role WHERE user_id = $1
`

func (q *Queries) GetRoleIDsByUserID(ctx context.Context, userID string) ([]string, error) {
	rows, err := q.db.Query(ctx, getRoleIDsByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var role_id string
		if err := rows.Scan(&role_id); err != nil {
			return nil, err
		}
		items = append(items, role_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserIDsByRoleID = `-- name: GetUserIDsByRoleID :many
SELECT user_id FROM t_user_role WHERE role_id = $1
`

func (q *Queries) GetUserIDsByRoleID(ctx context.Context, roleID string) ([]string, error) {
	rows, err := q.db.Query(ctx, getUserIDsByRoleID, roleID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var user_id string
		if err := rows.Scan(&user_id); err != nil {
			return nil, err
		}
		items = append(items, user_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserRoles = `-- name: ListUserRoles :many

SELECT user_id, role_id FROM t_user_role
WHERE ($1::text   IS NULL OR user_id = $1)
  AND ($2::text[] IS NULL OR user_id = ANY($2::text[]))
ORDER BY user_id DESC
LIMIT  $4
OFFSET $3
`

type ListUserRolesParams struct {
	UserID  *string
	UserIds []string
	Offset  *int32
	Limit   *int32
}

// user_role.sql
// SQL for the user<->role association (t_user_role).
// Ordering is fixed (user_id DESC) rather than interpolated, eliminating any
// ORDER BY injection surface. This matches the sole caller's default ordering.
func (q *Queries) ListUserRoles(ctx context.Context, arg ListUserRolesParams) ([]TUserRole, error) {
	rows, err := q.db.Query(ctx, listUserRoles,
		arg.UserID,
		arg.UserIds,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TUserRole{}
	for rows.Next() {
		var i TUserRole
		if err := rows.Scan(&i.UserID, &i.RoleID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
