// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: user_notice.sql

package pg

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const batchCreateUserNotices = `-- name: BatchCreateUserNotices :exec
INSERT INTO t_user_notice (id, notice_id, user_id, is_read)
SELECT unnest($1::text[]), unnest($2::text[]), unnest($3::text[]), 0
`

type BatchCreateUserNoticesParams struct {
	Ids       []string
	NoticeIds []string
	UserIds   []string
}

// Single-statement bulk insert via array unnest.
func (q *Queries) BatchCreateUserNotices(ctx context.Context, arg BatchCreateUserNoticesParams) error {
	_, err := q.db.Exec(ctx, batchCreateUserNotices, arg.Ids, arg.NoticeIds, arg.UserIds)
	return err
}

const countMyNotices = `-- name: CountMyNotices :one
SELECT COUNT(*)
FROM t_user_notice un
LEFT JOIN t_notice n ON un.notice_id = n.id
WHERE un.user_id = $1
  AND un.is_deleted = 0
  AND n.is_deleted = 0
  AND n.publish_status = 1
  AND ($2::text IS NULL OR n.title LIKE $2)
  AND ($3::int   IS NULL OR n.type = $3)
`

type CountMyNoticesParams struct {
	UserID string
	Title  *string
	Type   *int32
}

func (q *Queries) CountMyNotices(ctx context.Context, arg CountMyNoticesParams) (int64, error) {
	row := q.db.QueryRow(ctx, countMyNotices, arg.UserID, arg.Title, arg.Type)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createUserNotice = `-- name: CreateUserNotice :exec
INSERT INTO t_user_notice (id, notice_id, user_id, is_read) VALUES ($1, $2, $3, $4)
`

type CreateUserNoticeParams struct {
	ID       string
	NoticeID string
	UserID   string
	IsRead   int32
}

func (q *Queries) CreateUserNotice(ctx context.Context, arg CreateUserNoticeParams) error {
	_, err := q.db.Exec(ctx, createUserNotice,
		arg.ID,
		arg.NoticeID,
		arg.UserID,
		arg.IsRead,
	)
	return err
}

const deleteUserNoticesByNoticeID = `-- name: DeleteUserNoticesByNoticeID :exec
DELETE FROM t_user_notice WHERE notice_id = $1
`

func (q *Queries) DeleteUserNoticesByNoticeID(ctx context.Context, noticeID string) error {
	_, err := q.db.Exec(ctx, deleteUserNoticesByNoticeID, noticeID)
	return err
}

const deleteUserNoticesByNoticeIDs = `-- name: DeleteUserNoticesByNoticeIDs :exec
DELETE FROM t_user_notice WHERE notice_id = ANY($1::text[])
`

func (q *Queries) DeleteUserNoticesByNoticeIDs(ctx context.Context, noticeIds []string) error {
	_, err := q.db.Exec(ctx, deleteUserNoticesByNoticeIDs, noticeIds)
	return err
}

const listMyNotices = `-- name: ListMyNotices :many

SELECT un.id, un.notice_id, n.title, n.type, n.level, n.publish_time, un.is_read
FROM t_user_notice un
LEFT JOIN t_notice n ON un.notice_id = n.id
WHERE un.user_id = $1
  AND un.is_deleted = 0
  AND n.is_deleted = 0
  AND n.publish_status = 1
  AND ($2::text IS NULL OR n.title LIKE $2)
  AND ($3::int   IS NULL OR n.type = $3)
ORDER BY n.publish_time DESC
LIMIT  $5
OFFSET $4
`

type ListMyNoticesParams struct {
	UserID string
	Title  *string
	Type   *int32
	Offset *int32
	Limit  *int32
}

type ListMyNoticesRow struct {
	ID          string
	NoticeID    string
	Title       *string
	Type        *int32
	Level       *string
	PublishTime pgtype.Timestamptz
	IsRead      int32
}

// user_notice.sql
// SQL for per-user notice state (t_user_notice), including the "my notices" join.
// Published, non-deleted notices addressed to a user, newest first. Projects the
// fields the UI needs (UserNoticePageVO).
func (q *Queries) ListMyNotices(ctx context.Context, arg ListMyNoticesParams) ([]ListMyNoticesRow, error) {
	rows, err := q.db.Query(ctx, listMyNotices,
		arg.UserID,
		arg.Title,
		arg.Type,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListMyNoticesRow{}
	for rows.Next() {
		var i ListMyNoticesRow
		if err := rows.Scan(
			&i.ID,
			&i.NoticeID,
			&i.Title,
			&i.Type,
			&i.Level,
			&i.PublishTime,
			&i.IsRead,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markAllUserNoticesRead = `-- name: MarkAllUserNoticesRead :exec
UPDATE t_user_notice SET is_read = 1, read_time = NOW(), update_time = NOW()
WHERE user_id = $1 AND is_read = 0
`

func (q *Queries) MarkAllUserNoticesRead(ctx context.Context, userID string) error {
	_, err := q.db.Exec(ctx, markAllUserNoticesRead, userID)
	return err
}

const markUserNoticeRead = `-- name: MarkUserNoticeRead :exec
UPDATE t_user_notice SET is_read = 1, read_time = NOW(), update_time = NOW()
WHERE notice_id = $1 AND user_id = $2 AND is_read = 0
`

type MarkUserNoticeReadParams struct {
	NoticeID string
	UserID   string
}

func (q *Queries) MarkUserNoticeRead(ctx context.Context, arg MarkUserNoticeReadParams) error {
	_, err := q.db.Exec(ctx, markUserNoticeRead, arg.NoticeID, arg.UserID)
	return err
}
