// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: dept.sql

package sqlc

import (
	"context"
)

const createDept = `-- name: CreateDept :exec
INSERT INTO t_dept (
    id, name, code, parent_id, tree_path, sort, status,
    create_by, update_by, is_deleted, create_time, update_time
) VALUES (
    $1, $2, $3, $4, $5, $6, $7,
    $8, $9, $10, NOW(), NOW()
)
`

type CreateDeptParams struct {
	ID        string
	Name      string
	Code      string
	ParentID  string
	TreePath  string
	Sort      int32
	Status    int32
	CreateBy  string
	UpdateBy  string
	IsDeleted int32
}

func (q *Queries) CreateDept(ctx context.Context, arg CreateDeptParams) error {
	_, err := q.db.Exec(ctx, createDept,
		arg.ID,
		arg.Name,
		arg.Code,
		arg.ParentID,
		arg.TreePath,
		arg.Sort,
		arg.Status,
		arg.CreateBy,
		arg.UpdateBy,
		arg.IsDeleted,
	)
	return err
}

const getDept = `-- name: GetDept :one

SELECT id, name, code, parent_id, tree_path, sort, status, create_by, create_time, update_by, update_time, is_deleted FROM t_dept
WHERE id = $1 AND is_deleted = 0
`

// dept.sql
// All SQL for the department domain (t_dept). Dynamic filters use sqlc.narg
// (nullable args) so one prepared statement serves every filter combination while
// staying fully parameterized. Ordering is a fixed `sort ASC` (the previous GORM
// default), eliminating any ORDER BY injection surface.
func (q *Queries) GetDept(ctx context.Context, id string) (TDept, error) {
	row := q.db.QueryRow(ctx, getDept, id)
	var i TDept
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Code,
		&i.ParentID,
		&i.TreePath,
		&i.Sort,
		&i.Status,
		&i.CreateBy,
		&i.CreateTime,
		&i.UpdateBy,
		&i.UpdateTime,
		&i.IsDeleted,
	)
	return i, err
}

const getDeptByCode = `-- name: GetDeptByCode :one
SELECT id, name, code, parent_id, tree_path, sort, status, create_by, create_time, update_by, update_time, is_deleted FROM t_dept
WHERE code = $1 AND is_deleted = 0
  AND ($2::text IS NULL OR id <> $2)
LIMIT 1
`

type GetDeptByCodeParams struct {
	Code      string
	ExcludeID *string
}

// exclude_id lets callers ignore a specific row (used when validating a code on
// update). A NULL exclude_id disables the exclusion.
func (q *Queries) GetDeptByCode(ctx context.Context, arg GetDeptByCodeParams) (TDept, error) {
	row := q.db.QueryRow(ctx, getDeptByCode, arg.Code, arg.ExcludeID)
	var i TDept
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Code,
		&i.ParentID,
		&i.TreePath,
		&i.Sort,
		&i.Status,
		&i.CreateBy,
		&i.CreateTime,
		&i.UpdateBy,
		&i.UpdateTime,
		&i.IsDeleted,
	)
	return i, err
}

const listDepts = `-- name: ListDepts :many
SELECT id, name, code, parent_id, tree_path, sort, status, create_by, create_time, update_by, update_time, is_deleted FROM t_dept
WHERE is_deleted = 0
  AND ($1::text IS NULL OR name LIKE $1)
  AND ($2::int    IS NULL OR status = $2)
ORDER BY sort ASC
`

type ListDeptsParams struct {
	Keywords *string
	Status   *int32
}

func (q *Queries) ListDepts(ctx context.Context, arg ListDeptsParams) ([]TDept, error) {
	rows, err := q.db.Query(ctx, listDepts, arg.Keywords, arg.Status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TDept{}
	for rows.Next() {
		var i TDept
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Code,
			&i.ParentID,
			&i.TreePath,
			&i.Sort,
			&i.Status,
			&i.CreateBy,
			&i.CreateTime,
			&i.UpdateBy,
			&i.UpdateTime,
			&i.IsDeleted,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDeptsByIDs = `-- name: ListDeptsByIDs :many
SELECT id, name, code, parent_id, tree_path, sort, status, create_by, create_time, update_by, update_time, is_deleted FROM t_dept
WHERE is_deleted = 0 AND id = ANY($1::text[])
`

func (q *Queries) ListDeptsByIDs(ctx context.Context, ids []string) ([]TDept, error) {
	rows, err := q.db.Query(ctx, listDeptsByIDs, ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TDept{}
	for rows.Next() {
		var i TDept
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Code,
			&i.ParentID,
			&i.TreePath,
			&i.Sort,
			&i.Status,
			&i.CreateBy,
			&i.CreateTime,
			&i.UpdateBy,
			&i.UpdateTime,
			&i.IsDeleted,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEnabledDepts = `-- name: ListEnabledDepts :many
SELECT id, name, code, parent_id, tree_path, sort, status, create_by, create_time, update_by, update_time, is_deleted FROM t_dept
WHERE is_deleted = 0 AND status = 1
ORDER BY sort ASC
`

func (q *Queries) ListEnabledDepts(ctx context.Context) ([]TDept, error) {
	rows, err := q.db.Query(ctx, listEnabledDepts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TDept{}
	for rows.Next() {
		var i TDept
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Code,
			&i.ParentID,
			&i.TreePath,
			&i.Sort,
			&i.Status,
			&i.CreateBy,
			&i.CreateTime,
			&i.UpdateBy,
			&i.UpdateTime,
			&i.IsDeleted,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteDept = `-- name: SoftDeleteDept :exec
UPDATE t_dept SET is_deleted = 1, update_by = $2, update_time = NOW()
WHERE id = $1
`

type SoftDeleteDeptParams struct {
	ID       string
	UpdateBy string
}

func (q *Queries) SoftDeleteDept(ctx context.Context, arg SoftDeleteDeptParams) error {
	_, err := q.db.Exec(ctx, softDeleteDept, arg.ID, arg.UpdateBy)
	return err
}

const softDeleteDeptByTreePath = `-- name: SoftDeleteDeptByTreePath :exec
UPDATE t_dept SET is_deleted = 1, update_by = $1, update_time = NOW()
WHERE id = $2
   OR (',' || tree_path || ',') LIKE $3
`

type SoftDeleteDeptByTreePathParams struct {
	UpdateBy     string
	ID           string
	TreePathLike string
}

// Soft-deletes a department and all of its descendants. A node is a descendant
// when its comma-wrapped tree_path contains ",<id>,". Matches the previous GORM
// expression built from DBCompat.TreePathLike.
func (q *Queries) SoftDeleteDeptByTreePath(ctx context.Context, arg SoftDeleteDeptByTreePathParams) error {
	_, err := q.db.Exec(ctx, softDeleteDeptByTreePath, arg.UpdateBy, arg.ID, arg.TreePathLike)
	return err
}

const updateDept = `-- name: UpdateDept :exec
UPDATE t_dept SET
    name        = $2,
    code        = $3,
    parent_id   = $4,
    tree_path   = $5,
    sort        = $6,
    status      = $7,
    update_by   = $8,
    update_time = NOW()
WHERE id = $1
`

type UpdateDeptParams struct {
	ID       string
	Name     string
	Code     string
	ParentID string
	TreePath string
	Sort     int32
	Status   int32
	UpdateBy string
}

// Mirrors the previous Select-scoped GORM update
// (name, code, parent_id, tree_path, sort, status, update_by).
func (q *Queries) UpdateDept(ctx context.Context, arg UpdateDeptParams) error {
	_, err := q.db.Exec(ctx, updateDept,
		arg.ID,
		arg.Name,
		arg.Code,
		arg.ParentID,
		arg.TreePath,
		arg.Sort,
		arg.Status,
		arg.UpdateBy,
	)
	return err
}
