// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: dict.sql

package sqlc

import (
	"context"
)

const countDicts = `-- name: CountDicts :one
SELECT COUNT(*) FROM t_dict
WHERE is_deleted = 0
  AND ($1::text IS NULL OR (name LIKE $1 OR dict_code LIKE $1))
`

func (q *Queries) CountDicts(ctx context.Context, keywords *string) (int64, error) {
	row := q.db.QueryRow(ctx, countDicts, keywords)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createDict = `-- name: CreateDict :exec
INSERT INTO t_dict (
    id, dict_code, name, status, remark, create_by, update_by, is_deleted,
    create_time, update_time
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, NOW(), NOW()
)
`

type CreateDictParams struct {
	ID        string
	DictCode  string
	Name      string
	Status    int32
	Remark    string
	CreateBy  string
	UpdateBy  string
	IsDeleted int32
}

func (q *Queries) CreateDict(ctx context.Context, arg CreateDictParams) error {
	_, err := q.db.Exec(ctx, createDict,
		arg.ID,
		arg.DictCode,
		arg.Name,
		arg.Status,
		arg.Remark,
		arg.CreateBy,
		arg.UpdateBy,
		arg.IsDeleted,
	)
	return err
}

const getDict = `-- name: GetDict :one

SELECT id, dict_code, name, status, remark, create_by, create_time, update_by, update_time, is_deleted FROM t_dict WHERE id = $1 AND is_deleted = 0
`

// dict.sql
// SQL for the dictionary domain (t_dict). Dynamic filters use sqlc.narg so one
// prepared statement serves every filter combination. Ordering is fixed
// (create_time DESC) — the previous GORM default.
func (q *Queries) GetDict(ctx context.Context, id string) (TDict, error) {
	row := q.db.QueryRow(ctx, getDict, id)
	var i TDict
	err := row.Scan(
		&i.ID,
		&i.DictCode,
		&i.Name,
		&i.Status,
		&i.Remark,
		&i.CreateBy,
		&i.CreateTime,
		&i.UpdateBy,
		&i.UpdateTime,
		&i.IsDeleted,
	)
	return i, err
}

const getDictByCode = `-- name: GetDictByCode :one
SELECT id, dict_code, name, status, remark, create_by, create_time, update_by, update_time, is_deleted FROM t_dict
WHERE dict_code = $1 AND is_deleted = 0
  AND ($2::text IS NULL OR id <> $2)
LIMIT 1
`

type GetDictByCodeParams struct {
	DictCode  string
	ExcludeID *string
}

func (q *Queries) GetDictByCode(ctx context.Context, arg GetDictByCodeParams) (TDict, error) {
	row := q.db.QueryRow(ctx, getDictByCode, arg.DictCode, arg.ExcludeID)
	var i TDict
	err := row.Scan(
		&i.ID,
		&i.DictCode,
		&i.Name,
		&i.Status,
		&i.Remark,
		&i.CreateBy,
		&i.CreateTime,
		&i.UpdateBy,
		&i.UpdateTime,
		&i.IsDeleted,
	)
	return i, err
}

const listDicts = `-- name: ListDicts :many
SELECT id, dict_code, name, status, remark, create_by, create_time, update_by, update_time, is_deleted FROM t_dict
WHERE is_deleted = 0
  AND ($1::text IS NULL OR (name LIKE $1 OR dict_code LIKE $1))
ORDER BY create_time DESC
LIMIT  $3
OFFSET $2
`

type ListDictsParams struct {
	Keywords *string
	Offset   *int32
	Limit    *int32
}

func (q *Queries) ListDicts(ctx context.Context, arg ListDictsParams) ([]TDict, error) {
	rows, err := q.db.Query(ctx, listDicts, arg.Keywords, arg.Offset, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TDict{}
	for rows.Next() {
		var i TDict
		if err := rows.Scan(
			&i.ID,
			&i.DictCode,
			&i.Name,
			&i.Status,
			&i.Remark,
			&i.CreateBy,
			&i.CreateTime,
			&i.UpdateBy,
			&i.UpdateTime,
			&i.IsDeleted,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDictsByIDs = `-- name: ListDictsByIDs :many
SELECT id, dict_code, name, status, remark, create_by, create_time, update_by, update_time, is_deleted FROM t_dict WHERE is_deleted = 0 AND id = ANY($1::text[])
`

func (q *Queries) ListDictsByIDs(ctx context.Context, ids []string) ([]TDict, error) {
	rows, err := q.db.Query(ctx, listDictsByIDs, ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TDict{}
	for rows.Next() {
		var i TDict
		if err := rows.Scan(
			&i.ID,
			&i.DictCode,
			&i.Name,
			&i.Status,
			&i.Remark,
			&i.CreateBy,
			&i.CreateTime,
			&i.UpdateBy,
			&i.UpdateTime,
			&i.IsDeleted,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEnabledDicts = `-- name: ListEnabledDicts :many
SELECT id, dict_code, name, status, remark, create_by, create_time, update_by, update_time, is_deleted FROM t_dict WHERE is_deleted = 0 AND status = 1
`

func (q *Queries) ListEnabledDicts(ctx context.Context) ([]TDict, error) {
	rows, err := q.db.Query(ctx, listEnabledDicts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TDict{}
	for rows.Next() {
		var i TDict
		if err := rows.Scan(
			&i.ID,
			&i.DictCode,
			&i.Name,
			&i.Status,
			&i.Remark,
			&i.CreateBy,
			&i.CreateTime,
			&i.UpdateBy,
			&i.UpdateTime,
			&i.IsDeleted,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteDict = `-- name: SoftDeleteDict :exec
UPDATE t_dict SET is_deleted = 1, update_by = $2, update_time = NOW() WHERE id = $1
`

type SoftDeleteDictParams struct {
	ID       string
	UpdateBy string
}

func (q *Queries) SoftDeleteDict(ctx context.Context, arg SoftDeleteDictParams) error {
	_, err := q.db.Exec(ctx, softDeleteDict, arg.ID, arg.UpdateBy)
	return err
}

const softDeleteDictsByIDs = `-- name: SoftDeleteDictsByIDs :exec
UPDATE t_dict SET is_deleted = 1, update_by = $1, update_time = NOW()
WHERE id = ANY($2::text[])
`

type SoftDeleteDictsByIDsParams struct {
	UpdateBy string
	Ids      []string
}

func (q *Queries) SoftDeleteDictsByIDs(ctx context.Context, arg SoftDeleteDictsByIDsParams) error {
	_, err := q.db.Exec(ctx, softDeleteDictsByIDs, arg.UpdateBy, arg.Ids)
	return err
}

const updateDict = `-- name: UpdateDict :exec
UPDATE t_dict SET
    dict_code   = $2,
    name        = $3,
    status      = $4,
    remark      = $5,
    update_by   = $6,
    update_time = NOW()
WHERE id = $1
`

type UpdateDictParams struct {
	ID       string
	DictCode string
	Name     string
	Status   int32
	Remark   string
	UpdateBy string
}

func (q *Queries) UpdateDict(ctx context.Context, arg UpdateDictParams) error {
	_, err := q.db.Exec(ctx, updateDict,
		arg.ID,
		arg.DictCode,
		arg.Name,
		arg.Status,
		arg.Remark,
		arg.UpdateBy,
	)
	return err
}
