// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: dict_item.sql

package sqlc

import (
	"context"
)

const countDictItems = `-- name: CountDictItems :one
SELECT COUNT(*) FROM t_dict_item
WHERE is_deleted = 0
  AND ($1::text IS NULL OR dict_code = $1)
  AND ($2::text  IS NULL OR (label LIKE $2 OR value LIKE $2))
`

type CountDictItemsParams struct {
	DictCode *string
	Keywords *string
}

func (q *Queries) CountDictItems(ctx context.Context, arg CountDictItemsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countDictItems, arg.DictCode, arg.Keywords)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createDictItem = `-- name: CreateDictItem :exec
INSERT INTO t_dict_item (
    id, dict_code, label, value, tag_type, sort, status, remark,
    create_by, update_by, is_deleted, create_time, update_time
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8,
    $9, $10, $11, NOW(), NOW()
)
`

type CreateDictItemParams struct {
	ID        string
	DictCode  string
	Label     string
	Value     string
	TagType   string
	Sort      int32
	Status    int32
	Remark    string
	CreateBy  string
	UpdateBy  string
	IsDeleted int32
}

func (q *Queries) CreateDictItem(ctx context.Context, arg CreateDictItemParams) error {
	_, err := q.db.Exec(ctx, createDictItem,
		arg.ID,
		arg.DictCode,
		arg.Label,
		arg.Value,
		arg.TagType,
		arg.Sort,
		arg.Status,
		arg.Remark,
		arg.CreateBy,
		arg.UpdateBy,
		arg.IsDeleted,
	)
	return err
}

const getDictItem = `-- name: GetDictItem :one

SELECT id, dict_code, label, value, tag_type, sort, status, remark, create_by, create_time, update_by, update_time, is_deleted FROM t_dict_item WHERE id = $1 AND is_deleted = 0
`

// dict_item.sql
// SQL for dictionary items (t_dict_item). Dynamic filters use sqlc.narg so one
// prepared statement serves every filter combination. Ordering is fixed
// (sort ASC) — the previous GORM default.
func (q *Queries) GetDictItem(ctx context.Context, id string) (TDictItem, error) {
	row := q.db.QueryRow(ctx, getDictItem, id)
	var i TDictItem
	err := row.Scan(
		&i.ID,
		&i.DictCode,
		&i.Label,
		&i.Value,
		&i.TagType,
		&i.Sort,
		&i.Status,
		&i.Remark,
		&i.CreateBy,
		&i.CreateTime,
		&i.UpdateBy,
		&i.UpdateTime,
		&i.IsDeleted,
	)
	return i, err
}

const listDictItems = `-- name: ListDictItems :many
SELECT id, dict_code, label, value, tag_type, sort, status, remark, create_by, create_time, update_by, update_time, is_deleted FROM t_dict_item
WHERE is_deleted = 0
  AND ($1::text IS NULL OR dict_code = $1)
  AND ($2::text  IS NULL OR (label LIKE $2 OR value LIKE $2))
ORDER BY sort ASC
LIMIT  $4
OFFSET $3
`

type ListDictItemsParams struct {
	DictCode *string
	Keywords *string
	Offset   *int32
	Limit    *int32
}

func (q *Queries) ListDictItems(ctx context.Context, arg ListDictItemsParams) ([]TDictItem, error) {
	rows, err := q.db.Query(ctx, listDictItems,
		arg.DictCode,
		arg.Keywords,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TDictItem{}
	for rows.Next() {
		var i TDictItem
		if err := rows.Scan(
			&i.ID,
			&i.DictCode,
			&i.Label,
			&i.Value,
			&i.TagType,
			&i.Sort,
			&i.Status,
			&i.Remark,
			&i.CreateBy,
			&i.CreateTime,
			&i.UpdateBy,
			&i.UpdateTime,
			&i.IsDeleted,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDictItemsByDictCode = `-- name: ListDictItemsByDictCode :many
SELECT id, dict_code, label, value, tag_type, sort, status, remark, create_by, create_time, update_by, update_time, is_deleted FROM t_dict_item
WHERE dict_code = $1 AND is_deleted = 0 AND status = 1
ORDER BY sort ASC
`

func (q *Queries) ListDictItemsByDictCode(ctx context.Context, dictCode string) ([]TDictItem, error) {
	rows, err := q.db.Query(ctx, listDictItemsByDictCode, dictCode)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TDictItem{}
	for rows.Next() {
		var i TDictItem
		if err := rows.Scan(
			&i.ID,
			&i.DictCode,
			&i.Label,
			&i.Value,
			&i.TagType,
			&i.Sort,
			&i.Status,
			&i.Remark,
			&i.CreateBy,
			&i.CreateTime,
			&i.UpdateBy,
			&i.UpdateTime,
			&i.IsDeleted,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteDictItem = `-- name: SoftDeleteDictItem :exec
UPDATE t_dict_item SET is_deleted = 1, update_by = $2, update_time = NOW() WHERE id = $1
`

type SoftDeleteDictItemParams struct {
	ID       string
	UpdateBy string
}

func (q *Queries) SoftDeleteDictItem(ctx context.Context, arg SoftDeleteDictItemParams) error {
	_, err := q.db.Exec(ctx, softDeleteDictItem, arg.ID, arg.UpdateBy)
	return err
}

const softDeleteDictItemsByDictCodes = `-- name: SoftDeleteDictItemsByDictCodes :exec
UPDATE t_dict_item SET is_deleted = 1, update_by = $1, update_time = NOW()
WHERE dict_code = ANY($2::text[])
`

type SoftDeleteDictItemsByDictCodesParams struct {
	UpdateBy  string
	DictCodes []string
}

func (q *Queries) SoftDeleteDictItemsByDictCodes(ctx context.Context, arg SoftDeleteDictItemsByDictCodesParams) error {
	_, err := q.db.Exec(ctx, softDeleteDictItemsByDictCodes, arg.UpdateBy, arg.DictCodes)
	return err
}

const softDeleteDictItemsByIDs = `-- name: SoftDeleteDictItemsByIDs :exec
UPDATE t_dict_item SET is_deleted = 1, update_by = $1, update_time = NOW()
WHERE id = ANY($2::text[])
`

type SoftDeleteDictItemsByIDsParams struct {
	UpdateBy string
	Ids      []string
}

func (q *Queries) SoftDeleteDictItemsByIDs(ctx context.Context, arg SoftDeleteDictItemsByIDsParams) error {
	_, err := q.db.Exec(ctx, softDeleteDictItemsByIDs, arg.UpdateBy, arg.Ids)
	return err
}

const updateDictItem = `-- name: UpdateDictItem :exec
UPDATE t_dict_item SET
    dict_code   = $2,
    label       = $3,
    value       = $4,
    tag_type    = $5,
    sort        = $6,
    status      = $7,
    remark      = $8,
    update_by   = $9,
    update_time = NOW()
WHERE id = $1
`

type UpdateDictItemParams struct {
	ID       string
	DictCode string
	Label    string
	Value    string
	TagType  string
	Sort     int32
	Status   int32
	Remark   string
	UpdateBy string
}

func (q *Queries) UpdateDictItem(ctx context.Context, arg UpdateDictItemParams) error {
	_, err := q.db.Exec(ctx, updateDictItem,
		arg.ID,
		arg.DictCode,
		arg.Label,
		arg.Value,
		arg.TagType,
		arg.Sort,
		arg.Status,
		arg.Remark,
		arg.UpdateBy,
	)
	return err
}

const updateDictItemsDictCode = `-- name: UpdateDictItemsDictCode :exec
UPDATE t_dict_item SET dict_code = $1, update_time = NOW()
WHERE dict_code = $2
`

type UpdateDictItemsDictCodeParams struct {
	NewCode string
	OldCode string
}

// Cascade a dictionary code rename onto its items. Called by DictRepository when a
// dictionary's code changes.
func (q *Queries) UpdateDictItemsDictCode(ctx context.Context, arg UpdateDictItemsDictCodeParams) error {
	_, err := q.db.Exec(ctx, updateDictItemsDictCode, arg.NewCode, arg.OldCode)
	return err
}
