// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: download.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const batchDeleteDownloadTasks = `-- name: BatchDeleteDownloadTasks :exec
DELETE FROM sys_download_tasks WHERE id = ANY($1::bigint[])
`

func (q *Queries) BatchDeleteDownloadTasks(ctx context.Context, ids []int64) error {
	_, err := q.db.Exec(ctx, batchDeleteDownloadTasks, ids)
	return err
}

const countDownloadTasks = `-- name: CountDownloadTasks :one
SELECT COUNT(*) FROM sys_download_tasks
WHERE ($1::text     IS NULL OR status = $1)
  AND ($2::text IS NULL OR downloader = $2)
  AND ($3::text   IS NULL OR (
        name LIKE $3 OR url LIKE $3 OR
        save_path LIKE $3 OR hash LIKE $3))
  AND ($4::timestamptz IS NULL OR created_at >= $4)
  AND ($5::timestamptz   IS NULL OR created_at <= $5)
`

type CountDownloadTasksParams struct {
	Status     *string
	Downloader *string
	Keywords   *string
	CreateFrom pgtype.Timestamptz
	CreateTo   pgtype.Timestamptz
}

func (q *Queries) CountDownloadTasks(ctx context.Context, arg CountDownloadTasksParams) (int64, error) {
	row := q.db.QueryRow(ctx, countDownloadTasks,
		arg.Status,
		arg.Downloader,
		arg.Keywords,
		arg.CreateFrom,
		arg.CreateTo,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createDownloadTask = `-- name: CreateDownloadTask :one
INSERT INTO sys_download_tasks (
    queue_task_id, task_id, hash, name, url, downloader, status,
    total, downloaded, download_speed, uploaded, upload_speed,
    save_path, error_message, owner_id, created_at, updated_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7,
    $8, $9, $10, $11, $12,
    $13, $14, $15, NOW(), NOW()
)
RETURNING id
`

type CreateDownloadTaskParams struct {
	QueueTaskID   int64
	TaskID        string
	Hash          string
	Name          string
	Url           string
	Downloader    string
	Status        string
	Total         int64
	Downloaded    int64
	DownloadSpeed int64
	Uploaded      int64
	UploadSpeed   int64
	SavePath      string
	ErrorMessage  string
	OwnerID       string
}

func (q *Queries) CreateDownloadTask(ctx context.Context, arg CreateDownloadTaskParams) (int64, error) {
	row := q.db.QueryRow(ctx, createDownloadTask,
		arg.QueueTaskID,
		arg.TaskID,
		arg.Hash,
		arg.Name,
		arg.Url,
		arg.Downloader,
		arg.Status,
		arg.Total,
		arg.Downloaded,
		arg.DownloadSpeed,
		arg.Uploaded,
		arg.UploadSpeed,
		arg.SavePath,
		arg.ErrorMessage,
		arg.OwnerID,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const deleteDownloadTask = `-- name: DeleteDownloadTask :exec
DELETE FROM sys_download_tasks WHERE id = $1
`

func (q *Queries) DeleteDownloadTask(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteDownloadTask, id)
	return err
}

const getDownloadTask = `-- name: GetDownloadTask :one

SELECT id, queue_task_id, task_id, hash, name, url, downloader, status, total, downloaded, download_speed, uploaded, upload_speed, save_path, error_message, owner_id, created_at, updated_at, deleted_at FROM sys_download_tasks WHERE id = $1
`

// download.sql
// SQL for download tasks (sys_download_tasks). Dynamic filters use sqlc.narg;
// date-range bounds are passed as timestamptz. Ordering is fixed to created_at
// DESC — the previous GORM default.
func (q *Queries) GetDownloadTask(ctx context.Context, id int64) (SysDownloadTask, error) {
	row := q.db.QueryRow(ctx, getDownloadTask, id)
	var i SysDownloadTask
	err := row.Scan(
		&i.ID,
		&i.QueueTaskID,
		&i.TaskID,
		&i.Hash,
		&i.Name,
		&i.Url,
		&i.Downloader,
		&i.Status,
		&i.Total,
		&i.Downloaded,
		&i.DownloadSpeed,
		&i.Uploaded,
		&i.UploadSpeed,
		&i.SavePath,
		&i.ErrorMessage,
		&i.OwnerID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getDownloadTaskByQueueTaskID = `-- name: GetDownloadTaskByQueueTaskID :one
SELECT id, queue_task_id, task_id, hash, name, url, downloader, status, total, downloaded, download_speed, uploaded, upload_speed, save_path, error_message, owner_id, created_at, updated_at, deleted_at FROM sys_download_tasks WHERE queue_task_id = $1
`

func (q *Queries) GetDownloadTaskByQueueTaskID(ctx context.Context, queueTaskID int64) (SysDownloadTask, error) {
	row := q.db.QueryRow(ctx, getDownloadTaskByQueueTaskID, queueTaskID)
	var i SysDownloadTask
	err := row.Scan(
		&i.ID,
		&i.QueueTaskID,
		&i.TaskID,
		&i.Hash,
		&i.Name,
		&i.Url,
		&i.Downloader,
		&i.Status,
		&i.Total,
		&i.Downloaded,
		&i.DownloadSpeed,
		&i.Uploaded,
		&i.UploadSpeed,
		&i.SavePath,
		&i.ErrorMessage,
		&i.OwnerID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getDownloadTaskByTaskID = `-- name: GetDownloadTaskByTaskID :one
SELECT id, queue_task_id, task_id, hash, name, url, downloader, status, total, downloaded, download_speed, uploaded, upload_speed, save_path, error_message, owner_id, created_at, updated_at, deleted_at FROM sys_download_tasks WHERE task_id = $1
`

func (q *Queries) GetDownloadTaskByTaskID(ctx context.Context, taskID string) (SysDownloadTask, error) {
	row := q.db.QueryRow(ctx, getDownloadTaskByTaskID, taskID)
	var i SysDownloadTask
	err := row.Scan(
		&i.ID,
		&i.QueueTaskID,
		&i.TaskID,
		&i.Hash,
		&i.Name,
		&i.Url,
		&i.Downloader,
		&i.Status,
		&i.Total,
		&i.Downloaded,
		&i.DownloadSpeed,
		&i.Uploaded,
		&i.UploadSpeed,
		&i.SavePath,
		&i.ErrorMessage,
		&i.OwnerID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listActiveDownloadTasks = `-- name: ListActiveDownloadTasks :many
SELECT id, queue_task_id, task_id, hash, downloader FROM sys_download_tasks
WHERE status = ANY(ARRAY['downloading', 'seeding', 'unknown', 'queued'])
`

type ListActiveDownloadTasksRow struct {
	ID          int64
	QueueTaskID int64
	TaskID      string
	Hash        string
	Downloader  string
}

func (q *Queries) ListActiveDownloadTasks(ctx context.Context) ([]ListActiveDownloadTasksRow, error) {
	rows, err := q.db.Query(ctx, listActiveDownloadTasks)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListActiveDownloadTasksRow{}
	for rows.Next() {
		var i ListActiveDownloadTasksRow
		if err := rows.Scan(
			&i.ID,
			&i.QueueTaskID,
			&i.TaskID,
			&i.Hash,
			&i.Downloader,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDownloadStatusCounts = `-- name: ListDownloadStatusCounts :many
SELECT status, COUNT(*) AS count FROM sys_download_tasks GROUP BY status
`

type ListDownloadStatusCountsRow struct {
	Status string
	Count  int64
}

func (q *Queries) ListDownloadStatusCounts(ctx context.Context) ([]ListDownloadStatusCountsRow, error) {
	rows, err := q.db.Query(ctx, listDownloadStatusCounts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListDownloadStatusCountsRow{}
	for rows.Next() {
		var i ListDownloadStatusCountsRow
		if err := rows.Scan(&i.Status, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDownloadTasks = `-- name: ListDownloadTasks :many
SELECT id, queue_task_id, task_id, hash, name, url, downloader, status, total, downloaded, download_speed, uploaded, upload_speed, save_path, error_message, owner_id, created_at, updated_at, deleted_at FROM sys_download_tasks
WHERE ($1::text     IS NULL OR status = $1)
  AND ($2::text IS NULL OR downloader = $2)
  AND ($3::text   IS NULL OR (
        name LIKE $3 OR url LIKE $3 OR
        save_path LIKE $3 OR hash LIKE $3))
  AND ($4::timestamptz IS NULL OR created_at >= $4)
  AND ($5::timestamptz   IS NULL OR created_at <= $5)
ORDER BY created_at DESC
LIMIT  $7
OFFSET $6
`

type ListDownloadTasksParams struct {
	Status     *string
	Downloader *string
	Keywords   *string
	CreateFrom pgtype.Timestamptz
	CreateTo   pgtype.Timestamptz
	Offset     *int32
	Limit      *int32
}

func (q *Queries) ListDownloadTasks(ctx context.Context, arg ListDownloadTasksParams) ([]SysDownloadTask, error) {
	rows, err := q.db.Query(ctx, listDownloadTasks,
		arg.Status,
		arg.Downloader,
		arg.Keywords,
		arg.CreateFrom,
		arg.CreateTo,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SysDownloadTask{}
	for rows.Next() {
		var i SysDownloadTask
		if err := rows.Scan(
			&i.ID,
			&i.QueueTaskID,
			&i.TaskID,
			&i.Hash,
			&i.Name,
			&i.Url,
			&i.Downloader,
			&i.Status,
			&i.Total,
			&i.Downloaded,
			&i.DownloadSpeed,
			&i.Uploaded,
			&i.UploadSpeed,
			&i.SavePath,
			&i.ErrorMessage,
			&i.OwnerID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateDownloadTask = `-- name: UpdateDownloadTask :exec
UPDATE sys_download_tasks SET
    queue_task_id  = $2,
    task_id        = $3,
    hash           = $4,
    name           = $5,
    url            = $6,
    downloader     = $7,
    status         = $8,
    total          = $9,
    downloaded     = $10,
    download_speed = $11,
    uploaded       = $12,
    upload_speed   = $13,
    save_path      = $14,
    error_message  = $15,
    owner_id       = $16,
    updated_at     = NOW()
WHERE id = $1
`

type UpdateDownloadTaskParams struct {
	ID            int64
	QueueTaskID   int64
	TaskID        string
	Hash          string
	Name          string
	Url           string
	Downloader    string
	Status        string
	Total         int64
	Downloaded    int64
	DownloadSpeed int64
	Uploaded      int64
	UploadSpeed   int64
	SavePath      string
	ErrorMessage  string
	OwnerID       string
}

func (q *Queries) UpdateDownloadTask(ctx context.Context, arg UpdateDownloadTaskParams) error {
	_, err := q.db.Exec(ctx, updateDownloadTask,
		arg.ID,
		arg.QueueTaskID,
		arg.TaskID,
		arg.Hash,
		arg.Name,
		arg.Url,
		arg.Downloader,
		arg.Status,
		arg.Total,
		arg.Downloaded,
		arg.DownloadSpeed,
		arg.Uploaded,
		arg.UploadSpeed,
		arg.SavePath,
		arg.ErrorMessage,
		arg.OwnerID,
	)
	return err
}

const updateDownloadTaskFromDownloader = `-- name: UpdateDownloadTaskFromDownloader :exec
UPDATE sys_download_tasks SET
    status         = $1,
    downloaded     = $2,
    total          = $3,
    download_speed = $4,
    uploaded       = $5,
    upload_speed   = $6,
    error_message  = $7,
    task_id        = COALESCE(NULLIF($8, ''), task_id),
    hash           = COALESCE(NULLIF($9, ''), hash),
    name           = COALESCE(NULLIF($10, ''), name),
    save_path      = COALESCE(NULLIF($11, ''), save_path),
    updated_at     = NOW()
WHERE id = $12
`

type UpdateDownloadTaskFromDownloaderParams struct {
	Status        string
	Downloaded    int64
	Total         int64
	DownloadSpeed int64
	Uploaded      int64
	UploadSpeed   int64
	ErrorMessage  string
	TaskID        interface{}
	Hash          interface{}
	Name          interface{}
	SavePath      interface{}
	ID            int64
}

// Updates progress and, only when a non-empty value is supplied, the identity
// fields (task_id, hash, name, save_path). NULLIF(arg,”) + COALESCE keeps the
// existing value for empty arguments, mirroring the previous conditional map.
func (q *Queries) UpdateDownloadTaskFromDownloader(ctx context.Context, arg UpdateDownloadTaskFromDownloaderParams) error {
	_, err := q.db.Exec(ctx, updateDownloadTaskFromDownloader,
		arg.Status,
		arg.Downloaded,
		arg.Total,
		arg.DownloadSpeed,
		arg.Uploaded,
		arg.UploadSpeed,
		arg.ErrorMessage,
		arg.TaskID,
		arg.Hash,
		arg.Name,
		arg.SavePath,
		arg.ID,
	)
	return err
}

const updateDownloadTaskStatus = `-- name: UpdateDownloadTaskStatus :exec
UPDATE sys_download_tasks SET
    status         = $2,
    downloaded     = $3,
    total          = $4,
    download_speed = $5,
    uploaded       = $6,
    upload_speed   = $7,
    error_message  = $8,
    updated_at     = NOW()
WHERE id = $1
`

type UpdateDownloadTaskStatusParams struct {
	ID            int64
	Status        string
	Downloaded    int64
	Total         int64
	DownloadSpeed int64
	Uploaded      int64
	UploadSpeed   int64
	ErrorMessage  string
}

func (q *Queries) UpdateDownloadTaskStatus(ctx context.Context, arg UpdateDownloadTaskStatusParams) error {
	_, err := q.db.Exec(ctx, updateDownloadTaskStatus,
		arg.ID,
		arg.Status,
		arg.Downloaded,
		arg.Total,
		arg.DownloadSpeed,
		arg.Uploaded,
		arg.UploadSpeed,
		arg.ErrorMessage,
	)
	return err
}
