// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: member.sql

package sqlc

import (
	"context"
)

const countMembers = `-- name: CountMembers :one
SELECT COUNT(*) FROM t_member
WHERE is_deleted = 0
  AND ($1::text IS NULL OR tenant_id = $1)
  AND ($2::text  IS NULL OR (username LIKE $2 OR nickname LIKE $2 OR email LIKE $2))
  AND ($3::int     IS NULL OR status = $3)
`

type CountMembersParams struct {
	TenantID *string
	Keywords *string
	Status   *int32
}

func (q *Queries) CountMembers(ctx context.Context, arg CountMembersParams) (int64, error) {
	row := q.db.QueryRow(ctx, countMembers, arg.TenantID, arg.Keywords, arg.Status)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countMembersByUsername = `-- name: CountMembersByUsername :one
SELECT COUNT(*) FROM t_member
WHERE tenant_id = $1 AND username = $2 AND is_deleted = 0
`

type CountMembersByUsernameParams struct {
	TenantID string
	Username string
}

func (q *Queries) CountMembersByUsername(ctx context.Context, arg CountMembersByUsernameParams) (int64, error) {
	row := q.db.QueryRow(ctx, countMembersByUsername, arg.TenantID, arg.Username)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createMember = `-- name: CreateMember :exec
INSERT INTO t_member (
    id, tenant_id, username, email, mobile, password, nickname, avatar,
    gender, status, is_deleted, create_time, update_time
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8,
    $9, $10, $11, NOW(), NOW()
)
`

type CreateMemberParams struct {
	ID        string
	TenantID  string
	Username  string
	Email     string
	Mobile    string
	Password  string
	Nickname  string
	Avatar    string
	Gender    int32
	Status    int32
	IsDeleted int32
}

func (q *Queries) CreateMember(ctx context.Context, arg CreateMemberParams) error {
	_, err := q.db.Exec(ctx, createMember,
		arg.ID,
		arg.TenantID,
		arg.Username,
		arg.Email,
		arg.Mobile,
		arg.Password,
		arg.Nickname,
		arg.Avatar,
		arg.Gender,
		arg.Status,
		arg.IsDeleted,
	)
	return err
}

const getMemberByID = `-- name: GetMemberByID :one
SELECT id, tenant_id, username, email, mobile, password, nickname, avatar, gender, status, last_login_time, last_login_ip, create_time, update_time, is_deleted FROM t_member
WHERE tenant_id = $1 AND id = $2 AND is_deleted = 0
`

type GetMemberByIDParams struct {
	TenantID string
	ID       string
}

func (q *Queries) GetMemberByID(ctx context.Context, arg GetMemberByIDParams) (TMember, error) {
	row := q.db.QueryRow(ctx, getMemberByID, arg.TenantID, arg.ID)
	var i TMember
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Username,
		&i.Email,
		&i.Mobile,
		&i.Password,
		&i.Nickname,
		&i.Avatar,
		&i.Gender,
		&i.Status,
		&i.LastLoginTime,
		&i.LastLoginIp,
		&i.CreateTime,
		&i.UpdateTime,
		&i.IsDeleted,
	)
	return i, err
}

const getMemberByUsername = `-- name: GetMemberByUsername :one

SELECT id, tenant_id, username, email, mobile, password, nickname, avatar, gender, status, last_login_time, last_login_ip, create_time, update_time, is_deleted FROM t_member
WHERE tenant_id = $1 AND username = $2 AND is_deleted = 0
`

type GetMemberByUsernameParams struct {
	TenantID string
	Username string
}

// member.sql
// SQL for the member domain (t_member). All member access is tenant-scoped: every
// statement filters by tenant_id to enforce row-level isolation. Ordering is fixed
// to id DESC (the previous GORM default); dynamic filters use sqlc.narg.
func (q *Queries) GetMemberByUsername(ctx context.Context, arg GetMemberByUsernameParams) (TMember, error) {
	row := q.db.QueryRow(ctx, getMemberByUsername, arg.TenantID, arg.Username)
	var i TMember
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Username,
		&i.Email,
		&i.Mobile,
		&i.Password,
		&i.Nickname,
		&i.Avatar,
		&i.Gender,
		&i.Status,
		&i.LastLoginTime,
		&i.LastLoginIp,
		&i.CreateTime,
		&i.UpdateTime,
		&i.IsDeleted,
	)
	return i, err
}

const listMembers = `-- name: ListMembers :many
SELECT id, tenant_id, username, email, mobile, password, nickname, avatar, gender, status, last_login_time, last_login_ip, create_time, update_time, is_deleted FROM t_member
WHERE is_deleted = 0
  AND ($1::text IS NULL OR tenant_id = $1)
  AND ($2::text  IS NULL OR (username LIKE $2 OR nickname LIKE $2 OR email LIKE $2))
  AND ($3::int     IS NULL OR status = $3)
ORDER BY id DESC
LIMIT  $5
OFFSET $4
`

type ListMembersParams struct {
	TenantID *string
	Keywords *string
	Status   *int32
	Offset   *int32
	Limit    *int32
}

func (q *Queries) ListMembers(ctx context.Context, arg ListMembersParams) ([]TMember, error) {
	rows, err := q.db.Query(ctx, listMembers,
		arg.TenantID,
		arg.Keywords,
		arg.Status,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TMember{}
	for rows.Next() {
		var i TMember
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Username,
			&i.Email,
			&i.Mobile,
			&i.Password,
			&i.Nickname,
			&i.Avatar,
			&i.Gender,
			&i.Status,
			&i.LastLoginTime,
			&i.LastLoginIp,
			&i.CreateTime,
			&i.UpdateTime,
			&i.IsDeleted,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateMemberLoginInfo = `-- name: UpdateMemberLoginInfo :exec
UPDATE t_member SET last_login_ip = $3, last_login_time = NOW(), update_time = NOW()
WHERE tenant_id = $1 AND id = $2
`

type UpdateMemberLoginInfoParams struct {
	TenantID    string
	ID          string
	LastLoginIp string
}

func (q *Queries) UpdateMemberLoginInfo(ctx context.Context, arg UpdateMemberLoginInfoParams) error {
	_, err := q.db.Exec(ctx, updateMemberLoginInfo, arg.TenantID, arg.ID, arg.LastLoginIp)
	return err
}

const updateMemberPassword = `-- name: UpdateMemberPassword :exec
UPDATE t_member SET password = $3, update_time = NOW()
WHERE tenant_id = $1 AND id = $2
`

type UpdateMemberPasswordParams struct {
	TenantID string
	ID       string
	Password string
}

func (q *Queries) UpdateMemberPassword(ctx context.Context, arg UpdateMemberPasswordParams) error {
	_, err := q.db.Exec(ctx, updateMemberPassword, arg.TenantID, arg.ID, arg.Password)
	return err
}

const updateMemberProfile = `-- name: UpdateMemberProfile :exec
UPDATE t_member SET
    nickname    = $1,
    avatar      = $2,
    gender      = $3,
    mobile      = $4,
    email       = $5,
    update_time = NOW()
WHERE tenant_id = $6 AND id = $7
`

type UpdateMemberProfileParams struct {
	Nickname string
	Avatar   string
	Gender   int32
	Mobile   string
	Email    string
	TenantID string
	ID       string
}

func (q *Queries) UpdateMemberProfile(ctx context.Context, arg UpdateMemberProfileParams) error {
	_, err := q.db.Exec(ctx, updateMemberProfile,
		arg.Nickname,
		arg.Avatar,
		arg.Gender,
		arg.Mobile,
		arg.Email,
		arg.TenantID,
		arg.ID,
	)
	return err
}

const updateMemberStatus = `-- name: UpdateMemberStatus :exec
UPDATE t_member SET status = $3, update_time = NOW()
WHERE tenant_id = $1 AND id = $2
`

type UpdateMemberStatusParams struct {
	TenantID string
	ID       string
	Status   int32
}

func (q *Queries) UpdateMemberStatus(ctx context.Context, arg UpdateMemberStatusParams) error {
	_, err := q.db.Exec(ctx, updateMemberStatus, arg.TenantID, arg.ID, arg.Status)
	return err
}
