// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: notice.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countNotices = `-- name: CountNotices :one
SELECT COUNT(*) FROM t_notice
WHERE is_deleted = 0
  AND ($1::text IS NULL OR title LIKE $1)
  AND ($2::int   IS NULL OR type = $2)
  AND ($3::int IS NULL OR publish_status = $3)
`

type CountNoticesParams struct {
	Title         *string
	Type          *int32
	PublishStatus *int32
}

func (q *Queries) CountNotices(ctx context.Context, arg CountNoticesParams) (int64, error) {
	row := q.db.QueryRow(ctx, countNotices, arg.Title, arg.Type, arg.PublishStatus)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createNotice = `-- name: CreateNotice :exec
INSERT INTO t_notice (
    id, title, content, type, level, target_type, target_user_ids,
    publish_status, create_by, is_deleted, create_time, update_time
) VALUES (
    $1, $2, $3, $4, $5, $6, $7,
    $8, $9, $10, NOW(), NOW()
)
`

type CreateNoticeParams struct {
	ID            string
	Title         string
	Content       string
	Type          int32
	Level         string
	TargetType    int32
	TargetUserIds string
	PublishStatus int32
	CreateBy      string
	IsDeleted     int32
}

func (q *Queries) CreateNotice(ctx context.Context, arg CreateNoticeParams) error {
	_, err := q.db.Exec(ctx, createNotice,
		arg.ID,
		arg.Title,
		arg.Content,
		arg.Type,
		arg.Level,
		arg.TargetType,
		arg.TargetUserIds,
		arg.PublishStatus,
		arg.CreateBy,
		arg.IsDeleted,
	)
	return err
}

const getNotice = `-- name: GetNotice :one

SELECT id, title, content, type, level, target_type, target_user_ids, publisher_id, publish_status, publish_time, revoke_time, create_by, create_time, update_by, update_time, is_deleted FROM t_notice WHERE id = $1 AND is_deleted = 0
`

// notice.sql
// SQL for notices (t_notice). Dynamic filters use sqlc.narg; ordering is fixed to
// create_time DESC — the previous GORM default. publish_time / revoke_time are
// set conditionally via COALESCE so a single statement handles publish and revoke.
func (q *Queries) GetNotice(ctx context.Context, id string) (TNotice, error) {
	row := q.db.QueryRow(ctx, getNotice, id)
	var i TNotice
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Content,
		&i.Type,
		&i.Level,
		&i.TargetType,
		&i.TargetUserIds,
		&i.PublisherID,
		&i.PublishStatus,
		&i.PublishTime,
		&i.RevokeTime,
		&i.CreateBy,
		&i.CreateTime,
		&i.UpdateBy,
		&i.UpdateTime,
		&i.IsDeleted,
	)
	return i, err
}

const listNotices = `-- name: ListNotices :many
SELECT id, title, content, type, level, target_type, target_user_ids, publisher_id, publish_status, publish_time, revoke_time, create_by, create_time, update_by, update_time, is_deleted FROM t_notice
WHERE is_deleted = 0
  AND ($1::text IS NULL OR title LIKE $1)
  AND ($2::int   IS NULL OR type = $2)
  AND ($3::int IS NULL OR publish_status = $3)
ORDER BY create_time DESC
LIMIT  $5
OFFSET $4
`

type ListNoticesParams struct {
	Title         *string
	Type          *int32
	PublishStatus *int32
	Offset        *int32
	Limit         *int32
}

func (q *Queries) ListNotices(ctx context.Context, arg ListNoticesParams) ([]TNotice, error) {
	rows, err := q.db.Query(ctx, listNotices,
		arg.Title,
		arg.Type,
		arg.PublishStatus,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TNotice{}
	for rows.Next() {
		var i TNotice
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Content,
			&i.Type,
			&i.Level,
			&i.TargetType,
			&i.TargetUserIds,
			&i.PublisherID,
			&i.PublishStatus,
			&i.PublishTime,
			&i.RevokeTime,
			&i.CreateBy,
			&i.CreateTime,
			&i.UpdateBy,
			&i.UpdateTime,
			&i.IsDeleted,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteNoticesByIDs = `-- name: SoftDeleteNoticesByIDs :exec
UPDATE t_notice SET is_deleted = 1, update_by = $1, update_time = NOW()
WHERE id = ANY($2::text[])
`

type SoftDeleteNoticesByIDsParams struct {
	UpdateBy string
	Ids      []string
}

func (q *Queries) SoftDeleteNoticesByIDs(ctx context.Context, arg SoftDeleteNoticesByIDsParams) error {
	_, err := q.db.Exec(ctx, softDeleteNoticesByIDs, arg.UpdateBy, arg.Ids)
	return err
}

const updateNotice = `-- name: UpdateNotice :exec
UPDATE t_notice SET
    title           = $2,
    content         = $3,
    type            = $4,
    level           = $5,
    target_type     = $6,
    target_user_ids = $7,
    update_by       = $8,
    update_time     = NOW()
WHERE id = $1
`

type UpdateNoticeParams struct {
	ID            string
	Title         string
	Content       string
	Type          int32
	Level         string
	TargetType    int32
	TargetUserIds string
	UpdateBy      string
}

func (q *Queries) UpdateNotice(ctx context.Context, arg UpdateNoticeParams) error {
	_, err := q.db.Exec(ctx, updateNotice,
		arg.ID,
		arg.Title,
		arg.Content,
		arg.Type,
		arg.Level,
		arg.TargetType,
		arg.TargetUserIds,
		arg.UpdateBy,
	)
	return err
}

const updateNoticeStatus = `-- name: UpdateNoticeStatus :exec
UPDATE t_notice SET
    publish_status = $1,
    publisher_id   = $2,
    publish_time   = COALESCE($3, publish_time),
    revoke_time    = COALESCE($4, revoke_time),
    update_time    = NOW()
WHERE id = $5
`

type UpdateNoticeStatusParams struct {
	PublishStatus int32
	PublisherID   string
	PublishTime   pgtype.Timestamptz
	RevokeTime    pgtype.Timestamptz
	ID            string
}

func (q *Queries) UpdateNoticeStatus(ctx context.Context, arg UpdateNoticeStatusParams) error {
	_, err := q.db.Exec(ctx, updateNoticeStatus,
		arg.PublishStatus,
		arg.PublisherID,
		arg.PublishTime,
		arg.RevokeTime,
		arg.ID,
	)
	return err
}
