// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"context"
)

type Querier interface {
	// Single-statement bulk insert via array unnest, keeping the whole batch atomic.
	BatchCreateRoleMenus(ctx context.Context, arg BatchCreateRoleMenusParams) error
	// Single-statement bulk insert via array unnest.
	BatchCreateUserNotices(ctx context.Context, arg BatchCreateUserNoticesParams) error
	// Single-statement bulk insert via array unnest, keeping the whole batch atomic.
	BatchCreateUserRoles(ctx context.Context, arg BatchCreateUserRolesParams) error
	BatchDeleteDownloadTasks(ctx context.Context, ids []int64) error
	BatchDeleteLogs(ctx context.Context, ids []string) error
	BatchDeleteTasks(ctx context.Context, ids []int64) error
	CountConfigs(ctx context.Context, keywords *string) (int64, error)
	// Counts non-deleted configs with the given key, optionally excluding one id.
	CountConfigsByKey(ctx context.Context, arg CountConfigsByKeyParams) (int64, error)
	CountDictItems(ctx context.Context, arg CountDictItemsParams) (int64, error)
	CountDicts(ctx context.Context, keywords *string) (int64, error)
	CountDownloadTasks(ctx context.Context, arg CountDownloadTasksParams) (int64, error)
	CountLogs(ctx context.Context, arg CountLogsParams) (int64, error)
	CountMembers(ctx context.Context, arg CountMembersParams) (int64, error)
	CountMembersByUsername(ctx context.Context, arg CountMembersByUsernameParams) (int64, error)
	CountMenus(ctx context.Context, arg CountMenusParams) (int64, error)
	CountMyNotices(ctx context.Context, arg CountMyNoticesParams) (int64, error)
	CountNotices(ctx context.Context, arg CountNoticesParams) (int64, error)
	CountRoles(ctx context.Context, arg CountRolesParams) (int64, error)
	CountTasks(ctx context.Context, arg CountTasksParams) (int64, error)
	CountTenants(ctx context.Context, arg CountTenantsParams) (int64, error)
	CountUserRoles(ctx context.Context, arg CountUserRolesParams) (int64, error)
	CountUsers(ctx context.Context, arg CountUsersParams) (int64, error)
	CreateConfig(ctx context.Context, arg CreateConfigParams) error
	CreateDept(ctx context.Context, arg CreateDeptParams) error
	CreateDict(ctx context.Context, arg CreateDictParams) error
	CreateDictItem(ctx context.Context, arg CreateDictItemParams) error
	CreateDownloadTask(ctx context.Context, arg CreateDownloadTaskParams) (int64, error)
	CreateLog(ctx context.Context, arg CreateLogParams) error
	CreateMember(ctx context.Context, arg CreateMemberParams) error
	CreateMenu(ctx context.Context, arg CreateMenuParams) error
	CreateNotice(ctx context.Context, arg CreateNoticeParams) error
	// queue_task.sql
	// SQL for the framework-agnostic pkg/queue engine over sys_tasks. Unlike the admin
	// Job module (task.sql), these queries honour soft-delete: reads filter
	// `deleted_at IS NULL`, Create/Update touch only live rows, and Delete is a soft
	// delete (sets deleted_at) — preserving the previous gorm.DeletedAt behaviour of
	// the engine's GORM TaskRepository. The sqlc implementation of queue.TaskRepository
	// lives in the application layer (lib) and is injected into pkg/queue.
	CreateQueueTask(ctx context.Context, arg CreateQueueTaskParams) (SysTask, error)
	CreateRole(ctx context.Context, arg CreateRoleParams) error
	CreateTenant(ctx context.Context, arg CreateTenantParams) error
	CreateUser(ctx context.Context, arg CreateUserParams) error
	CreateUserNotice(ctx context.Context, arg CreateUserNoticeParams) error
	CreateUserRole(ctx context.Context, arg CreateUserRoleParams) error
	DeleteDownloadTask(ctx context.Context, id int64) error
	DeleteLog(ctx context.Context, id string) error
	DeleteMenu(ctx context.Context, id string) error
	DeleteRoleMenusByMenuID(ctx context.Context, menuID string) error
	DeleteRoleMenusByRoleID(ctx context.Context, roleID string) error
	DeleteTask(ctx context.Context, id int64) error
	DeleteUserNoticesByNoticeID(ctx context.Context, noticeID string) error
	DeleteUserNoticesByNoticeIDs(ctx context.Context, noticeIds []string) error
	DeleteUserRolesByRoleID(ctx context.Context, roleID string) error
	DeleteUserRolesByUserID(ctx context.Context, userID string) error
	// config.sql
	// SQL for the system configuration domain (t_config). Dynamic filters use
	// sqlc.narg; ordering is fixed to id DESC (the previous GORM default).
	GetConfig(ctx context.Context, id string) (TConfig, error)
	GetConfigByKey(ctx context.Context, configKey string) (TConfig, error)
	// dept.sql
	// All SQL for the department domain (t_dept). Dynamic filters use sqlc.narg
	// (nullable args) so one prepared statement serves every filter combination while
	// staying fully parameterized. Ordering is a fixed `sort ASC` (the previous GORM
	// default), eliminating any ORDER BY injection surface.
	GetDept(ctx context.Context, id string) (TDept, error)
	// exclude_id lets callers ignore a specific row (used when validating a code on
	// update). A NULL exclude_id disables the exclusion.
	GetDeptByCode(ctx context.Context, arg GetDeptByCodeParams) (TDept, error)
	// dict.sql
	// SQL for the dictionary domain (t_dict). Dynamic filters use sqlc.narg so one
	// prepared statement serves every filter combination. Ordering is fixed
	// (create_time DESC) — the previous GORM default.
	GetDict(ctx context.Context, id string) (TDict, error)
	GetDictByCode(ctx context.Context, arg GetDictByCodeParams) (TDict, error)
	// dict_item.sql
	// SQL for dictionary items (t_dict_item). Dynamic filters use sqlc.narg so one
	// prepared statement serves every filter combination. Ordering is fixed
	// (sort ASC) — the previous GORM default.
	GetDictItem(ctx context.Context, id string) (TDictItem, error)
	// download.sql
	// SQL for download tasks (sys_download_tasks). Dynamic filters use sqlc.narg;
	// date-range bounds are passed as timestamptz. Ordering is fixed to created_at
	// DESC — the previous GORM default.
	GetDownloadTask(ctx context.Context, id int64) (SysDownloadTask, error)
	GetDownloadTaskByQueueTaskID(ctx context.Context, queueTaskID int64) (SysDownloadTask, error)
	GetDownloadTaskByTaskID(ctx context.Context, taskID string) (SysDownloadTask, error)
	// log.sql
	// SQL for the operation audit log (sys_log). Dynamic filters use sqlc.narg;
	// date-range bounds are passed as timestamptz (parsed in Go). Ordering is fixed
	// to create_time DESC — the previous GORM default.
	GetLog(ctx context.Context, id string) (SysLog, error)
	GetMemberByID(ctx context.Context, arg GetMemberByIDParams) (TMember, error)
	// member.sql
	// SQL for the member domain (t_member). All member access is tenant-scoped: every
	// statement filters by tenant_id to enforce row-level isolation. Ordering is fixed
	// to id DESC (the previous GORM default); dynamic filters use sqlc.narg.
	GetMemberByUsername(ctx context.Context, arg GetMemberByUsernameParams) (TMember, error)
	GetMenu(ctx context.Context, id string) (TMenu, error)
	// role_menu.sql
	// SQL for the role<->menu association (t_role_menu), scoped to the Role module's
	// access paths. The Menu module still reaches t_role_menu through GORM during the
	// transition, so its menu-side delete is intentionally NOT defined here.
	GetMenuIDsByRoleID(ctx context.Context, roleID string) ([]string, error)
	// notice.sql
	// SQL for notices (t_notice). Dynamic filters use sqlc.narg; ordering is fixed to
	// create_time DESC — the previous GORM default. publish_time / revoke_time are
	// set conditionally via COALESCE so a single statement handles publish and revoke.
	GetNotice(ctx context.Context, id string) (TNotice, error)
	GetQueueTask(ctx context.Context, id int64) (SysTask, error)
	// role.sql
	// All SQL for the role domain (t_role). Generated into db/sqlc by `make sqlc`.
	// Dynamic filters use sqlc.narg (nullable args): a NULL argument disables that
	// predicate, so a single prepared statement serves every filter combination
	// while remaining fully parameterized (no SQL injection surface). Ordering is a
	// fixed `id DESC` — the previous GORM default — rather than an interpolated
	// column, eliminating any ORDER BY injection surface.
	GetRole(ctx context.Context, id string) (TRole, error)
	GetRoleByCode(ctx context.Context, code string) (TRole, error)
	GetRoleIDsByUserID(ctx context.Context, userID string) ([]string, error)
	// task.sql
	// SQL for the admin Job module over sys_tasks. These queries intentionally do NOT
	// filter deleted_at (models/system.Task has no DeletedAt field), and Delete is a
	// hard DELETE — preserving the previous admin behaviour, which differs from the
	// pkg/queue engine's soft-delete view of the same table. Ordering is fixed to
	// created_at DESC; dynamic filters use sqlc.narg.
	GetTask(ctx context.Context, id int64) (SysTask, error)
	// tenant.sql
	// SQL for the tenant domain (t_tenant). Ordering is fixed to id DESC (the
	// previous GORM default); dynamic filters use sqlc.narg.
	GetTenant(ctx context.Context, id string) (TTenant, error)
	GetTenantByCode(ctx context.Context, code string) (TTenant, error)
	// user.sql
	// All SQL for the user domain. Generated into db/sqlc by `make sqlc`.
	// Dynamic filters use sqlc.narg (nullable args): a NULL argument disables that
	// predicate, so a single prepared statement serves every filter combination
	// while remaining fully parameterized (no SQL injection surface).
	GetUser(ctx context.Context, id string) (TUser, error)
	GetUserByUsername(ctx context.Context, username string) (TUser, error)
	GetUserIDsByRoleID(ctx context.Context, roleID string) ([]string, error)
	ListActiveDownloadTasks(ctx context.Context) ([]ListActiveDownloadTasksRow, error)
	ListAllConfigs(ctx context.Context) ([]TConfig, error)
	// Non-empty button (type = 4) permission strings for the given roles.
	ListButtonPermsByRoleIDs(ctx context.Context, roleIds []string) ([]string, error)
	ListConfigs(ctx context.Context, arg ListConfigsParams) ([]TConfig, error)
	ListDepts(ctx context.Context, arg ListDeptsParams) ([]TDept, error)
	ListDeptsByIDs(ctx context.Context, ids []string) ([]TDept, error)
	ListDictItems(ctx context.Context, arg ListDictItemsParams) ([]TDictItem, error)
	ListDictItemsByDictCode(ctx context.Context, dictCode string) ([]TDictItem, error)
	ListDicts(ctx context.Context, arg ListDictsParams) ([]TDict, error)
	ListDictsByIDs(ctx context.Context, ids []string) ([]TDict, error)
	ListDownloadStatusCounts(ctx context.Context) ([]ListDownloadStatusCountsRow, error)
	ListDownloadTasks(ctx context.Context, arg ListDownloadTasksParams) ([]SysDownloadTask, error)
	ListEnabledDepts(ctx context.Context) ([]TDept, error)
	ListEnabledDicts(ctx context.Context) ([]TDict, error)
	ListLogs(ctx context.Context, arg ListLogsParams) ([]SysLog, error)
	ListMembers(ctx context.Context, arg ListMembersParams) ([]TMember, error)
	// menu.sql
	// All SQL for the menu domain (t_menu). Dynamic filters use sqlc.narg (nullable
	// args) so one prepared statement serves every filter combination while staying
	// fully parameterized.
	//
	// Ordering is whitelisted, not interpolated: the bound order_by selects between
	// the only two orderings the application uses — sort ASC (order_by = 1) and the
	// default id DESC (order_by = 0). Each ORDER BY term is active in exactly one
	// mode, so there is no ORDER BY injection surface.
	ListMenus(ctx context.Context, arg ListMenusParams) ([]TMenu, error)
	// Menus assigned to any of the given roles, ordered by sort ASC.
	ListMenusByRoleIDs(ctx context.Context, roleIds []string) ([]TMenu, error)
	// user_notice.sql
	// SQL for per-user notice state (t_user_notice), including the "my notices" join.
	// Published, non-deleted notices addressed to a user, newest first. Projects the
	// fields the UI needs (UserNoticePageVO).
	ListMyNotices(ctx context.Context, arg ListMyNoticesParams) ([]ListMyNoticesRow, error)
	ListNotices(ctx context.Context, arg ListNoticesParams) ([]TNotice, error)
	ListPendingQueueTasks(ctx context.Context, types []string) ([]SysTask, error)
	ListRoles(ctx context.Context, arg ListRolesParams) ([]TRole, error)
	ListTaskStatusCounts(ctx context.Context) ([]ListTaskStatusCountsRow, error)
	ListTaskTypes(ctx context.Context) ([]string, error)
	ListTasks(ctx context.Context, arg ListTasksParams) ([]SysTask, error)
	ListTenants(ctx context.Context, arg ListTenantsParams) ([]TTenant, error)
	// user_role.sql
	// SQL for the user<->role association (t_user_role).
	// Ordering is fixed (user_id DESC) rather than interpolated, eliminating any
	// ORDER BY injection surface. This matches the sole caller's default ordering.
	ListUserRoles(ctx context.Context, arg ListUserRolesParams) ([]TUserRole, error)
	ListUsers(ctx context.Context, arg ListUsersParams) ([]TUser, error)
	MarkAllUserNoticesRead(ctx context.Context, userID string) error
	MarkUserNoticeRead(ctx context.Context, arg MarkUserNoticeReadParams) error
	SoftDeleteConfig(ctx context.Context, arg SoftDeleteConfigParams) error
	SoftDeleteDept(ctx context.Context, arg SoftDeleteDeptParams) error
	// Soft-deletes a department and all of its descendants. A node is a descendant
	// when its comma-wrapped tree_path contains ",<id>,". Matches the previous GORM
	// expression built from DBCompat.TreePathLike.
	SoftDeleteDeptByTreePath(ctx context.Context, arg SoftDeleteDeptByTreePathParams) error
	SoftDeleteDict(ctx context.Context, arg SoftDeleteDictParams) error
	SoftDeleteDictItem(ctx context.Context, arg SoftDeleteDictItemParams) error
	SoftDeleteDictItemsByDictCodes(ctx context.Context, arg SoftDeleteDictItemsByDictCodesParams) error
	SoftDeleteDictItemsByIDs(ctx context.Context, arg SoftDeleteDictItemsByIDsParams) error
	SoftDeleteDictsByIDs(ctx context.Context, arg SoftDeleteDictsByIDsParams) error
	SoftDeleteNoticesByIDs(ctx context.Context, arg SoftDeleteNoticesByIDsParams) error
	SoftDeleteQueueTask(ctx context.Context, id int64) error
	SoftDeleteRole(ctx context.Context, id string) error
	SoftDeleteTenant(ctx context.Context, id string) error
	SoftDeleteUser(ctx context.Context, id string) error
	UpdateConfig(ctx context.Context, arg UpdateConfigParams) error
	// Mirrors the previous Select-scoped GORM update
	// (name, code, parent_id, tree_path, sort, status, update_by).
	UpdateDept(ctx context.Context, arg UpdateDeptParams) error
	UpdateDict(ctx context.Context, arg UpdateDictParams) error
	UpdateDictItem(ctx context.Context, arg UpdateDictItemParams) error
	// Cascade a dictionary code rename onto its items. Called by DictRepository when a
	// dictionary's code changes.
	UpdateDictItemsDictCode(ctx context.Context, arg UpdateDictItemsDictCodeParams) error
	UpdateDownloadTask(ctx context.Context, arg UpdateDownloadTaskParams) error
	// Updates progress and, only when a non-empty value is supplied, the identity
	// fields (task_id, hash, name, save_path). NULLIF(arg,'') + COALESCE keeps the
	// existing value for empty arguments, mirroring the previous conditional map.
	UpdateDownloadTaskFromDownloader(ctx context.Context, arg UpdateDownloadTaskFromDownloaderParams) error
	UpdateDownloadTaskStatus(ctx context.Context, arg UpdateDownloadTaskStatusParams) error
	UpdateMemberLoginInfo(ctx context.Context, arg UpdateMemberLoginInfoParams) error
	UpdateMemberPassword(ctx context.Context, arg UpdateMemberPasswordParams) error
	UpdateMemberProfile(ctx context.Context, arg UpdateMemberProfileParams) error
	UpdateMemberStatus(ctx context.Context, arg UpdateMemberStatusParams) error
	UpdateMenu(ctx context.Context, arg UpdateMenuParams) error
	UpdateMenuTreePath(ctx context.Context, arg UpdateMenuTreePathParams) error
	UpdateMenuVisible(ctx context.Context, arg UpdateMenuVisibleParams) error
	UpdateNotice(ctx context.Context, arg UpdateNoticeParams) error
	UpdateNoticeStatus(ctx context.Context, arg UpdateNoticeStatusParams) error
	UpdateQueueTask(ctx context.Context, arg UpdateQueueTaskParams) (SysTask, error)
	// Mirrors the previous Select-scoped GORM update
	// (name, code, sort, status, data_scope, update_by).
	UpdateRole(ctx context.Context, arg UpdateRoleParams) error
	UpdateRoleStatus(ctx context.Context, arg UpdateRoleStatusParams) error
	UpdateTenant(ctx context.Context, arg UpdateTenantParams) error
	UpdateUser(ctx context.Context, arg UpdateUserParams) error
	UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error
	UpdateUserProfile(ctx context.Context, arg UpdateUserProfileParams) error
	UpdateUserStatus(ctx context.Context, arg UpdateUserStatusParams) error
}

var _ Querier = (*Queries)(nil)
