// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: role.sql

package sqlc

import (
	"context"
)

const countRoles = `-- name: CountRoles :one
SELECT COUNT(*) FROM t_role
WHERE is_deleted = 0
  AND ($1::text[]  IS NULL OR id = ANY($1::text[]))
  AND ($2::text   IS NULL OR name = $2)
  AND ($3::text   IS NULL OR code = $3)
  AND ($4::text IS NULL OR id IN (
        SELECT role_id FROM t_user_role WHERE user_id = $4))
  AND ($5::text IS NULL OR (
        name LIKE $5 OR code LIKE $5))
  AND ($6::int  IS NULL OR status = $6)
`

type CountRolesParams struct {
	Ids        []string
	Name       *string
	Code       *string
	UserID     *string
	QueryValue *string
	Status     *int32
}

func (q *Queries) CountRoles(ctx context.Context, arg CountRolesParams) (int64, error) {
	row := q.db.QueryRow(ctx, countRoles,
		arg.Ids,
		arg.Name,
		arg.Code,
		arg.UserID,
		arg.QueryValue,
		arg.Status,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createRole = `-- name: CreateRole :exec
INSERT INTO t_role (
    id, name, code, sort, status, data_scope, create_by, update_by, is_deleted,
    create_time, update_time
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9,
    NOW(), NOW()
)
`

type CreateRoleParams struct {
	ID        string
	Name      string
	Code      string
	Sort      int32
	Status    int32
	DataScope int32
	CreateBy  string
	UpdateBy  string
	IsDeleted int32
}

func (q *Queries) CreateRole(ctx context.Context, arg CreateRoleParams) error {
	_, err := q.db.Exec(ctx, createRole,
		arg.ID,
		arg.Name,
		arg.Code,
		arg.Sort,
		arg.Status,
		arg.DataScope,
		arg.CreateBy,
		arg.UpdateBy,
		arg.IsDeleted,
	)
	return err
}

const getRole = `-- name: GetRole :one

SELECT id, name, code, sort, status, data_scope, create_by, create_time, update_by, update_time, is_deleted FROM t_role
WHERE id = $1 AND is_deleted = 0
`

// role.sql
// All SQL for the role domain (t_role). Generated into db/sqlc by `make sqlc`.
// Dynamic filters use sqlc.narg (nullable args): a NULL argument disables that
// predicate, so a single prepared statement serves every filter combination
// while remaining fully parameterized (no SQL injection surface). Ordering is a
// fixed `id DESC` — the previous GORM default — rather than an interpolated
// column, eliminating any ORDER BY injection surface.
func (q *Queries) GetRole(ctx context.Context, id string) (TRole, error) {
	row := q.db.QueryRow(ctx, getRole, id)
	var i TRole
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Code,
		&i.Sort,
		&i.Status,
		&i.DataScope,
		&i.CreateBy,
		&i.CreateTime,
		&i.UpdateBy,
		&i.UpdateTime,
		&i.IsDeleted,
	)
	return i, err
}

const getRoleByCode = `-- name: GetRoleByCode :one
SELECT id, name, code, sort, status, data_scope, create_by, create_time, update_by, update_time, is_deleted FROM t_role
WHERE code = $1 AND is_deleted = 0
LIMIT 1
`

func (q *Queries) GetRoleByCode(ctx context.Context, code string) (TRole, error) {
	row := q.db.QueryRow(ctx, getRoleByCode, code)
	var i TRole
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Code,
		&i.Sort,
		&i.Status,
		&i.DataScope,
		&i.CreateBy,
		&i.CreateTime,
		&i.UpdateBy,
		&i.UpdateTime,
		&i.IsDeleted,
	)
	return i, err
}

const listRoles = `-- name: ListRoles :many
SELECT id, name, code, sort, status, data_scope, create_by, create_time, update_by, update_time, is_deleted FROM t_role
WHERE is_deleted = 0
  AND ($1::text[]  IS NULL OR id = ANY($1::text[]))
  AND ($2::text   IS NULL OR name = $2)
  AND ($3::text   IS NULL OR code = $3)
  AND ($4::text IS NULL OR id IN (
        SELECT role_id FROM t_user_role WHERE user_id = $4))
  AND ($5::text IS NULL OR (
        name LIKE $5 OR code LIKE $5))
  AND ($6::int  IS NULL OR status = $6)
ORDER BY id DESC
LIMIT  $8
OFFSET $7
`

type ListRolesParams struct {
	Ids        []string
	Name       *string
	Code       *string
	UserID     *string
	QueryValue *string
	Status     *int32
	Offset     *int32
	Limit      *int32
}

func (q *Queries) ListRoles(ctx context.Context, arg ListRolesParams) ([]TRole, error) {
	rows, err := q.db.Query(ctx, listRoles,
		arg.Ids,
		arg.Name,
		arg.Code,
		arg.UserID,
		arg.QueryValue,
		arg.Status,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TRole{}
	for rows.Next() {
		var i TRole
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Code,
			&i.Sort,
			&i.Status,
			&i.DataScope,
			&i.CreateBy,
			&i.CreateTime,
			&i.UpdateBy,
			&i.UpdateTime,
			&i.IsDeleted,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteRole = `-- name: SoftDeleteRole :exec
UPDATE t_role SET is_deleted = 1, update_time = NOW() WHERE id = $1
`

func (q *Queries) SoftDeleteRole(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, softDeleteRole, id)
	return err
}

const updateRole = `-- name: UpdateRole :exec
UPDATE t_role SET
    name        = $2,
    code        = $3,
    sort        = $4,
    status      = $5,
    data_scope  = $6,
    update_by   = $7,
    update_time = NOW()
WHERE id = $1
`

type UpdateRoleParams struct {
	ID        string
	Name      string
	Code      string
	Sort      int32
	Status    int32
	DataScope int32
	UpdateBy  string
}

// Mirrors the previous Select-scoped GORM update
// (name, code, sort, status, data_scope, update_by).
func (q *Queries) UpdateRole(ctx context.Context, arg UpdateRoleParams) error {
	_, err := q.db.Exec(ctx, updateRole,
		arg.ID,
		arg.Name,
		arg.Code,
		arg.Sort,
		arg.Status,
		arg.DataScope,
		arg.UpdateBy,
	)
	return err
}

const updateRoleStatus = `-- name: UpdateRoleStatus :exec
UPDATE t_role SET status = $2, update_time = NOW() WHERE id = $1
`

type UpdateRoleStatusParams struct {
	ID     string
	Status int32
}

func (q *Queries) UpdateRoleStatus(ctx context.Context, arg UpdateRoleStatusParams) error {
	_, err := q.db.Exec(ctx, updateRoleStatus, arg.ID, arg.Status)
	return err
}
