// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: role_menu.sql

package sqlc

import (
	"context"
)

const batchCreateRoleMenus = `-- name: BatchCreateRoleMenus :exec
INSERT INTO t_role_menu (role_id, menu_id)
SELECT unnest($1::text[]), unnest($2::text[])
ON CONFLICT (role_id, menu_id) DO NOTHING
`

type BatchCreateRoleMenusParams struct {
	RoleIds []string
	MenuIds []string
}

// Single-statement bulk insert via array unnest, keeping the whole batch atomic.
func (q *Queries) BatchCreateRoleMenus(ctx context.Context, arg BatchCreateRoleMenusParams) error {
	_, err := q.db.Exec(ctx, batchCreateRoleMenus, arg.RoleIds, arg.MenuIds)
	return err
}

const deleteRoleMenusByMenuID = `-- name: DeleteRoleMenusByMenuID :exec
DELETE FROM t_role_menu WHERE menu_id = $1
`

func (q *Queries) DeleteRoleMenusByMenuID(ctx context.Context, menuID string) error {
	_, err := q.db.Exec(ctx, deleteRoleMenusByMenuID, menuID)
	return err
}

const deleteRoleMenusByRoleID = `-- name: DeleteRoleMenusByRoleID :exec
DELETE FROM t_role_menu WHERE role_id = $1
`

func (q *Queries) DeleteRoleMenusByRoleID(ctx context.Context, roleID string) error {
	_, err := q.db.Exec(ctx, deleteRoleMenusByRoleID, roleID)
	return err
}

const getMenuIDsByRoleID = `-- name: GetMenuIDsByRoleID :many

SELECT menu_id FROM t_role_menu WHERE role_id = $1
`

// role_menu.sql
// SQL for the role<->menu association (t_role_menu), scoped to the Role module's
// access paths. The Menu module still reaches t_role_menu through GORM during the
// transition, so its menu-side delete is intentionally NOT defined here.
func (q *Queries) GetMenuIDsByRoleID(ctx context.Context, roleID string) ([]string, error) {
	rows, err := q.db.Query(ctx, getMenuIDsByRoleID, roleID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var menu_id string
		if err := rows.Scan(&menu_id); err != nil {
			return nil, err
		}
		items = append(items, menu_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
