// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: user.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countUsers = `-- name: CountUsers :one
SELECT COUNT(*) FROM t_user
WHERE is_deleted = 0
  AND ($1::text  IS NULL OR username = $1)
  AND ($2::text  IS NULL OR nickname = $2)
  AND ($3::int     IS NULL OR status   = $3)
  AND ($4::text   IS NULL OR dept_id  = $4)
  AND ($5::text  IS NULL OR (
        username ILIKE $5 OR
        nickname ILIKE $5 OR
        mobile   ILIKE $5 OR
        email    ILIKE $5))
  AND ($6::timestamptz IS NULL OR create_time >= $6)
  AND ($7::timestamptz   IS NULL OR create_time <= $7)
  AND ($8::text[] IS NULL OR id IN (
        SELECT user_id FROM t_user_role WHERE role_id = ANY($8::text[])))
`

type CountUsersParams struct {
	Username   *string
	Nickname   *string
	Status     *int32
	DeptID     *string
	Keywords   *string
	CreateFrom pgtype.Timestamptz
	CreateTo   pgtype.Timestamptz
	RoleIds    []string
}

func (q *Queries) CountUsers(ctx context.Context, arg CountUsersParams) (int64, error) {
	row := q.db.QueryRow(ctx, countUsers,
		arg.Username,
		arg.Nickname,
		arg.Status,
		arg.DeptID,
		arg.Keywords,
		arg.CreateFrom,
		arg.CreateTo,
		arg.RoleIds,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createUser = `-- name: CreateUser :exec
INSERT INTO t_user (
    id, username, nickname, gender, password, dept_id, avatar,
    mobile, status, email, create_by, update_by, is_deleted, openid,
    create_time, update_time
) VALUES (
    $1, $2, $3, $4, $5, $6, $7,
    $8, $9, $10, $11, $12, $13, $14,
    NOW(), NOW()
)
`

type CreateUserParams struct {
	ID        string
	Username  string
	Nickname  string
	Gender    int32
	Password  string
	DeptID    string
	Avatar    string
	Mobile    string
	Status    int32
	Email     string
	CreateBy  string
	UpdateBy  string
	IsDeleted int32
	Openid    string
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) error {
	_, err := q.db.Exec(ctx, createUser,
		arg.ID,
		arg.Username,
		arg.Nickname,
		arg.Gender,
		arg.Password,
		arg.DeptID,
		arg.Avatar,
		arg.Mobile,
		arg.Status,
		arg.Email,
		arg.CreateBy,
		arg.UpdateBy,
		arg.IsDeleted,
		arg.Openid,
	)
	return err
}

const getUser = `-- name: GetUser :one

SELECT id, username, nickname, gender, password, dept_id, avatar, mobile, status, email, create_time, create_by, update_time, update_by, is_deleted, openid FROM t_user
WHERE id = $1 AND is_deleted = 0
`

// user.sql
// All SQL for the user domain. Generated into db/sqlc by `make sqlc`.
// Dynamic filters use sqlc.narg (nullable args): a NULL argument disables that
// predicate, so a single prepared statement serves every filter combination
// while remaining fully parameterized (no SQL injection surface).
func (q *Queries) GetUser(ctx context.Context, id string) (TUser, error) {
	row := q.db.QueryRow(ctx, getUser, id)
	var i TUser
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Nickname,
		&i.Gender,
		&i.Password,
		&i.DeptID,
		&i.Avatar,
		&i.Mobile,
		&i.Status,
		&i.Email,
		&i.CreateTime,
		&i.CreateBy,
		&i.UpdateTime,
		&i.UpdateBy,
		&i.IsDeleted,
		&i.Openid,
	)
	return i, err
}

const getUserByUsername = `-- name: GetUserByUsername :one
SELECT id, username, nickname, gender, password, dept_id, avatar, mobile, status, email, create_time, create_by, update_time, update_by, is_deleted, openid FROM t_user
WHERE username = $1 AND is_deleted = 0
LIMIT 1
`

func (q *Queries) GetUserByUsername(ctx context.Context, username string) (TUser, error) {
	row := q.db.QueryRow(ctx, getUserByUsername, username)
	var i TUser
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Nickname,
		&i.Gender,
		&i.Password,
		&i.DeptID,
		&i.Avatar,
		&i.Mobile,
		&i.Status,
		&i.Email,
		&i.CreateTime,
		&i.CreateBy,
		&i.UpdateTime,
		&i.UpdateBy,
		&i.IsDeleted,
		&i.Openid,
	)
	return i, err
}

const listUsers = `-- name: ListUsers :many
SELECT id, username, nickname, gender, password, dept_id, avatar, mobile, status, email, create_time, create_by, update_time, update_by, is_deleted, openid FROM t_user
WHERE is_deleted = 0
  AND ($1::text  IS NULL OR username = $1)
  AND ($2::text  IS NULL OR nickname = $2)
  AND ($3::int     IS NULL OR status   = $3)
  AND ($4::text   IS NULL OR dept_id  = $4)
  AND ($5::text  IS NULL OR (
        username ILIKE $5 OR
        nickname ILIKE $5 OR
        mobile   ILIKE $5 OR
        email    ILIKE $5))
  AND ($6::timestamptz IS NULL OR create_time >= $6)
  AND ($7::timestamptz   IS NULL OR create_time <= $7)
  AND ($8::text[] IS NULL OR id IN (
        SELECT user_id FROM t_user_role WHERE role_id = ANY($8::text[])))
ORDER BY create_time DESC
LIMIT  $10
OFFSET $9
`

type ListUsersParams struct {
	Username   *string
	Nickname   *string
	Status     *int32
	DeptID     *string
	Keywords   *string
	CreateFrom pgtype.Timestamptz
	CreateTo   pgtype.Timestamptz
	RoleIds    []string
	Offset     *int32
	Limit      *int32
}

func (q *Queries) ListUsers(ctx context.Context, arg ListUsersParams) ([]TUser, error) {
	rows, err := q.db.Query(ctx, listUsers,
		arg.Username,
		arg.Nickname,
		arg.Status,
		arg.DeptID,
		arg.Keywords,
		arg.CreateFrom,
		arg.CreateTo,
		arg.RoleIds,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TUser{}
	for rows.Next() {
		var i TUser
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.Nickname,
			&i.Gender,
			&i.Password,
			&i.DeptID,
			&i.Avatar,
			&i.Mobile,
			&i.Status,
			&i.Email,
			&i.CreateTime,
			&i.CreateBy,
			&i.UpdateTime,
			&i.UpdateBy,
			&i.IsDeleted,
			&i.Openid,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteUser = `-- name: SoftDeleteUser :exec
UPDATE t_user SET is_deleted = 1, update_time = NOW() WHERE id = $1
`

func (q *Queries) SoftDeleteUser(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, softDeleteUser, id)
	return err
}

const updateUser = `-- name: UpdateUser :exec
UPDATE t_user SET
    username    = $2,
    nickname    = $3,
    gender      = $4,
    dept_id     = $5,
    avatar      = $6,
    mobile      = $7,
    status      = $8,
    email       = $9,
    update_by   = $10,
    update_time = NOW()
WHERE id = $1
`

type UpdateUserParams struct {
	ID       string
	Username string
	Nickname string
	Gender   int32
	DeptID   string
	Avatar   string
	Mobile   string
	Status   int32
	Email    string
	UpdateBy string
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) error {
	_, err := q.db.Exec(ctx, updateUser,
		arg.ID,
		arg.Username,
		arg.Nickname,
		arg.Gender,
		arg.DeptID,
		arg.Avatar,
		arg.Mobile,
		arg.Status,
		arg.Email,
		arg.UpdateBy,
	)
	return err
}

const updateUserPassword = `-- name: UpdateUserPassword :exec
UPDATE t_user SET password = $2, update_time = NOW() WHERE id = $1
`

type UpdateUserPasswordParams struct {
	ID       string
	Password string
}

func (q *Queries) UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error {
	_, err := q.db.Exec(ctx, updateUserPassword, arg.ID, arg.Password)
	return err
}

const updateUserProfile = `-- name: UpdateUserProfile :exec
UPDATE t_user SET
    nickname    = COALESCE($1, nickname),
    gender      = COALESCE($2,   gender),
    avatar      = COALESCE($3,   avatar),
    mobile      = COALESCE($4,   mobile),
    email       = COALESCE($5,    email),
    update_time = NOW()
WHERE id = $6
`

type UpdateUserProfileParams struct {
	Nickname *string
	Gender   *int32
	Avatar   *string
	Mobile   *string
	Email    *string
	ID       string
}

func (q *Queries) UpdateUserProfile(ctx context.Context, arg UpdateUserProfileParams) error {
	_, err := q.db.Exec(ctx, updateUserProfile,
		arg.Nickname,
		arg.Gender,
		arg.Avatar,
		arg.Mobile,
		arg.Email,
		arg.ID,
	)
	return err
}

const updateUserStatus = `-- name: UpdateUserStatus :exec
UPDATE t_user SET status = $2, update_time = NOW() WHERE id = $1
`

type UpdateUserStatusParams struct {
	ID     string
	Status int32
}

func (q *Queries) UpdateUserStatus(ctx context.Context, arg UpdateUserStatusParams) error {
	_, err := q.db.Exec(ctx, updateUserStatus, arg.ID, arg.Status)
	return err
}
