// Code generated by tools/gen-store. DO NOT EDIT.

package store

import "github.com/jackc/pgx/v5/pgtype"

type BatchCreateRoleMenusParams struct {
	RoleIds []string
	MenuIds []string
}

type BatchCreateUserNoticesParams struct {
	Ids       []string
	NoticeIds []string
	UserIds   []string
}

type BatchCreateUserRolesParams struct {
	UserIds []string
	RoleIds []string
}

type CountConfigsByKeyParams struct {
	ConfigKey string
	ExcludeID *string
}

type CountDictItemsParams struct {
	DictCode *string
	Keywords *string
}

type CountDownloadTasksParams struct {
	Status     *string
	Downloader *string
	Keywords   *string
	CreateFrom pgtype.Timestamptz
	CreateTo   pgtype.Timestamptz
}

type CountLogsParams struct {
	Module     *string
	Keywords   *string
	CreateFrom pgtype.Timestamptz
	CreateTo   pgtype.Timestamptz
}

type CountMembersByUsernameParams struct {
	TenantID string
	Username string
}

type CountMembersParams struct {
	TenantID *string
	Keywords *string
	Status   *int32
}

type CountMenusParams struct {
	Ids            []string
	Name           *string
	ParentID       *string
	PrefixTreePath *string
	Type           *int32
	Visible        *int32
	Keywords       *string
}

type CountMyNoticesParams struct {
	UserID string
	Title  *string
	Type   *int32
}

type CountNoticesParams struct {
	Title         *string
	Type          *int32
	PublishStatus *int32
}

type CountRolesParams struct {
	Ids        []string
	Name       *string
	Code       *string
	UserID     *string
	QueryValue *string
	Status     *int32
}

type CountTasksParams struct {
	Type          *string
	Status        *string
	CorrelationID *string
	Keywords      *string
	CreateFrom    pgtype.Timestamptz
	CreateTo      pgtype.Timestamptz
}

type CountTenantsParams struct {
	Keywords *string
	Status   *int32
}

type CountUserRolesParams struct {
	UserID  *string
	UserIds []string
}

type CountUsersParams struct {
	Username   *string
	Nickname   *string
	Status     *int32
	DeptID     *string
	Keywords   *string
	CreateFrom pgtype.Timestamptz
	CreateTo   pgtype.Timestamptz
	RoleIds    []string
}

type CreateConfigParams struct {
	ID          string
	ConfigName  string
	ConfigKey   string
	ConfigValue string
	Remark      string
	CreateBy    string
	UpdateBy    string
	IsDeleted   int32
}

type CreateDeptParams struct {
	ID        string
	Name      string
	Code      string
	ParentID  string
	TreePath  string
	Sort      int32
	Status    int32
	CreateBy  string
	UpdateBy  string
	IsDeleted int32
}

type CreateDictItemParams struct {
	ID        string
	DictCode  string
	Label     string
	Value     string
	TagType   string
	Sort      int32
	Status    int32
	Remark    string
	CreateBy  string
	UpdateBy  string
	IsDeleted int32
}

type CreateDictParams struct {
	ID        string
	DictCode  string
	Name      string
	Status    int32
	Remark    string
	CreateBy  string
	UpdateBy  string
	IsDeleted int32
}

type CreateDownloadTaskParams struct {
	QueueTaskID   int64
	TaskID        string
	Hash          string
	Name          string
	Url           string
	Downloader    string
	Status        string
	Total         int64
	Downloaded    int64
	DownloadSpeed int64
	Uploaded      int64
	UploadSpeed   int64
	SavePath      string
	ErrorMessage  string
	OwnerID       string
}

type CreateLogParams struct {
	ID              string
	Module          string
	RequestMethod   string
	RequestParams   string
	ResponseContent string
	Content         string
	RequestUri      string
	Method          string
	Ip              string
	Province        string
	City            string
	ExecutionTime   int64
	Browser         string
	BrowserVersion  string
	Os              string
	CreateBy        string
}

type CreateMemberParams struct {
	ID        string
	TenantID  string
	Username  string
	Email     string
	Mobile    string
	Password  string
	Nickname  string
	Avatar    string
	Gender    int32
	Status    int32
	IsDeleted int32
}

type CreateMenuParams struct {
	ID         string
	ParentID   string
	TreePath   string
	Name       string
	Type       int32
	RouteName  string
	RoutePath  string
	Component  string
	Perm       string
	AlwaysShow int32
	KeepAlive  int32
	Visible    int32
	Sort       int32
	Icon       string
	Redirect   string
	Params     string
}

type CreateNoticeParams struct {
	ID            string
	Title         string
	Content       string
	Type          int32
	Level         string
	TargetType    int32
	TargetUserIds string
	PublishStatus int32
	CreateBy      string
	IsDeleted     int32
}

type CreateQueueTaskParams struct {
	Type                   string
	Status                 string
	CorrelationID          string
	OwnerID                string
	PrivateState           string
	PublicRetryCount       int32
	PublicExecutedDuration int64
	PublicError            string
	PublicErrorHistory     string
	PublicResumeTime       int64
}

type CreateRoleParams struct {
	ID        string
	Name      string
	Code      string
	Sort      int32
	Status    int32
	DataScope int32
	CreateBy  string
	UpdateBy  string
	IsDeleted int32
}

type CreateTenantParams struct {
	ID        string
	Code      string
	Name      string
	Status    int32
	CreateBy  string
	IsDeleted int32
}

type CreateUserNoticeParams struct {
	ID       string
	NoticeID string
	UserID   string
	IsRead   int32
}

type CreateUserParams struct {
	ID        string
	Username  string
	Nickname  string
	Gender    int32
	Password  string
	DeptID    string
	Avatar    string
	Mobile    string
	Status    int32
	Email     string
	CreateBy  string
	UpdateBy  string
	IsDeleted int32
	Openid    string
}

type CreateUserRoleParams struct {
	UserID string
	RoleID string
}

type GetDeptByCodeParams struct {
	Code      string
	ExcludeID *string
}

type GetDictByCodeParams struct {
	DictCode  string
	ExcludeID *string
}

type GetMemberByIDParams struct {
	TenantID string
	ID       string
}

type GetMemberByUsernameParams struct {
	TenantID string
	Username string
}

type ListActiveDownloadTasksRow struct {
	ID          int64
	QueueTaskID int64
	TaskID      string
	Hash        string
	Downloader  string
}

type ListConfigsParams struct {
	Keywords *string
	Offset   *int32
	Limit    *int32
}

type ListDeptsParams struct {
	Keywords *string
	Status   *int32
}

type ListDictItemsParams struct {
	DictCode *string
	Keywords *string
	Offset   *int32
	Limit    *int32
}

type ListDictsParams struct {
	Keywords *string
	Offset   *int32
	Limit    *int32
}

type ListDownloadStatusCountsRow struct {
	Status string
	Count  int64
}

type ListDownloadTasksParams struct {
	Status     *string
	Downloader *string
	Keywords   *string
	CreateFrom pgtype.Timestamptz
	CreateTo   pgtype.Timestamptz
	Offset     *int32
	Limit      *int32
}

type ListLogsParams struct {
	Module     *string
	Keywords   *string
	CreateFrom pgtype.Timestamptz
	CreateTo   pgtype.Timestamptz
	Offset     *int32
	Limit      *int32
}

type ListMembersParams struct {
	TenantID *string
	Keywords *string
	Status   *int32
	Offset   *int32
	Limit    *int32
}

type ListMenusParams struct {
	Ids            []string
	Name           *string
	ParentID       *string
	PrefixTreePath *string
	Type           *int32
	Visible        *int32
	Keywords       *string
	OrderBy        int32
	Offset         *int32
	Limit          *int32
}

type ListMyNoticesParams struct {
	UserID string
	Title  *string
	Type   *int32
	Offset *int32
	Limit  *int32
}

type ListMyNoticesRow struct {
	ID          string
	NoticeID    string
	Title       *string
	Type        *int32
	Level       *string
	PublishTime pgtype.Timestamptz
	IsRead      int32
}

type ListNoticesParams struct {
	Title         *string
	Type          *int32
	PublishStatus *int32
	Offset        *int32
	Limit         *int32
}

type ListRolesParams struct {
	Ids        []string
	Name       *string
	Code       *string
	UserID     *string
	QueryValue *string
	Status     *int32
	Offset     *int32
	Limit      *int32
}

type ListTaskStatusCountsRow struct {
	Status string
	Count  int64
}

type ListTasksParams struct {
	Type          *string
	Status        *string
	CorrelationID *string
	Keywords      *string
	CreateFrom    pgtype.Timestamptz
	CreateTo      pgtype.Timestamptz
	Offset        *int32
	Limit         *int32
}

type ListTenantsParams struct {
	Keywords *string
	Status   *int32
	Offset   *int32
	Limit    *int32
}

type ListUserRolesParams struct {
	UserID  *string
	UserIds []string
	Offset  *int32
	Limit   *int32
}

type ListUsersParams struct {
	Username   *string
	Nickname   *string
	Status     *int32
	DeptID     *string
	Keywords   *string
	CreateFrom pgtype.Timestamptz
	CreateTo   pgtype.Timestamptz
	RoleIds    []string
	Offset     *int32
	Limit      *int32
}

type MarkUserNoticeReadParams struct {
	NoticeID string
	UserID   string
}

type SoftDeleteConfigParams struct {
	ID       string
	UpdateBy string
}

type SoftDeleteDeptByTreePathParams struct {
	UpdateBy     string
	ID           string
	TreePathLike string
}

type SoftDeleteDeptParams struct {
	ID       string
	UpdateBy string
}

type SoftDeleteDictItemParams struct {
	ID       string
	UpdateBy string
}

type SoftDeleteDictItemsByDictCodesParams struct {
	UpdateBy  string
	DictCodes []string
}

type SoftDeleteDictItemsByIDsParams struct {
	UpdateBy string
	Ids      []string
}

type SoftDeleteDictParams struct {
	ID       string
	UpdateBy string
}

type SoftDeleteDictsByIDsParams struct {
	UpdateBy string
	Ids      []string
}

type SoftDeleteNoticesByIDsParams struct {
	UpdateBy string
	Ids      []string
}

type SysDownloadTask struct {
	ID            int64
	QueueTaskID   int64
	TaskID        string
	Hash          string
	Name          string
	Url           string
	Downloader    string
	Status        string
	Total         int64
	Downloaded    int64
	DownloadSpeed int64
	Uploaded      int64
	UploadSpeed   int64
	SavePath      string
	ErrorMessage  string
	OwnerID       string
	CreatedAt     pgtype.Timestamptz
	UpdatedAt     pgtype.Timestamptz
	DeletedAt     pgtype.Timestamptz
}

type SysLog struct {
	ID              string
	Module          string
	RequestMethod   string
	RequestParams   string
	ResponseContent string
	Content         string
	RequestUri      string
	Method          string
	Ip              string
	Province        string
	City            string
	ExecutionTime   int64
	Browser         string
	BrowserVersion  string
	Os              string
	CreateBy        string
	CreateTime      pgtype.Timestamptz
}

type SysTask struct {
	ID                     int64
	Type                   string
	Status                 string
	CorrelationID          string
	OwnerID                string
	PrivateState           string
	PublicRetryCount       int32
	PublicExecutedDuration int64
	PublicError            string
	PublicErrorHistory     string
	PublicResumeTime       int64
	CreatedAt              pgtype.Timestamptz
	UpdatedAt              pgtype.Timestamptz
	DeletedAt              pgtype.Timestamptz
}

type TConfig struct {
	ID          string
	ConfigName  string
	ConfigKey   string
	ConfigValue string
	Remark      string
	CreateTime  pgtype.Timestamptz
	CreateBy    string
	UpdateTime  pgtype.Timestamptz
	UpdateBy    string
	IsDeleted   int32
}

type TDept struct {
	ID         string
	Name       string
	Code       string
	ParentID   string
	TreePath   string
	Sort       int32
	Status     int32
	CreateBy   string
	CreateTime pgtype.Timestamptz
	UpdateBy   string
	UpdateTime pgtype.Timestamptz
	IsDeleted  int32
}

type TDict struct {
	ID         string
	DictCode   string
	Name       string
	Status     int32
	Remark     string
	CreateBy   string
	CreateTime pgtype.Timestamptz
	UpdateBy   string
	UpdateTime pgtype.Timestamptz
	IsDeleted  int32
}

type TDictItem struct {
	ID         string
	DictCode   string
	Label      string
	Value      string
	TagType    string
	Sort       int32
	Status     int32
	Remark     string
	CreateBy   string
	CreateTime pgtype.Timestamptz
	UpdateBy   string
	UpdateTime pgtype.Timestamptz
	IsDeleted  int32
}

type TMember struct {
	ID            string
	TenantID      string
	Username      string
	Email         string
	Mobile        string
	Password      string
	Nickname      string
	Avatar        string
	Gender        int32
	Status        int32
	LastLoginTime pgtype.Timestamptz
	LastLoginIp   string
	CreateTime    pgtype.Timestamptz
	UpdateTime    pgtype.Timestamptz
	IsDeleted     int32
}

type TMenu struct {
	ID         string
	ParentID   string
	TreePath   string
	Name       string
	Type       int32
	RouteName  string
	RoutePath  string
	Component  string
	Perm       string
	AlwaysShow int32
	KeepAlive  int32
	Visible    int32
	Sort       int32
	Icon       string
	Redirect   string
	Params     string
	CreateTime pgtype.Timestamptz
	UpdateTime pgtype.Timestamptz
}

type TNotice struct {
	ID            string
	Title         string
	Content       string
	Type          int32
	Level         string
	TargetType    int32
	TargetUserIds string
	PublisherID   string
	PublishStatus int32
	PublishTime   pgtype.Timestamptz
	RevokeTime    pgtype.Timestamptz
	CreateBy      string
	CreateTime    pgtype.Timestamptz
	UpdateBy      string
	UpdateTime    pgtype.Timestamptz
	IsDeleted     int32
}

type TRole struct {
	ID         string
	Name       string
	Code       string
	Sort       int32
	Status     int32
	DataScope  int32
	CreateBy   string
	CreateTime pgtype.Timestamptz
	UpdateBy   string
	UpdateTime pgtype.Timestamptz
	IsDeleted  int32
}

type TRoleMenu struct {
	RoleID string
	MenuID string
}

type TTenant struct {
	ID         string
	Code       string
	Name       string
	Status     int32
	CreateTime pgtype.Timestamptz
	CreateBy   string
	UpdateTime pgtype.Timestamptz
	UpdateBy   string
	IsDeleted  int32
}

type TUser struct {
	ID         string
	Username   string
	Nickname   string
	Gender     int32
	Password   string
	DeptID     string
	Avatar     string
	Mobile     string
	Status     int32
	Email      string
	CreateTime pgtype.Timestamptz
	CreateBy   string
	UpdateTime pgtype.Timestamptz
	UpdateBy   string
	IsDeleted  int32
	Openid     string
}

type TUserNotice struct {
	ID         string
	NoticeID   string
	UserID     string
	IsRead     int32
	ReadTime   pgtype.Timestamptz
	CreateTime pgtype.Timestamptz
	UpdateTime pgtype.Timestamptz
	IsDeleted  int32
}

type TUserRole struct {
	UserID string
	RoleID string
}

type UpdateConfigParams struct {
	ID          string
	ConfigName  string
	ConfigKey   string
	ConfigValue string
	Remark      string
	UpdateBy    string
}

type UpdateDeptParams struct {
	ID       string
	Name     string
	Code     string
	ParentID string
	TreePath string
	Sort     int32
	Status   int32
	UpdateBy string
}

type UpdateDictItemParams struct {
	ID       string
	DictCode string
	Label    string
	Value    string
	TagType  string
	Sort     int32
	Status   int32
	Remark   string
	UpdateBy string
}

type UpdateDictItemsDictCodeParams struct {
	NewCode string
	OldCode string
}

type UpdateDictParams struct {
	ID       string
	DictCode string
	Name     string
	Status   int32
	Remark   string
	UpdateBy string
}

type UpdateDownloadTaskFromDownloaderParams struct {
	Status        string
	Downloaded    int64
	Total         int64
	DownloadSpeed int64
	Uploaded      int64
	UploadSpeed   int64
	ErrorMessage  string
	TaskID        interface{}
	Hash          interface{}
	Name          interface{}
	SavePath      interface{}
	ID            int64
}

type UpdateDownloadTaskParams struct {
	ID            int64
	QueueTaskID   int64
	TaskID        string
	Hash          string
	Name          string
	Url           string
	Downloader    string
	Status        string
	Total         int64
	Downloaded    int64
	DownloadSpeed int64
	Uploaded      int64
	UploadSpeed   int64
	SavePath      string
	ErrorMessage  string
	OwnerID       string
}

type UpdateDownloadTaskStatusParams struct {
	ID            int64
	Status        string
	Downloaded    int64
	Total         int64
	DownloadSpeed int64
	Uploaded      int64
	UploadSpeed   int64
	ErrorMessage  string
}

type UpdateMemberLoginInfoParams struct {
	TenantID    string
	ID          string
	LastLoginIp string
}

type UpdateMemberPasswordParams struct {
	TenantID string
	ID       string
	Password string
}

type UpdateMemberProfileParams struct {
	Nickname string
	Avatar   string
	Gender   int32
	Mobile   string
	Email    string
	TenantID string
	ID       string
}

type UpdateMemberStatusParams struct {
	TenantID string
	ID       string
	Status   int32
}

type UpdateMenuParams struct {
	ID         string
	ParentID   string
	TreePath   string
	Name       string
	Type       int32
	RouteName  string
	RoutePath  string
	Component  string
	Perm       string
	AlwaysShow int32
	KeepAlive  int32
	Visible    int32
	Sort       int32
	Icon       string
	Redirect   string
	Params     string
}

type UpdateMenuTreePathParams struct {
	ID       string
	TreePath string
}

type UpdateMenuVisibleParams struct {
	ID      string
	Visible int32
}

type UpdateNoticeParams struct {
	ID            string
	Title         string
	Content       string
	Type          int32
	Level         string
	TargetType    int32
	TargetUserIds string
	UpdateBy      string
}

type UpdateNoticeStatusParams struct {
	PublishStatus int32
	PublisherID   string
	PublishTime   pgtype.Timestamptz
	RevokeTime    pgtype.Timestamptz
	ID            string
}

type UpdateQueueTaskParams struct {
	ID                     int64
	Type                   string
	Status                 string
	CorrelationID          string
	OwnerID                string
	PrivateState           string
	PublicRetryCount       int32
	PublicExecutedDuration int64
	PublicError            string
	PublicErrorHistory     string
	PublicResumeTime       int64
}

type UpdateRoleParams struct {
	ID        string
	Name      string
	Code      string
	Sort      int32
	Status    int32
	DataScope int32
	UpdateBy  string
}

type UpdateRoleStatusParams struct {
	ID     string
	Status int32
}

type UpdateTenantParams struct {
	ID       string
	Code     string
	Name     string
	Status   int32
	UpdateBy string
}

type UpdateUserParams struct {
	ID       string
	Username string
	Nickname string
	Gender   int32
	DeptID   string
	Avatar   string
	Mobile   string
	Status   int32
	Email    string
	UpdateBy string
}

type UpdateUserPasswordParams struct {
	ID       string
	Password string
}

type UpdateUserProfileParams struct {
	Nickname *string
	Gender   *int32
	Avatar   *string
	Mobile   *string
	Email    *string
	ID       string
}

type UpdateUserStatusParams struct {
	ID     string
	Status int32
}
