// Code generated by tools/gen-store. DO NOT EDIT.

package store

import "context"

type Store interface {
	BatchCreateRoleMenus(ctx context.Context, arg BatchCreateRoleMenusParams) error
	BatchCreateUserNotices(ctx context.Context, arg BatchCreateUserNoticesParams) error
	BatchCreateUserRoles(ctx context.Context, arg BatchCreateUserRolesParams) error
	BatchDeleteDownloadTasks(ctx context.Context, ids []int64) error
	BatchDeleteLogs(ctx context.Context, ids []string) error
	BatchDeleteTasks(ctx context.Context, ids []int64) error
	CountConfigs(ctx context.Context, keywords *string) (int64, error)
	CountConfigsByKey(ctx context.Context, arg CountConfigsByKeyParams) (int64, error)
	CountDictItems(ctx context.Context, arg CountDictItemsParams) (int64, error)
	CountDicts(ctx context.Context, keywords *string) (int64, error)
	CountDownloadTasks(ctx context.Context, arg CountDownloadTasksParams) (int64, error)
	CountLogs(ctx context.Context, arg CountLogsParams) (int64, error)
	CountMembers(ctx context.Context, arg CountMembersParams) (int64, error)
	CountMembersByUsername(ctx context.Context, arg CountMembersByUsernameParams) (int64, error)
	CountMenus(ctx context.Context, arg CountMenusParams) (int64, error)
	CountMyNotices(ctx context.Context, arg CountMyNoticesParams) (int64, error)
	CountNotices(ctx context.Context, arg CountNoticesParams) (int64, error)
	CountRoles(ctx context.Context, arg CountRolesParams) (int64, error)
	CountTasks(ctx context.Context, arg CountTasksParams) (int64, error)
	CountTenants(ctx context.Context, arg CountTenantsParams) (int64, error)
	CountUserRoles(ctx context.Context, arg CountUserRolesParams) (int64, error)
	CountUsers(ctx context.Context, arg CountUsersParams) (int64, error)
	CreateConfig(ctx context.Context, arg CreateConfigParams) error
	CreateDept(ctx context.Context, arg CreateDeptParams) error
	CreateDict(ctx context.Context, arg CreateDictParams) error
	CreateDictItem(ctx context.Context, arg CreateDictItemParams) error
	CreateDownloadTask(ctx context.Context, arg CreateDownloadTaskParams) (int64, error)
	CreateLog(ctx context.Context, arg CreateLogParams) error
	CreateMember(ctx context.Context, arg CreateMemberParams) error
	CreateMenu(ctx context.Context, arg CreateMenuParams) error
	CreateNotice(ctx context.Context, arg CreateNoticeParams) error
	CreateQueueTask(ctx context.Context, arg CreateQueueTaskParams) (SysTask, error)
	CreateRole(ctx context.Context, arg CreateRoleParams) error
	CreateTenant(ctx context.Context, arg CreateTenantParams) error
	CreateUser(ctx context.Context, arg CreateUserParams) error
	CreateUserNotice(ctx context.Context, arg CreateUserNoticeParams) error
	CreateUserRole(ctx context.Context, arg CreateUserRoleParams) error
	DeleteDownloadTask(ctx context.Context, id int64) error
	DeleteLog(ctx context.Context, id string) error
	DeleteMenu(ctx context.Context, id string) error
	DeleteRoleMenusByMenuID(ctx context.Context, menuID string) error
	DeleteRoleMenusByRoleID(ctx context.Context, roleID string) error
	DeleteTask(ctx context.Context, id int64) error
	DeleteUserNoticesByNoticeID(ctx context.Context, noticeID string) error
	DeleteUserNoticesByNoticeIDs(ctx context.Context, noticeIds []string) error
	DeleteUserRolesByRoleID(ctx context.Context, roleID string) error
	DeleteUserRolesByUserID(ctx context.Context, userID string) error
	GetConfig(ctx context.Context, id string) (TConfig, error)
	GetConfigByKey(ctx context.Context, configKey string) (TConfig, error)
	GetDept(ctx context.Context, id string) (TDept, error)
	GetDeptByCode(ctx context.Context, arg GetDeptByCodeParams) (TDept, error)
	GetDict(ctx context.Context, id string) (TDict, error)
	GetDictByCode(ctx context.Context, arg GetDictByCodeParams) (TDict, error)
	GetDictItem(ctx context.Context, id string) (TDictItem, error)
	GetDownloadTask(ctx context.Context, id int64) (SysDownloadTask, error)
	GetDownloadTaskByQueueTaskID(ctx context.Context, queueTaskID int64) (SysDownloadTask, error)
	GetDownloadTaskByTaskID(ctx context.Context, taskID string) (SysDownloadTask, error)
	GetLog(ctx context.Context, id string) (SysLog, error)
	GetMemberByID(ctx context.Context, arg GetMemberByIDParams) (TMember, error)
	GetMemberByUsername(ctx context.Context, arg GetMemberByUsernameParams) (TMember, error)
	GetMenu(ctx context.Context, id string) (TMenu, error)
	GetMenuIDsByRoleID(ctx context.Context, roleID string) ([]string, error)
	GetNotice(ctx context.Context, id string) (TNotice, error)
	GetQueueTask(ctx context.Context, id int64) (SysTask, error)
	GetRole(ctx context.Context, id string) (TRole, error)
	GetRoleByCode(ctx context.Context, code string) (TRole, error)
	GetRoleIDsByUserID(ctx context.Context, userID string) ([]string, error)
	GetTask(ctx context.Context, id int64) (SysTask, error)
	GetTenant(ctx context.Context, id string) (TTenant, error)
	GetTenantByCode(ctx context.Context, code string) (TTenant, error)
	GetUser(ctx context.Context, id string) (TUser, error)
	GetUserByUsername(ctx context.Context, username string) (TUser, error)
	GetUserIDsByRoleID(ctx context.Context, roleID string) ([]string, error)
	ListActiveDownloadTasks(ctx context.Context) ([]ListActiveDownloadTasksRow, error)
	ListAllConfigs(ctx context.Context) ([]TConfig, error)
	ListButtonPermsByRoleIDs(ctx context.Context, roleIds []string) ([]string, error)
	ListConfigs(ctx context.Context, arg ListConfigsParams) ([]TConfig, error)
	ListDepts(ctx context.Context, arg ListDeptsParams) ([]TDept, error)
	ListDeptsByIDs(ctx context.Context, ids []string) ([]TDept, error)
	ListDictItems(ctx context.Context, arg ListDictItemsParams) ([]TDictItem, error)
	ListDictItemsByDictCode(ctx context.Context, dictCode string) ([]TDictItem, error)
	ListDicts(ctx context.Context, arg ListDictsParams) ([]TDict, error)
	ListDictsByIDs(ctx context.Context, ids []string) ([]TDict, error)
	ListDownloadStatusCounts(ctx context.Context) ([]ListDownloadStatusCountsRow, error)
	ListDownloadTasks(ctx context.Context, arg ListDownloadTasksParams) ([]SysDownloadTask, error)
	ListEnabledDepts(ctx context.Context) ([]TDept, error)
	ListEnabledDicts(ctx context.Context) ([]TDict, error)
	ListLogs(ctx context.Context, arg ListLogsParams) ([]SysLog, error)
	ListMembers(ctx context.Context, arg ListMembersParams) ([]TMember, error)
	ListMenus(ctx context.Context, arg ListMenusParams) ([]TMenu, error)
	ListMenusByRoleIDs(ctx context.Context, roleIds []string) ([]TMenu, error)
	ListMyNotices(ctx context.Context, arg ListMyNoticesParams) ([]ListMyNoticesRow, error)
	ListNotices(ctx context.Context, arg ListNoticesParams) ([]TNotice, error)
	ListPendingQueueTasks(ctx context.Context, types []string) ([]SysTask, error)
	ListRoles(ctx context.Context, arg ListRolesParams) ([]TRole, error)
	ListTaskStatusCounts(ctx context.Context) ([]ListTaskStatusCountsRow, error)
	ListTaskTypes(ctx context.Context) ([]string, error)
	ListTasks(ctx context.Context, arg ListTasksParams) ([]SysTask, error)
	ListTenants(ctx context.Context, arg ListTenantsParams) ([]TTenant, error)
	ListUserRoles(ctx context.Context, arg ListUserRolesParams) ([]TUserRole, error)
	ListUsers(ctx context.Context, arg ListUsersParams) ([]TUser, error)
	MarkAllUserNoticesRead(ctx context.Context, userID string) error
	MarkUserNoticeRead(ctx context.Context, arg MarkUserNoticeReadParams) error
	SoftDeleteConfig(ctx context.Context, arg SoftDeleteConfigParams) error
	SoftDeleteDept(ctx context.Context, arg SoftDeleteDeptParams) error
	SoftDeleteDeptByTreePath(ctx context.Context, arg SoftDeleteDeptByTreePathParams) error
	SoftDeleteDict(ctx context.Context, arg SoftDeleteDictParams) error
	SoftDeleteDictItem(ctx context.Context, arg SoftDeleteDictItemParams) error
	SoftDeleteDictItemsByDictCodes(ctx context.Context, arg SoftDeleteDictItemsByDictCodesParams) error
	SoftDeleteDictItemsByIDs(ctx context.Context, arg SoftDeleteDictItemsByIDsParams) error
	SoftDeleteDictsByIDs(ctx context.Context, arg SoftDeleteDictsByIDsParams) error
	SoftDeleteNoticesByIDs(ctx context.Context, arg SoftDeleteNoticesByIDsParams) error
	SoftDeleteQueueTask(ctx context.Context, id int64) error
	SoftDeleteRole(ctx context.Context, id string) error
	SoftDeleteTenant(ctx context.Context, id string) error
	SoftDeleteUser(ctx context.Context, id string) error
	UpdateConfig(ctx context.Context, arg UpdateConfigParams) error
	UpdateDept(ctx context.Context, arg UpdateDeptParams) error
	UpdateDict(ctx context.Context, arg UpdateDictParams) error
	UpdateDictItem(ctx context.Context, arg UpdateDictItemParams) error
	UpdateDictItemsDictCode(ctx context.Context, arg UpdateDictItemsDictCodeParams) error
	UpdateDownloadTask(ctx context.Context, arg UpdateDownloadTaskParams) error
	UpdateDownloadTaskFromDownloader(ctx context.Context, arg UpdateDownloadTaskFromDownloaderParams) error
	UpdateDownloadTaskStatus(ctx context.Context, arg UpdateDownloadTaskStatusParams) error
	UpdateMemberLoginInfo(ctx context.Context, arg UpdateMemberLoginInfoParams) error
	UpdateMemberPassword(ctx context.Context, arg UpdateMemberPasswordParams) error
	UpdateMemberProfile(ctx context.Context, arg UpdateMemberProfileParams) error
	UpdateMemberStatus(ctx context.Context, arg UpdateMemberStatusParams) error
	UpdateMenu(ctx context.Context, arg UpdateMenuParams) error
	UpdateMenuTreePath(ctx context.Context, arg UpdateMenuTreePathParams) error
	UpdateMenuVisible(ctx context.Context, arg UpdateMenuVisibleParams) error
	UpdateNotice(ctx context.Context, arg UpdateNoticeParams) error
	UpdateNoticeStatus(ctx context.Context, arg UpdateNoticeStatusParams) error
	UpdateQueueTask(ctx context.Context, arg UpdateQueueTaskParams) (SysTask, error)
	UpdateRole(ctx context.Context, arg UpdateRoleParams) error
	UpdateRoleStatus(ctx context.Context, arg UpdateRoleStatusParams) error
	UpdateTenant(ctx context.Context, arg UpdateTenantParams) error
	UpdateUser(ctx context.Context, arg UpdateUserParams) error
	UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error
	UpdateUserProfile(ctx context.Context, arg UpdateUserProfileParams) error
	UpdateUserStatus(ctx context.Context, arg UpdateUserStatusParams) error
}
