/**
 * Generate TypeScript types from the backend OpenAPI (Swagger) contract.
 *
 * Pipeline:
 *   docs/contracts/openapi.yaml (Swagger 2.0 from swag)
 *     → swagger2openapi (convert to OpenAPI 3.0)
 *     → openapi-typescript (emit TS)
 *     → src/types/light-admin/schema.ts
 *
 * Refresh upstream via `cd light-admin-server && make swagger`
 * then copy docs/swagger.yaml into docs/contracts/openapi.yaml.
 */
import { mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import yaml from 'js-yaml';
import openapiTS, { astToString } from 'openapi-typescript';
// @ts-expect-error — no bundled types
import converter from 'swagger2openapi';

const here = dirname(fileURLToPath(import.meta.url));
const projectRoot = resolve(here, '..');
const specPath = resolve(projectRoot, '../docs/contracts/openapi.yaml');
const outDir = resolve(projectRoot, 'src/types/light-admin');
const outFile = resolve(outDir, 'schema.ts');

async function loadAsOpenApi3(path: string): Promise<unknown> {
  const raw = readFileSync(path, 'utf8');
  const doc = yaml.load(raw) as Record<string, unknown>;
  if (typeof doc?.openapi === 'string' && doc.openapi.startsWith('3'))
    return doc;
  const { openapi } = await converter.convertObj(doc, {
    patch: true,
    warnOnly: true,
  });
  return openapi;
}

async function main() {
  const spec = await loadAsOpenApi3(specPath);
  const ast = await openapiTS(spec as never);
  const ts = astToString(ast);
  mkdirSync(outDir, { recursive: true });
  const header =
    '// AUTO-GENERATED by scripts/gen-types.ts from docs/contracts/openapi.yaml. Do not edit.\n' +
    '// Run `npm run gen:types` to regenerate.\n\n';
  writeFileSync(outFile, header + ts, 'utf8');
  // eslint-disable-next-line no-console
  console.log(`Wrote ${outFile}`);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
