// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: config.sql

package sqlitegen

import (
	"context"
	"time"
)

const countConfigs = `-- name: CountConfigs :one
SELECT COUNT(*) FROM t_config
WHERE is_deleted = 0
  AND (?1 IS NULL OR (config_name LIKE ?1 OR config_key LIKE ?1))
`

func (q *Queries) CountConfigs(ctx context.Context, keywords interface{}) (int64, error) {
	row := q.db.QueryRowContext(ctx, countConfigs, keywords)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countConfigsByKey = `-- name: CountConfigsByKey :one
SELECT COUNT(*) FROM t_config
WHERE config_key = ?1 AND is_deleted = 0
  AND (?2 IS NULL OR id <> ?2)
`

type CountConfigsByKeyParams struct {
	ConfigKey string
	ExcludeID interface{}
}

// Counts non-deleted configs with the given key, optionally excluding one id.
func (q *Queries) CountConfigsByKey(ctx context.Context, arg CountConfigsByKeyParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countConfigsByKey, arg.ConfigKey, arg.ExcludeID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createConfig = `-- name: CreateConfig :exec
INSERT INTO t_config (
    id, config_name, config_key, config_value, remark, create_by, update_by, is_deleted,
    create_time, update_time
) VALUES (
    ?1, ?2, ?3, ?4,
    ?5, ?6, ?7, ?8,
    ?9, ?9
)
`

type CreateConfigParams struct {
	ID          string
	ConfigName  string
	ConfigKey   string
	ConfigValue string
	Remark      string
	CreateBy    string
	UpdateBy    string
	IsDeleted   int32
	Now         time.Time
}

func (q *Queries) CreateConfig(ctx context.Context, arg CreateConfigParams) error {
	_, err := q.db.ExecContext(ctx, createConfig,
		arg.ID,
		arg.ConfigName,
		arg.ConfigKey,
		arg.ConfigValue,
		arg.Remark,
		arg.CreateBy,
		arg.UpdateBy,
		arg.IsDeleted,
		arg.Now,
	)
	return err
}

const getConfig = `-- name: GetConfig :one

SELECT id, config_name, config_key, config_value, remark, create_time, create_by, update_time, update_by, is_deleted FROM t_config WHERE id = ?1 AND is_deleted = 0
`

// config.sql (SQLite dialect)
// Derived from queries/postgres/config.sql per docs/multi-database-plan.md section 5:
// every parameter is a named sqlc.arg/narg (mixing anonymous ? with named args
// mis-numbers the placeholders under sqlc's sqlite engine). LIMIT/OFFSET are
// non-null args; the adapter maps a nil store limit/offset to -1/0 (SQLite:
// LIMIT -1 = no limit).
func (q *Queries) GetConfig(ctx context.Context, id string) (TConfig, error) {
	row := q.db.QueryRowContext(ctx, getConfig, id)
	var i TConfig
	err := row.Scan(
		&i.ID,
		&i.ConfigName,
		&i.ConfigKey,
		&i.ConfigValue,
		&i.Remark,
		&i.CreateTime,
		&i.CreateBy,
		&i.UpdateTime,
		&i.UpdateBy,
		&i.IsDeleted,
	)
	return i, err
}

const getConfigByKey = `-- name: GetConfigByKey :one
SELECT id, config_name, config_key, config_value, remark, create_time, create_by, update_time, update_by, is_deleted FROM t_config WHERE config_key = ?1 AND is_deleted = 0
`

func (q *Queries) GetConfigByKey(ctx context.Context, configKey string) (TConfig, error) {
	row := q.db.QueryRowContext(ctx, getConfigByKey, configKey)
	var i TConfig
	err := row.Scan(
		&i.ID,
		&i.ConfigName,
		&i.ConfigKey,
		&i.ConfigValue,
		&i.Remark,
		&i.CreateTime,
		&i.CreateBy,
		&i.UpdateTime,
		&i.UpdateBy,
		&i.IsDeleted,
	)
	return i, err
}

const listAllConfigs = `-- name: ListAllConfigs :many
SELECT id, config_name, config_key, config_value, remark, create_time, create_by, update_time, update_by, is_deleted FROM t_config WHERE is_deleted = 0
`

func (q *Queries) ListAllConfigs(ctx context.Context) ([]TConfig, error) {
	rows, err := q.db.QueryContext(ctx, listAllConfigs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TConfig{}
	for rows.Next() {
		var i TConfig
		if err := rows.Scan(
			&i.ID,
			&i.ConfigName,
			&i.ConfigKey,
			&i.ConfigValue,
			&i.Remark,
			&i.CreateTime,
			&i.CreateBy,
			&i.UpdateTime,
			&i.UpdateBy,
			&i.IsDeleted,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listConfigs = `-- name: ListConfigs :many
SELECT id, config_name, config_key, config_value, remark, create_time, create_by, update_time, update_by, is_deleted FROM t_config
WHERE is_deleted = 0
  AND (?1 IS NULL OR (config_name LIKE ?1 OR config_key LIKE ?1))
ORDER BY id DESC
LIMIT  ?3
OFFSET ?2
`

type ListConfigsParams struct {
	Keywords interface{}
	Offset   int64
	Limit    int64
}

func (q *Queries) ListConfigs(ctx context.Context, arg ListConfigsParams) ([]TConfig, error) {
	rows, err := q.db.QueryContext(ctx, listConfigs, arg.Keywords, arg.Offset, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TConfig{}
	for rows.Next() {
		var i TConfig
		if err := rows.Scan(
			&i.ID,
			&i.ConfigName,
			&i.ConfigKey,
			&i.ConfigValue,
			&i.Remark,
			&i.CreateTime,
			&i.CreateBy,
			&i.UpdateTime,
			&i.UpdateBy,
			&i.IsDeleted,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteConfig = `-- name: SoftDeleteConfig :exec
UPDATE t_config SET is_deleted = 1, update_by = ?1, update_time = ?2 WHERE id = ?3
`

type SoftDeleteConfigParams struct {
	UpdateBy string
	Now      time.Time
	ID       string
}

func (q *Queries) SoftDeleteConfig(ctx context.Context, arg SoftDeleteConfigParams) error {
	_, err := q.db.ExecContext(ctx, softDeleteConfig, arg.UpdateBy, arg.Now, arg.ID)
	return err
}

const updateConfig = `-- name: UpdateConfig :exec
UPDATE t_config SET
    config_name  = ?1,
    config_key   = ?2,
    config_value = ?3,
    remark       = ?4,
    update_by    = ?5,
    update_time  = ?6
WHERE id = ?7
`

type UpdateConfigParams struct {
	ConfigName  string
	ConfigKey   string
	ConfigValue string
	Remark      string
	UpdateBy    string
	Now         time.Time
	ID          string
}

func (q *Queries) UpdateConfig(ctx context.Context, arg UpdateConfigParams) error {
	_, err := q.db.ExecContext(ctx, updateConfig,
		arg.ConfigName,
		arg.ConfigKey,
		arg.ConfigValue,
		arg.Remark,
		arg.UpdateBy,
		arg.Now,
		arg.ID,
	)
	return err
}
