// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: dict.sql

package sqlitegen

import (
	"context"
	"strings"
	"time"
)

const countDicts = `-- name: CountDicts :one
SELECT COUNT(*) FROM t_dict
WHERE is_deleted = 0
  AND (?1 IS NULL OR (name LIKE ?1 OR dict_code LIKE ?1))
`

func (q *Queries) CountDicts(ctx context.Context, keywords interface{}) (int64, error) {
	row := q.db.QueryRowContext(ctx, countDicts, keywords)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createDict = `-- name: CreateDict :exec
INSERT INTO t_dict (
    id, dict_code, name, status, remark, create_by, update_by, is_deleted,
    create_time, update_time
) VALUES (
    ?1, ?2, ?3, ?4,
    ?5, ?6, ?7, ?8,
    ?9, ?9
)
`

type CreateDictParams struct {
	ID        string
	DictCode  string
	Name      string
	Status    int32
	Remark    string
	CreateBy  string
	UpdateBy  string
	IsDeleted int32
	Now       time.Time
}

func (q *Queries) CreateDict(ctx context.Context, arg CreateDictParams) error {
	_, err := q.db.ExecContext(ctx, createDict,
		arg.ID,
		arg.DictCode,
		arg.Name,
		arg.Status,
		arg.Remark,
		arg.CreateBy,
		arg.UpdateBy,
		arg.IsDeleted,
		arg.Now,
	)
	return err
}

const getDict = `-- name: GetDict :one

SELECT id, dict_code, name, status, remark, create_by, create_time, update_by, update_time, is_deleted FROM t_dict WHERE id = ?1 AND is_deleted = 0
`

// dict.sql (SQLite dialect)
// Derived from queries/postgres/dict.sql. Every parameter is a named
// sqlc.arg/narg (see config.sql header).
func (q *Queries) GetDict(ctx context.Context, id string) (TDict, error) {
	row := q.db.QueryRowContext(ctx, getDict, id)
	var i TDict
	err := row.Scan(
		&i.ID,
		&i.DictCode,
		&i.Name,
		&i.Status,
		&i.Remark,
		&i.CreateBy,
		&i.CreateTime,
		&i.UpdateBy,
		&i.UpdateTime,
		&i.IsDeleted,
	)
	return i, err
}

const getDictByCode = `-- name: GetDictByCode :one
SELECT id, dict_code, name, status, remark, create_by, create_time, update_by, update_time, is_deleted FROM t_dict
WHERE dict_code = ?1 AND is_deleted = 0
  AND (?2 IS NULL OR id <> ?2)
LIMIT 1
`

type GetDictByCodeParams struct {
	DictCode  string
	ExcludeID interface{}
}

func (q *Queries) GetDictByCode(ctx context.Context, arg GetDictByCodeParams) (TDict, error) {
	row := q.db.QueryRowContext(ctx, getDictByCode, arg.DictCode, arg.ExcludeID)
	var i TDict
	err := row.Scan(
		&i.ID,
		&i.DictCode,
		&i.Name,
		&i.Status,
		&i.Remark,
		&i.CreateBy,
		&i.CreateTime,
		&i.UpdateBy,
		&i.UpdateTime,
		&i.IsDeleted,
	)
	return i, err
}

const listDicts = `-- name: ListDicts :many
SELECT id, dict_code, name, status, remark, create_by, create_time, update_by, update_time, is_deleted FROM t_dict
WHERE is_deleted = 0
  AND (?1 IS NULL OR (name LIKE ?1 OR dict_code LIKE ?1))
ORDER BY create_time DESC
LIMIT  ?3
OFFSET ?2
`

type ListDictsParams struct {
	Keywords interface{}
	Offset   int64
	Limit    int64
}

func (q *Queries) ListDicts(ctx context.Context, arg ListDictsParams) ([]TDict, error) {
	rows, err := q.db.QueryContext(ctx, listDicts, arg.Keywords, arg.Offset, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TDict{}
	for rows.Next() {
		var i TDict
		if err := rows.Scan(
			&i.ID,
			&i.DictCode,
			&i.Name,
			&i.Status,
			&i.Remark,
			&i.CreateBy,
			&i.CreateTime,
			&i.UpdateBy,
			&i.UpdateTime,
			&i.IsDeleted,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDictsByIDs = `-- name: ListDictsByIDs :many
SELECT id, dict_code, name, status, remark, create_by, create_time, update_by, update_time, is_deleted FROM t_dict WHERE is_deleted = 0 AND id IN (/*SLICE:ids*/?)
`

func (q *Queries) ListDictsByIDs(ctx context.Context, ids []string) ([]TDict, error) {
	query := listDictsByIDs
	var queryParams []interface{}
	if len(ids) > 0 {
		for _, v := range ids {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:ids*/?", strings.Repeat(",?", len(ids))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:ids*/?", "NULL", 1)
	}
	rows, err := q.db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TDict{}
	for rows.Next() {
		var i TDict
		if err := rows.Scan(
			&i.ID,
			&i.DictCode,
			&i.Name,
			&i.Status,
			&i.Remark,
			&i.CreateBy,
			&i.CreateTime,
			&i.UpdateBy,
			&i.UpdateTime,
			&i.IsDeleted,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEnabledDicts = `-- name: ListEnabledDicts :many
SELECT id, dict_code, name, status, remark, create_by, create_time, update_by, update_time, is_deleted FROM t_dict WHERE is_deleted = 0 AND status = 1
`

func (q *Queries) ListEnabledDicts(ctx context.Context) ([]TDict, error) {
	rows, err := q.db.QueryContext(ctx, listEnabledDicts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TDict{}
	for rows.Next() {
		var i TDict
		if err := rows.Scan(
			&i.ID,
			&i.DictCode,
			&i.Name,
			&i.Status,
			&i.Remark,
			&i.CreateBy,
			&i.CreateTime,
			&i.UpdateBy,
			&i.UpdateTime,
			&i.IsDeleted,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteDict = `-- name: SoftDeleteDict :exec
UPDATE t_dict SET is_deleted = 1, update_by = ?1, update_time = ?2 WHERE id = ?3
`

type SoftDeleteDictParams struct {
	UpdateBy string
	Now      time.Time
	ID       string
}

func (q *Queries) SoftDeleteDict(ctx context.Context, arg SoftDeleteDictParams) error {
	_, err := q.db.ExecContext(ctx, softDeleteDict, arg.UpdateBy, arg.Now, arg.ID)
	return err
}

const softDeleteDictsByIDs = `-- name: SoftDeleteDictsByIDs :exec
UPDATE t_dict SET is_deleted = 1, update_by = ?1, update_time = ?2
WHERE id IN (/*SLICE:ids*/?)
`

type SoftDeleteDictsByIDsParams struct {
	UpdateBy string
	Now      time.Time
	Ids      []string
}

func (q *Queries) SoftDeleteDictsByIDs(ctx context.Context, arg SoftDeleteDictsByIDsParams) error {
	query := softDeleteDictsByIDs
	var queryParams []interface{}
	queryParams = append(queryParams, arg.UpdateBy)
	queryParams = append(queryParams, arg.Now)
	if len(arg.Ids) > 0 {
		for _, v := range arg.Ids {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:ids*/?", strings.Repeat(",?", len(arg.Ids))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:ids*/?", "NULL", 1)
	}
	_, err := q.db.ExecContext(ctx, query, queryParams...)
	return err
}

const updateDict = `-- name: UpdateDict :exec
UPDATE t_dict SET
    dict_code   = ?1,
    name        = ?2,
    status      = ?3,
    remark      = ?4,
    update_by   = ?5,
    update_time = ?6
WHERE id = ?7
`

type UpdateDictParams struct {
	DictCode string
	Name     string
	Status   int32
	Remark   string
	UpdateBy string
	Now      time.Time
	ID       string
}

func (q *Queries) UpdateDict(ctx context.Context, arg UpdateDictParams) error {
	_, err := q.db.ExecContext(ctx, updateDict,
		arg.DictCode,
		arg.Name,
		arg.Status,
		arg.Remark,
		arg.UpdateBy,
		arg.Now,
		arg.ID,
	)
	return err
}
