// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: notice.sql

package sqlitegen

import (
	"context"
	"strings"
	"time"
)

const countNotices = `-- name: CountNotices :one
SELECT COUNT(*) FROM t_notice
WHERE is_deleted = 0
  AND (?1 IS NULL OR title LIKE ?1)
  AND (?2  IS NULL OR type = ?2)
  AND (?3 IS NULL OR publish_status = ?3)
`

type CountNoticesParams struct {
	Title         interface{}
	Type          interface{}
	PublishStatus interface{}
}

func (q *Queries) CountNotices(ctx context.Context, arg CountNoticesParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countNotices, arg.Title, arg.Type, arg.PublishStatus)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createNotice = `-- name: CreateNotice :exec
INSERT INTO t_notice (
    id, title, content, type, level, target_type, target_user_ids,
    publish_status, create_by, is_deleted, create_time, update_time
) VALUES (
    ?1, ?2, ?3, ?4,
    ?5, ?6, ?7,
    ?8, ?9, ?10,
    ?11, ?11
)
`

type CreateNoticeParams struct {
	ID            string
	Title         string
	Content       string
	Type          int32
	Level         string
	TargetType    int32
	TargetUserIds string
	PublishStatus int32
	CreateBy      string
	IsDeleted     int32
	Now           time.Time
}

func (q *Queries) CreateNotice(ctx context.Context, arg CreateNoticeParams) error {
	_, err := q.db.ExecContext(ctx, createNotice,
		arg.ID,
		arg.Title,
		arg.Content,
		arg.Type,
		arg.Level,
		arg.TargetType,
		arg.TargetUserIds,
		arg.PublishStatus,
		arg.CreateBy,
		arg.IsDeleted,
		arg.Now,
	)
	return err
}

const getNotice = `-- name: GetNotice :one

SELECT id, title, content, type, level, target_type, target_user_ids, publisher_id, publish_status, publish_time, revoke_time, create_by, create_time, update_by, update_time, is_deleted FROM t_notice WHERE id = ?1 AND is_deleted = 0
`

// notice.sql (SQLite dialect)
// Derived from queries/postgres/notice.sql. Every parameter is a named
// sqlc.arg/narg (see config.sql header).
func (q *Queries) GetNotice(ctx context.Context, id string) (TNotice, error) {
	row := q.db.QueryRowContext(ctx, getNotice, id)
	var i TNotice
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Content,
		&i.Type,
		&i.Level,
		&i.TargetType,
		&i.TargetUserIds,
		&i.PublisherID,
		&i.PublishStatus,
		&i.PublishTime,
		&i.RevokeTime,
		&i.CreateBy,
		&i.CreateTime,
		&i.UpdateBy,
		&i.UpdateTime,
		&i.IsDeleted,
	)
	return i, err
}

const listNotices = `-- name: ListNotices :many
SELECT id, title, content, type, level, target_type, target_user_ids, publisher_id, publish_status, publish_time, revoke_time, create_by, create_time, update_by, update_time, is_deleted FROM t_notice
WHERE is_deleted = 0
  AND (?1 IS NULL OR title LIKE ?1)
  AND (?2  IS NULL OR type = ?2)
  AND (?3 IS NULL OR publish_status = ?3)
ORDER BY create_time DESC
LIMIT  ?5
OFFSET ?4
`

type ListNoticesParams struct {
	Title         interface{}
	Type          interface{}
	PublishStatus interface{}
	Offset        int64
	Limit         int64
}

func (q *Queries) ListNotices(ctx context.Context, arg ListNoticesParams) ([]TNotice, error) {
	rows, err := q.db.QueryContext(ctx, listNotices,
		arg.Title,
		arg.Type,
		arg.PublishStatus,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TNotice{}
	for rows.Next() {
		var i TNotice
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Content,
			&i.Type,
			&i.Level,
			&i.TargetType,
			&i.TargetUserIds,
			&i.PublisherID,
			&i.PublishStatus,
			&i.PublishTime,
			&i.RevokeTime,
			&i.CreateBy,
			&i.CreateTime,
			&i.UpdateBy,
			&i.UpdateTime,
			&i.IsDeleted,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteNoticesByIDs = `-- name: SoftDeleteNoticesByIDs :exec
UPDATE t_notice SET is_deleted = 1, update_by = ?1, update_time = ?2
WHERE id IN (/*SLICE:ids*/?)
`

type SoftDeleteNoticesByIDsParams struct {
	UpdateBy string
	Now      time.Time
	Ids      []string
}

func (q *Queries) SoftDeleteNoticesByIDs(ctx context.Context, arg SoftDeleteNoticesByIDsParams) error {
	query := softDeleteNoticesByIDs
	var queryParams []interface{}
	queryParams = append(queryParams, arg.UpdateBy)
	queryParams = append(queryParams, arg.Now)
	if len(arg.Ids) > 0 {
		for _, v := range arg.Ids {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:ids*/?", strings.Repeat(",?", len(arg.Ids))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:ids*/?", "NULL", 1)
	}
	_, err := q.db.ExecContext(ctx, query, queryParams...)
	return err
}

const updateNotice = `-- name: UpdateNotice :exec
UPDATE t_notice SET
    title           = ?1,
    content         = ?2,
    type            = ?3,
    level           = ?4,
    target_type     = ?5,
    target_user_ids = ?6,
    update_by       = ?7,
    update_time     = ?8
WHERE id = ?9
`

type UpdateNoticeParams struct {
	Title         string
	Content       string
	Type          int32
	Level         string
	TargetType    int32
	TargetUserIds string
	UpdateBy      string
	Now           time.Time
	ID            string
}

func (q *Queries) UpdateNotice(ctx context.Context, arg UpdateNoticeParams) error {
	_, err := q.db.ExecContext(ctx, updateNotice,
		arg.Title,
		arg.Content,
		arg.Type,
		arg.Level,
		arg.TargetType,
		arg.TargetUserIds,
		arg.UpdateBy,
		arg.Now,
		arg.ID,
	)
	return err
}

const updateNoticeStatus = `-- name: UpdateNoticeStatus :exec
UPDATE t_notice SET
    publish_status = ?1,
    publisher_id   = ?2,
    publish_time   = COALESCE(?3, publish_time),
    revoke_time    = COALESCE(?4, revoke_time),
    update_time    = ?5
WHERE id = ?6
`

type UpdateNoticeStatusParams struct {
	PublishStatus int32
	PublisherID   string
	PublishTime   *time.Time
	RevokeTime    *time.Time
	Now           time.Time
	ID            string
}

func (q *Queries) UpdateNoticeStatus(ctx context.Context, arg UpdateNoticeStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateNoticeStatus,
		arg.PublishStatus,
		arg.PublisherID,
		arg.PublishTime,
		arg.RevokeTime,
		arg.Now,
		arg.ID,
	)
	return err
}
