// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queue_task.sql

package sqlitegen

import (
	"context"
	"time"
)

const createQueueTask = `-- name: CreateQueueTask :one

INSERT INTO sys_tasks (
    type, status, correlation_id, owner_id, private_state,
    public_retry_count, public_executed_duration, public_error,
    public_error_history, public_resume_time, created_at, updated_at
) VALUES (
    ?1, ?2, ?3, ?4,
    ?5, ?6, ?7,
    ?8, ?9, ?10,
    ?11, ?11
)
RETURNING id, type, status, correlation_id, owner_id, private_state, public_retry_count, public_executed_duration, public_error, public_error_history, public_resume_time, created_at, updated_at, deleted_at
`

type CreateQueueTaskParams struct {
	Type                   string
	Status                 string
	CorrelationID          string
	OwnerID                string
	PrivateState           string
	PublicRetryCount       int32
	PublicExecutedDuration int64
	PublicError            string
	PublicErrorHistory     string
	PublicResumeTime       int64
	Now                    time.Time
}

// queue_task.sql (SQLite dialect)
// Derived from queries/postgres/queue_task.sql. Every parameter is a named
// sqlc.arg/narg (see config.sql header). RETURNING is native on
// SQLite >= 3.35. The nullable type-list filter uses the comma-wrapped
// instr() membership test (see menu.sql header).
func (q *Queries) CreateQueueTask(ctx context.Context, arg CreateQueueTaskParams) (SysTask, error) {
	row := q.db.QueryRowContext(ctx, createQueueTask,
		arg.Type,
		arg.Status,
		arg.CorrelationID,
		arg.OwnerID,
		arg.PrivateState,
		arg.PublicRetryCount,
		arg.PublicExecutedDuration,
		arg.PublicError,
		arg.PublicErrorHistory,
		arg.PublicResumeTime,
		arg.Now,
	)
	var i SysTask
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.Status,
		&i.CorrelationID,
		&i.OwnerID,
		&i.PrivateState,
		&i.PublicRetryCount,
		&i.PublicExecutedDuration,
		&i.PublicError,
		&i.PublicErrorHistory,
		&i.PublicResumeTime,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getQueueTask = `-- name: GetQueueTask :one
SELECT id, type, status, correlation_id, owner_id, private_state, public_retry_count, public_executed_duration, public_error, public_error_history, public_resume_time, created_at, updated_at, deleted_at FROM sys_tasks WHERE id = ?1 AND deleted_at IS NULL
`

func (q *Queries) GetQueueTask(ctx context.Context, id int64) (SysTask, error) {
	row := q.db.QueryRowContext(ctx, getQueueTask, id)
	var i SysTask
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.Status,
		&i.CorrelationID,
		&i.OwnerID,
		&i.PrivateState,
		&i.PublicRetryCount,
		&i.PublicExecutedDuration,
		&i.PublicError,
		&i.PublicErrorHistory,
		&i.PublicResumeTime,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listPendingQueueTasks = `-- name: ListPendingQueueTasks :many
SELECT id, type, status, correlation_id, owner_id, private_state, public_retry_count, public_executed_duration, public_error, public_error_history, public_resume_time, created_at, updated_at, deleted_at FROM sys_tasks
WHERE deleted_at IS NULL
  AND status IN ('queued', 'processing', 'suspending')
  AND (?1 IS NULL OR instr(?1, ',' || type || ',') > 0)
ORDER BY id
`

func (q *Queries) ListPendingQueueTasks(ctx context.Context, types interface{}) ([]SysTask, error) {
	rows, err := q.db.QueryContext(ctx, listPendingQueueTasks, types)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SysTask{}
	for rows.Next() {
		var i SysTask
		if err := rows.Scan(
			&i.ID,
			&i.Type,
			&i.Status,
			&i.CorrelationID,
			&i.OwnerID,
			&i.PrivateState,
			&i.PublicRetryCount,
			&i.PublicExecutedDuration,
			&i.PublicError,
			&i.PublicErrorHistory,
			&i.PublicResumeTime,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteQueueTask = `-- name: SoftDeleteQueueTask :exec
UPDATE sys_tasks SET deleted_at = ?1 WHERE id = ?2 AND deleted_at IS NULL
`

type SoftDeleteQueueTaskParams struct {
	Now *time.Time
	ID  int64
}

func (q *Queries) SoftDeleteQueueTask(ctx context.Context, arg SoftDeleteQueueTaskParams) error {
	_, err := q.db.ExecContext(ctx, softDeleteQueueTask, arg.Now, arg.ID)
	return err
}

const updateQueueTask = `-- name: UpdateQueueTask :one
UPDATE sys_tasks SET
    type                     = ?1,
    status                   = ?2,
    correlation_id           = ?3,
    owner_id                 = ?4,
    private_state            = ?5,
    public_retry_count       = ?6,
    public_executed_duration = ?7,
    public_error             = ?8,
    public_error_history     = ?9,
    public_resume_time       = ?10,
    updated_at               = ?11
WHERE id = ?12 AND deleted_at IS NULL
RETURNING id, type, status, correlation_id, owner_id, private_state, public_retry_count, public_executed_duration, public_error, public_error_history, public_resume_time, created_at, updated_at, deleted_at
`

type UpdateQueueTaskParams struct {
	Type                   string
	Status                 string
	CorrelationID          string
	OwnerID                string
	PrivateState           string
	PublicRetryCount       int32
	PublicExecutedDuration int64
	PublicError            string
	PublicErrorHistory     string
	PublicResumeTime       int64
	Now                    time.Time
	ID                     int64
}

func (q *Queries) UpdateQueueTask(ctx context.Context, arg UpdateQueueTaskParams) (SysTask, error) {
	row := q.db.QueryRowContext(ctx, updateQueueTask,
		arg.Type,
		arg.Status,
		arg.CorrelationID,
		arg.OwnerID,
		arg.PrivateState,
		arg.PublicRetryCount,
		arg.PublicExecutedDuration,
		arg.PublicError,
		arg.PublicErrorHistory,
		arg.PublicResumeTime,
		arg.Now,
		arg.ID,
	)
	var i SysTask
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.Status,
		&i.CorrelationID,
		&i.OwnerID,
		&i.PrivateState,
		&i.PublicRetryCount,
		&i.PublicExecutedDuration,
		&i.PublicError,
		&i.PublicErrorHistory,
		&i.PublicResumeTime,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
