// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tenant.sql

package sqlitegen

import (
	"context"
	"time"
)

const countTenants = `-- name: CountTenants :one
SELECT COUNT(*) FROM t_tenant
WHERE is_deleted = 0
  AND (?1 IS NULL OR (code LIKE ?1 OR name LIKE ?1))
  AND (?2   IS NULL OR status = ?2)
`

type CountTenantsParams struct {
	Keywords interface{}
	Status   interface{}
}

func (q *Queries) CountTenants(ctx context.Context, arg CountTenantsParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countTenants, arg.Keywords, arg.Status)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createTenant = `-- name: CreateTenant :exec
INSERT INTO t_tenant (id, code, name, status, create_by, is_deleted, create_time, update_time)
VALUES (?1, ?2, ?3, ?4,
        ?5, ?6, ?7, ?7)
`

type CreateTenantParams struct {
	ID        string
	Code      string
	Name      string
	Status    int32
	CreateBy  string
	IsDeleted int32
	Now       time.Time
}

func (q *Queries) CreateTenant(ctx context.Context, arg CreateTenantParams) error {
	_, err := q.db.ExecContext(ctx, createTenant,
		arg.ID,
		arg.Code,
		arg.Name,
		arg.Status,
		arg.CreateBy,
		arg.IsDeleted,
		arg.Now,
	)
	return err
}

const getTenant = `-- name: GetTenant :one

SELECT id, code, name, status, create_time, create_by, update_time, update_by, is_deleted FROM t_tenant WHERE id = ?1 AND is_deleted = 0
`

// tenant.sql (SQLite dialect)
// Derived from queries/postgres/tenant.sql. Every parameter is a named
// sqlc.arg/narg (see config.sql header).
func (q *Queries) GetTenant(ctx context.Context, id string) (TTenant, error) {
	row := q.db.QueryRowContext(ctx, getTenant, id)
	var i TTenant
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.Status,
		&i.CreateTime,
		&i.CreateBy,
		&i.UpdateTime,
		&i.UpdateBy,
		&i.IsDeleted,
	)
	return i, err
}

const getTenantByCode = `-- name: GetTenantByCode :one
SELECT id, code, name, status, create_time, create_by, update_time, update_by, is_deleted FROM t_tenant WHERE code = ?1 AND is_deleted = 0
`

func (q *Queries) GetTenantByCode(ctx context.Context, code string) (TTenant, error) {
	row := q.db.QueryRowContext(ctx, getTenantByCode, code)
	var i TTenant
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.Status,
		&i.CreateTime,
		&i.CreateBy,
		&i.UpdateTime,
		&i.UpdateBy,
		&i.IsDeleted,
	)
	return i, err
}

const listTenants = `-- name: ListTenants :many
SELECT id, code, name, status, create_time, create_by, update_time, update_by, is_deleted FROM t_tenant
WHERE is_deleted = 0
  AND (?1 IS NULL OR (code LIKE ?1 OR name LIKE ?1))
  AND (?2   IS NULL OR status = ?2)
ORDER BY id DESC
LIMIT  ?4
OFFSET ?3
`

type ListTenantsParams struct {
	Keywords interface{}
	Status   interface{}
	Offset   int64
	Limit    int64
}

func (q *Queries) ListTenants(ctx context.Context, arg ListTenantsParams) ([]TTenant, error) {
	rows, err := q.db.QueryContext(ctx, listTenants,
		arg.Keywords,
		arg.Status,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TTenant{}
	for rows.Next() {
		var i TTenant
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.Name,
			&i.Status,
			&i.CreateTime,
			&i.CreateBy,
			&i.UpdateTime,
			&i.UpdateBy,
			&i.IsDeleted,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteTenant = `-- name: SoftDeleteTenant :exec
UPDATE t_tenant SET is_deleted = 1, update_time = ?1 WHERE id = ?2
`

type SoftDeleteTenantParams struct {
	Now time.Time
	ID  string
}

func (q *Queries) SoftDeleteTenant(ctx context.Context, arg SoftDeleteTenantParams) error {
	_, err := q.db.ExecContext(ctx, softDeleteTenant, arg.Now, arg.ID)
	return err
}

const updateTenant = `-- name: UpdateTenant :exec
UPDATE t_tenant SET code = ?1, name = ?2, status = ?3,
    update_by = ?4, update_time = ?5
WHERE id = ?6
`

type UpdateTenantParams struct {
	Code     string
	Name     string
	Status   int32
	UpdateBy string
	Now      time.Time
	ID       string
}

func (q *Queries) UpdateTenant(ctx context.Context, arg UpdateTenantParams) error {
	_, err := q.db.ExecContext(ctx, updateTenant,
		arg.Code,
		arg.Name,
		arg.Status,
		arg.UpdateBy,
		arg.Now,
		arg.ID,
	)
	return err
}
