// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: user.sql

package sqlitegen

import (
	"context"
	"time"
)

const countUsers = `-- name: CountUsers :one
SELECT COUNT(*) FROM t_user
WHERE is_deleted = 0
  AND (?1 IS NULL OR username = ?1)
  AND (?2 IS NULL OR nickname = ?2)
  AND (?3   IS NULL OR status   = ?3)
  AND (?4  IS NULL OR dept_id  = ?4)
  AND (?5 IS NULL OR (
        username LIKE ?5 OR
        nickname LIKE ?5 OR
        mobile   LIKE ?5 OR
        email    LIKE ?5))
  AND (?6 IS NULL OR create_time >= ?6)
  AND (?7   IS NULL OR create_time <= ?7)
  AND (?8 IS NULL OR id IN (
        SELECT user_id FROM t_user_role WHERE instr(?8, ',' || role_id || ',') > 0))
`

type CountUsersParams struct {
	Username   interface{}
	Nickname   interface{}
	Status     interface{}
	DeptID     interface{}
	Keywords   interface{}
	CreateFrom interface{}
	CreateTo   interface{}
	RoleIds    interface{}
}

func (q *Queries) CountUsers(ctx context.Context, arg CountUsersParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countUsers,
		arg.Username,
		arg.Nickname,
		arg.Status,
		arg.DeptID,
		arg.Keywords,
		arg.CreateFrom,
		arg.CreateTo,
		arg.RoleIds,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createUser = `-- name: CreateUser :exec
INSERT INTO t_user (
    id, username, nickname, gender, password, dept_id, avatar,
    mobile, status, email, create_by, update_by, is_deleted, openid,
    create_time, update_time
) VALUES (
    ?1, ?2, ?3, ?4,
    ?5, ?6, ?7,
    ?8, ?9, ?10, ?11,
    ?12, ?13, ?14,
    ?15, ?15
)
`

type CreateUserParams struct {
	ID        string
	Username  string
	Nickname  string
	Gender    int32
	Password  string
	DeptID    string
	Avatar    string
	Mobile    string
	Status    int32
	Email     string
	CreateBy  string
	UpdateBy  string
	IsDeleted int32
	Openid    string
	Now       time.Time
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) error {
	_, err := q.db.ExecContext(ctx, createUser,
		arg.ID,
		arg.Username,
		arg.Nickname,
		arg.Gender,
		arg.Password,
		arg.DeptID,
		arg.Avatar,
		arg.Mobile,
		arg.Status,
		arg.Email,
		arg.CreateBy,
		arg.UpdateBy,
		arg.IsDeleted,
		arg.Openid,
		arg.Now,
	)
	return err
}

const getUser = `-- name: GetUser :one

SELECT id, username, nickname, gender, password, dept_id, avatar, mobile, status, email, create_time, create_by, update_time, update_by, is_deleted, openid FROM t_user
WHERE id = ?1 AND is_deleted = 0
`

// user.sql (SQLite dialect)
// Derived from queries/postgres/user.sql. Every parameter is a named
// sqlc.arg/narg (see config.sql header). ILIKE becomes LIKE (SQLite LIKE is
// already case-insensitive for ASCII). The nullable role-id list uses the
// comma-wrapped instr() membership test (see menu.sql header).
func (q *Queries) GetUser(ctx context.Context, id string) (TUser, error) {
	row := q.db.QueryRowContext(ctx, getUser, id)
	var i TUser
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Nickname,
		&i.Gender,
		&i.Password,
		&i.DeptID,
		&i.Avatar,
		&i.Mobile,
		&i.Status,
		&i.Email,
		&i.CreateTime,
		&i.CreateBy,
		&i.UpdateTime,
		&i.UpdateBy,
		&i.IsDeleted,
		&i.Openid,
	)
	return i, err
}

const getUserByUsername = `-- name: GetUserByUsername :one
SELECT id, username, nickname, gender, password, dept_id, avatar, mobile, status, email, create_time, create_by, update_time, update_by, is_deleted, openid FROM t_user
WHERE username = ?1 AND is_deleted = 0
LIMIT 1
`

func (q *Queries) GetUserByUsername(ctx context.Context, username string) (TUser, error) {
	row := q.db.QueryRowContext(ctx, getUserByUsername, username)
	var i TUser
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Nickname,
		&i.Gender,
		&i.Password,
		&i.DeptID,
		&i.Avatar,
		&i.Mobile,
		&i.Status,
		&i.Email,
		&i.CreateTime,
		&i.CreateBy,
		&i.UpdateTime,
		&i.UpdateBy,
		&i.IsDeleted,
		&i.Openid,
	)
	return i, err
}

const listUsers = `-- name: ListUsers :many
SELECT id, username, nickname, gender, password, dept_id, avatar, mobile, status, email, create_time, create_by, update_time, update_by, is_deleted, openid FROM t_user
WHERE is_deleted = 0
  AND (?1 IS NULL OR username = ?1)
  AND (?2 IS NULL OR nickname = ?2)
  AND (?3   IS NULL OR status   = ?3)
  AND (?4  IS NULL OR dept_id  = ?4)
  AND (?5 IS NULL OR (
        username LIKE ?5 OR
        nickname LIKE ?5 OR
        mobile   LIKE ?5 OR
        email    LIKE ?5))
  AND (?6 IS NULL OR create_time >= ?6)
  AND (?7   IS NULL OR create_time <= ?7)
  AND (?8 IS NULL OR id IN (
        SELECT user_id FROM t_user_role WHERE instr(?8, ',' || role_id || ',') > 0))
ORDER BY create_time DESC
LIMIT  ?10
OFFSET ?9
`

type ListUsersParams struct {
	Username   interface{}
	Nickname   interface{}
	Status     interface{}
	DeptID     interface{}
	Keywords   interface{}
	CreateFrom interface{}
	CreateTo   interface{}
	RoleIds    interface{}
	Offset     int64
	Limit      int64
}

func (q *Queries) ListUsers(ctx context.Context, arg ListUsersParams) ([]TUser, error) {
	rows, err := q.db.QueryContext(ctx, listUsers,
		arg.Username,
		arg.Nickname,
		arg.Status,
		arg.DeptID,
		arg.Keywords,
		arg.CreateFrom,
		arg.CreateTo,
		arg.RoleIds,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TUser{}
	for rows.Next() {
		var i TUser
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.Nickname,
			&i.Gender,
			&i.Password,
			&i.DeptID,
			&i.Avatar,
			&i.Mobile,
			&i.Status,
			&i.Email,
			&i.CreateTime,
			&i.CreateBy,
			&i.UpdateTime,
			&i.UpdateBy,
			&i.IsDeleted,
			&i.Openid,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteUser = `-- name: SoftDeleteUser :exec
UPDATE t_user SET is_deleted = 1, update_time = ?1 WHERE id = ?2
`

type SoftDeleteUserParams struct {
	Now time.Time
	ID  string
}

func (q *Queries) SoftDeleteUser(ctx context.Context, arg SoftDeleteUserParams) error {
	_, err := q.db.ExecContext(ctx, softDeleteUser, arg.Now, arg.ID)
	return err
}

const updateUser = `-- name: UpdateUser :exec
UPDATE t_user SET
    username    = ?1,
    nickname    = ?2,
    gender      = ?3,
    dept_id     = ?4,
    avatar      = ?5,
    mobile      = ?6,
    status      = ?7,
    email       = ?8,
    update_by   = ?9,
    update_time = ?10
WHERE id = ?11
`

type UpdateUserParams struct {
	Username string
	Nickname string
	Gender   int32
	DeptID   string
	Avatar   string
	Mobile   string
	Status   int32
	Email    string
	UpdateBy string
	Now      time.Time
	ID       string
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) error {
	_, err := q.db.ExecContext(ctx, updateUser,
		arg.Username,
		arg.Nickname,
		arg.Gender,
		arg.DeptID,
		arg.Avatar,
		arg.Mobile,
		arg.Status,
		arg.Email,
		arg.UpdateBy,
		arg.Now,
		arg.ID,
	)
	return err
}

const updateUserPassword = `-- name: UpdateUserPassword :exec
UPDATE t_user SET password = ?1, update_time = ?2 WHERE id = ?3
`

type UpdateUserPasswordParams struct {
	Password string
	Now      time.Time
	ID       string
}

func (q *Queries) UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error {
	_, err := q.db.ExecContext(ctx, updateUserPassword, arg.Password, arg.Now, arg.ID)
	return err
}

const updateUserProfile = `-- name: UpdateUserProfile :exec
UPDATE t_user SET
    nickname    = COALESCE(?1, nickname),
    gender      = COALESCE(?2,   gender),
    avatar      = COALESCE(?3,   avatar),
    mobile      = COALESCE(?4,   mobile),
    email       = COALESCE(?5,    email),
    update_time = ?6
WHERE id = ?7
`

type UpdateUserProfileParams struct {
	Nickname *string
	Gender   *int32
	Avatar   *string
	Mobile   *string
	Email    *string
	Now      time.Time
	ID       string
}

func (q *Queries) UpdateUserProfile(ctx context.Context, arg UpdateUserProfileParams) error {
	_, err := q.db.ExecContext(ctx, updateUserProfile,
		arg.Nickname,
		arg.Gender,
		arg.Avatar,
		arg.Mobile,
		arg.Email,
		arg.Now,
		arg.ID,
	)
	return err
}

const updateUserStatus = `-- name: UpdateUserStatus :exec
UPDATE t_user SET status = ?1, update_time = ?2 WHERE id = ?3
`

type UpdateUserStatusParams struct {
	Status int32
	Now    time.Time
	ID     string
}

func (q *Queries) UpdateUserStatus(ctx context.Context, arg UpdateUserStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateUserStatus, arg.Status, arg.Now, arg.ID)
	return err
}
