// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: user_role.sql

package sqlitegen

import (
	"context"
)

const countUserRoles = `-- name: CountUserRoles :one
SELECT COUNT(*) FROM t_user_role
WHERE (?1  IS NULL OR user_id = ?1)
  AND (?2 IS NULL OR instr(?2, ',' || user_id || ',') > 0)
`

type CountUserRolesParams struct {
	UserID  interface{}
	UserIds interface{}
}

func (q *Queries) CountUserRoles(ctx context.Context, arg CountUserRolesParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countUserRoles, arg.UserID, arg.UserIds)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createUserRole = `-- name: CreateUserRole :exec
INSERT OR IGNORE INTO t_user_role (user_id, role_id) VALUES (?1, ?2)
`

type CreateUserRoleParams struct {
	UserID string
	RoleID string
}

func (q *Queries) CreateUserRole(ctx context.Context, arg CreateUserRoleParams) error {
	_, err := q.db.ExecContext(ctx, createUserRole, arg.UserID, arg.RoleID)
	return err
}

const deleteUserRolesByRoleID = `-- name: DeleteUserRolesByRoleID :exec
DELETE FROM t_user_role WHERE role_id = ?1
`

func (q *Queries) DeleteUserRolesByRoleID(ctx context.Context, roleID string) error {
	_, err := q.db.ExecContext(ctx, deleteUserRolesByRoleID, roleID)
	return err
}

const deleteUserRolesByUserID = `-- name: DeleteUserRolesByUserID :exec
DELETE FROM t_user_role WHERE user_id = ?1
`

func (q *Queries) DeleteUserRolesByUserID(ctx context.Context, userID string) error {
	_, err := q.db.ExecContext(ctx, deleteUserRolesByUserID, userID)
	return err
}

const getRoleIDsByUserID = `-- name: GetRoleIDsByUserID :many
SELECT role_id FROM t_user_role WHERE user_id = ?1
`

func (q *Queries) GetRoleIDsByUserID(ctx context.Context, userID string) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, getRoleIDsByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var role_id string
		if err := rows.Scan(&role_id); err != nil {
			return nil, err
		}
		items = append(items, role_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserIDsByRoleID = `-- name: GetUserIDsByRoleID :many
SELECT user_id FROM t_user_role WHERE role_id = ?1
`

func (q *Queries) GetUserIDsByRoleID(ctx context.Context, roleID string) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, getUserIDsByRoleID, roleID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var user_id string
		if err := rows.Scan(&user_id); err != nil {
			return nil, err
		}
		items = append(items, user_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserRoles = `-- name: ListUserRoles :many

SELECT user_id, role_id FROM t_user_role
WHERE (?1  IS NULL OR user_id = ?1)
  AND (?2 IS NULL OR instr(?2, ',' || user_id || ',') > 0)
ORDER BY user_id DESC
LIMIT  ?4
OFFSET ?3
`

type ListUserRolesParams struct {
	UserID  interface{}
	UserIds interface{}
	Offset  int64
	Limit   int64
}

// user_role.sql (SQLite dialect)
// Derived from queries/postgres/user_role.sql. Every parameter is a named
// sqlc.arg/narg (see config.sql header). The nullable user-id list uses the
// comma-wrapped instr() membership test (see menu.sql header). SQLite has no
// unnest(): BatchCreateUserRoles is implemented in the sqlitestore adapter as
// a loop over CreateUserRole (INSERT OR IGNORE replaces ON CONFLICT).
// Ordering is fixed (user_id DESC) rather than interpolated, eliminating any
// ORDER BY injection surface. This matches the sole caller's default ordering.
func (q *Queries) ListUserRoles(ctx context.Context, arg ListUserRolesParams) ([]TUserRole, error) {
	rows, err := q.db.QueryContext(ctx, listUserRoles,
		arg.UserID,
		arg.UserIds,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TUserRole{}
	for rows.Next() {
		var i TUserRole
		if err := rows.Scan(&i.UserID, &i.RoleID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
