// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: user_notice.sql

package sqlitegen

import (
	"context"
	"strings"
	"time"
)

const countMyNotices = `-- name: CountMyNotices :one
SELECT COUNT(*)
FROM t_user_notice un
LEFT JOIN t_notice n ON un.notice_id = n.id
WHERE un.user_id = ?1
  AND un.is_deleted = 0
  AND n.is_deleted = 0
  AND n.publish_status = 1
  AND (?2 IS NULL OR n.title LIKE ?2)
  AND (?3  IS NULL OR n.type = ?3)
`

type CountMyNoticesParams struct {
	UserID string
	Title  interface{}
	Type   interface{}
}

func (q *Queries) CountMyNotices(ctx context.Context, arg CountMyNoticesParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countMyNotices, arg.UserID, arg.Title, arg.Type)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createUserNotice = `-- name: CreateUserNotice :exec
INSERT INTO t_user_notice (id, notice_id, user_id, is_read)
VALUES (?1, ?2, ?3, ?4)
`

type CreateUserNoticeParams struct {
	ID       string
	NoticeID string
	UserID   string
	IsRead   int32
}

func (q *Queries) CreateUserNotice(ctx context.Context, arg CreateUserNoticeParams) error {
	_, err := q.db.ExecContext(ctx, createUserNotice,
		arg.ID,
		arg.NoticeID,
		arg.UserID,
		arg.IsRead,
	)
	return err
}

const deleteUserNoticesByNoticeID = `-- name: DeleteUserNoticesByNoticeID :exec
DELETE FROM t_user_notice WHERE notice_id = ?1
`

func (q *Queries) DeleteUserNoticesByNoticeID(ctx context.Context, noticeID string) error {
	_, err := q.db.ExecContext(ctx, deleteUserNoticesByNoticeID, noticeID)
	return err
}

const deleteUserNoticesByNoticeIDs = `-- name: DeleteUserNoticesByNoticeIDs :exec
DELETE FROM t_user_notice WHERE notice_id IN (/*SLICE:notice_ids*/?)
`

func (q *Queries) DeleteUserNoticesByNoticeIDs(ctx context.Context, noticeIds []string) error {
	query := deleteUserNoticesByNoticeIDs
	var queryParams []interface{}
	if len(noticeIds) > 0 {
		for _, v := range noticeIds {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:notice_ids*/?", strings.Repeat(",?", len(noticeIds))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:notice_ids*/?", "NULL", 1)
	}
	_, err := q.db.ExecContext(ctx, query, queryParams...)
	return err
}

const listMyNotices = `-- name: ListMyNotices :many

SELECT un.id, un.notice_id, n.title, n.type, n.level, n.publish_time, un.is_read
FROM t_user_notice un
LEFT JOIN t_notice n ON un.notice_id = n.id
WHERE un.user_id = ?1
  AND un.is_deleted = 0
  AND n.is_deleted = 0
  AND n.publish_status = 1
  AND (?2 IS NULL OR n.title LIKE ?2)
  AND (?3  IS NULL OR n.type = ?3)
ORDER BY n.publish_time DESC
LIMIT  ?5
OFFSET ?4
`

type ListMyNoticesParams struct {
	UserID string
	Title  interface{}
	Type   interface{}
	Offset int64
	Limit  int64
}

type ListMyNoticesRow struct {
	ID          string
	NoticeID    string
	Title       *string
	Type        *int32
	Level       *string
	PublishTime *time.Time
	IsRead      int32
}

// user_notice.sql (SQLite dialect)
// Derived from queries/postgres/user_notice.sql. Every parameter is a named
// sqlc.arg/narg (see config.sql header). SQLite has no unnest(): the postgres
// BatchCreateUserNotices bulk insert is implemented in the sqlitestore adapter
// as a loop over CreateUserNotice.
// Published, non-deleted notices addressed to a user, newest first. Projects the
// fields the UI needs (UserNoticePageVO).
func (q *Queries) ListMyNotices(ctx context.Context, arg ListMyNoticesParams) ([]ListMyNoticesRow, error) {
	rows, err := q.db.QueryContext(ctx, listMyNotices,
		arg.UserID,
		arg.Title,
		arg.Type,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListMyNoticesRow{}
	for rows.Next() {
		var i ListMyNoticesRow
		if err := rows.Scan(
			&i.ID,
			&i.NoticeID,
			&i.Title,
			&i.Type,
			&i.Level,
			&i.PublishTime,
			&i.IsRead,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markAllUserNoticesRead = `-- name: MarkAllUserNoticesRead :exec
UPDATE t_user_notice SET is_read = 1, read_time = ?1, update_time = ?1
WHERE user_id = ?2 AND is_read = 0
`

type MarkAllUserNoticesReadParams struct {
	Now    *time.Time
	UserID string
}

func (q *Queries) MarkAllUserNoticesRead(ctx context.Context, arg MarkAllUserNoticesReadParams) error {
	_, err := q.db.ExecContext(ctx, markAllUserNoticesRead, arg.Now, arg.UserID)
	return err
}

const markUserNoticeRead = `-- name: MarkUserNoticeRead :exec
UPDATE t_user_notice SET is_read = 1, read_time = ?1, update_time = ?1
WHERE notice_id = ?2 AND user_id = ?3 AND is_read = 0
`

type MarkUserNoticeReadParams struct {
	Now      *time.Time
	NoticeID string
	UserID   string
}

func (q *Queries) MarkUserNoticeRead(ctx context.Context, arg MarkUserNoticeReadParams) error {
	_, err := q.db.ExecContext(ctx, markUserNoticeRead, arg.Now, arg.NoticeID, arg.UserID)
	return err
}
