// Code generated by tools/gen-store. DO NOT EDIT.
//
// Methods implemented by hand in manual.go (not generatable for this engine):
//   - BatchCreateRoleMenus
//   - BatchCreateUserNotices
//   - BatchCreateUserRoles
//   - CreateQueueTask (result type differs: SysTask vs int64)
//   - ListMenus
//   - UpdateQueueTask (result count differs)

package mysqlstore

import (
	"context"
	"errors"

	"database/sql"

	"github.com/top-system/light-admin/db/mysqlgen"
	"github.com/top-system/light-admin/db/store"
)

// Store adapts the sqlc-generated *mysqlgen.Queries to the engine-neutral
// store.Store interface.
type Store struct {
	q *mysqlgen.Queries
}

// New builds a Store over any mysqlgen.DBTX (a pool/handle or a transaction).
func New(db mysqlgen.DBTX) *Store {
	return &Store{q: mysqlgen.New(db)}
}

var _ store.Store = (*Store)(nil)

// translateErr maps the driver's sentinels to the engine-neutral store
// errors so business code never imports a database driver.
func translateErr(err error) error {
	if err != nil && errors.Is(err, sql.ErrNoRows) {
		return store.ErrNoRows
	}
	return err
}

func (s *Store) BatchDeleteDownloadTasks(ctx context.Context, ids []int64) error {
	return translateErr(s.q.BatchDeleteDownloadTasks(ctx, ids))
}

func (s *Store) BatchDeleteLogs(ctx context.Context, ids []string) error {
	return translateErr(s.q.BatchDeleteLogs(ctx, ids))
}

func (s *Store) BatchDeleteTasks(ctx context.Context, ids []int64) error {
	return translateErr(s.q.BatchDeleteTasks(ctx, ids))
}

func (s *Store) CountConfigs(ctx context.Context, keywords *string) (int64, error) {
	v, err := s.q.CountConfigs(ctx, mysqlgen.CountConfigsParams{
		Keywords: keywords,
	})
	return v, translateErr(err)
}

func (s *Store) CountConfigsByKey(ctx context.Context, arg store.CountConfigsByKeyParams) (int64, error) {
	v, err := s.q.CountConfigsByKey(ctx, mysqlgen.CountConfigsByKeyParams(arg))
	return v, translateErr(err)
}

func (s *Store) CountDictItems(ctx context.Context, arg store.CountDictItemsParams) (int64, error) {
	v, err := s.q.CountDictItems(ctx, mysqlgen.CountDictItemsParams(arg))
	return v, translateErr(err)
}

func (s *Store) CountDicts(ctx context.Context, keywords *string) (int64, error) {
	v, err := s.q.CountDicts(ctx, mysqlgen.CountDictsParams{
		Keywords: keywords,
	})
	return v, translateErr(err)
}

func (s *Store) CountDownloadTasks(ctx context.Context, arg store.CountDownloadTasksParams) (int64, error) {
	v, err := s.q.CountDownloadTasks(ctx, mysqlgen.CountDownloadTasksParams(arg))
	return v, translateErr(err)
}

func (s *Store) CountLogs(ctx context.Context, arg store.CountLogsParams) (int64, error) {
	v, err := s.q.CountLogs(ctx, mysqlgen.CountLogsParams(arg))
	return v, translateErr(err)
}

func (s *Store) CountMembers(ctx context.Context, arg store.CountMembersParams) (int64, error) {
	v, err := s.q.CountMembers(ctx, mysqlgen.CountMembersParams(arg))
	return v, translateErr(err)
}

func (s *Store) CountMembersByUsername(ctx context.Context, arg store.CountMembersByUsernameParams) (int64, error) {
	v, err := s.q.CountMembersByUsername(ctx, mysqlgen.CountMembersByUsernameParams(arg))
	return v, translateErr(err)
}

func (s *Store) CountMenus(ctx context.Context, arg store.CountMenusParams) (int64, error) {
	v, err := s.q.CountMenus(ctx, mysqlgen.CountMenusParams{
		Ids:            csvList(arg.Ids),
		Name:           arg.Name,
		ParentID:       arg.ParentID,
		PrefixTreePath: arg.PrefixTreePath,
		Type:           arg.Type,
		Visible:        arg.Visible,
		Keywords:       arg.Keywords,
	})
	return v, translateErr(err)
}

func (s *Store) CountMyNotices(ctx context.Context, arg store.CountMyNoticesParams) (int64, error) {
	v, err := s.q.CountMyNotices(ctx, mysqlgen.CountMyNoticesParams(arg))
	return v, translateErr(err)
}

func (s *Store) CountNotices(ctx context.Context, arg store.CountNoticesParams) (int64, error) {
	v, err := s.q.CountNotices(ctx, mysqlgen.CountNoticesParams(arg))
	return v, translateErr(err)
}

func (s *Store) CountRoles(ctx context.Context, arg store.CountRolesParams) (int64, error) {
	v, err := s.q.CountRoles(ctx, mysqlgen.CountRolesParams{
		Ids:        csvList(arg.Ids),
		Name:       arg.Name,
		Code:       arg.Code,
		UserID:     arg.UserID,
		QueryValue: arg.QueryValue,
		Status:     arg.Status,
	})
	return v, translateErr(err)
}

func (s *Store) CountTasks(ctx context.Context, arg store.CountTasksParams) (int64, error) {
	v, err := s.q.CountTasks(ctx, mysqlgen.CountTasksParams(arg))
	return v, translateErr(err)
}

func (s *Store) CountTenants(ctx context.Context, arg store.CountTenantsParams) (int64, error) {
	v, err := s.q.CountTenants(ctx, mysqlgen.CountTenantsParams(arg))
	return v, translateErr(err)
}

func (s *Store) CountUserRoles(ctx context.Context, arg store.CountUserRolesParams) (int64, error) {
	v, err := s.q.CountUserRoles(ctx, mysqlgen.CountUserRolesParams{
		UserID:  arg.UserID,
		UserIds: csvList(arg.UserIds),
	})
	return v, translateErr(err)
}

func (s *Store) CountUsers(ctx context.Context, arg store.CountUsersParams) (int64, error) {
	v, err := s.q.CountUsers(ctx, mysqlgen.CountUsersParams{
		Username:   arg.Username,
		Nickname:   arg.Nickname,
		Status:     arg.Status,
		DeptID:     arg.DeptID,
		Keywords:   arg.Keywords,
		CreateFrom: arg.CreateFrom,
		CreateTo:   arg.CreateTo,
		RoleIds:    csvList(arg.RoleIds),
	})
	return v, translateErr(err)
}

func (s *Store) CreateConfig(ctx context.Context, arg store.CreateConfigParams) error {
	return translateErr(s.q.CreateConfig(ctx, mysqlgen.CreateConfigParams(arg)))
}

func (s *Store) CreateDept(ctx context.Context, arg store.CreateDeptParams) error {
	return translateErr(s.q.CreateDept(ctx, mysqlgen.CreateDeptParams(arg)))
}

func (s *Store) CreateDict(ctx context.Context, arg store.CreateDictParams) error {
	return translateErr(s.q.CreateDict(ctx, mysqlgen.CreateDictParams(arg)))
}

func (s *Store) CreateDictItem(ctx context.Context, arg store.CreateDictItemParams) error {
	return translateErr(s.q.CreateDictItem(ctx, mysqlgen.CreateDictItemParams(arg)))
}

func (s *Store) CreateDownloadTask(ctx context.Context, arg store.CreateDownloadTaskParams) (int64, error) {
	v, err := s.q.CreateDownloadTask(ctx, mysqlgen.CreateDownloadTaskParams(arg))
	return v, translateErr(err)
}

func (s *Store) CreateLog(ctx context.Context, arg store.CreateLogParams) error {
	return translateErr(s.q.CreateLog(ctx, mysqlgen.CreateLogParams(arg)))
}

func (s *Store) CreateMember(ctx context.Context, arg store.CreateMemberParams) error {
	return translateErr(s.q.CreateMember(ctx, mysqlgen.CreateMemberParams(arg)))
}

func (s *Store) CreateMenu(ctx context.Context, arg store.CreateMenuParams) error {
	return translateErr(s.q.CreateMenu(ctx, mysqlgen.CreateMenuParams(arg)))
}

func (s *Store) CreateNotice(ctx context.Context, arg store.CreateNoticeParams) error {
	return translateErr(s.q.CreateNotice(ctx, mysqlgen.CreateNoticeParams(arg)))
}

func (s *Store) CreateRole(ctx context.Context, arg store.CreateRoleParams) error {
	return translateErr(s.q.CreateRole(ctx, mysqlgen.CreateRoleParams(arg)))
}

func (s *Store) CreateTenant(ctx context.Context, arg store.CreateTenantParams) error {
	return translateErr(s.q.CreateTenant(ctx, mysqlgen.CreateTenantParams(arg)))
}

func (s *Store) CreateUser(ctx context.Context, arg store.CreateUserParams) error {
	return translateErr(s.q.CreateUser(ctx, mysqlgen.CreateUserParams(arg)))
}

func (s *Store) CreateUserNotice(ctx context.Context, arg store.CreateUserNoticeParams) error {
	return translateErr(s.q.CreateUserNotice(ctx, mysqlgen.CreateUserNoticeParams(arg)))
}

func (s *Store) CreateUserRole(ctx context.Context, arg store.CreateUserRoleParams) error {
	return translateErr(s.q.CreateUserRole(ctx, mysqlgen.CreateUserRoleParams(arg)))
}

func (s *Store) DeleteDownloadTask(ctx context.Context, id int64) error {
	return translateErr(s.q.DeleteDownloadTask(ctx, id))
}

func (s *Store) DeleteLog(ctx context.Context, id string) error {
	return translateErr(s.q.DeleteLog(ctx, id))
}

func (s *Store) DeleteMenu(ctx context.Context, id string) error {
	return translateErr(s.q.DeleteMenu(ctx, id))
}

func (s *Store) DeleteRoleMenusByMenuID(ctx context.Context, menuID string) error {
	return translateErr(s.q.DeleteRoleMenusByMenuID(ctx, menuID))
}

func (s *Store) DeleteRoleMenusByRoleID(ctx context.Context, roleID string) error {
	return translateErr(s.q.DeleteRoleMenusByRoleID(ctx, roleID))
}

func (s *Store) DeleteTask(ctx context.Context, id int64) error {
	return translateErr(s.q.DeleteTask(ctx, id))
}

func (s *Store) DeleteUserNoticesByNoticeID(ctx context.Context, noticeID string) error {
	return translateErr(s.q.DeleteUserNoticesByNoticeID(ctx, noticeID))
}

func (s *Store) DeleteUserNoticesByNoticeIDs(ctx context.Context, noticeIds []string) error {
	return translateErr(s.q.DeleteUserNoticesByNoticeIDs(ctx, noticeIds))
}

func (s *Store) DeleteUserRolesByRoleID(ctx context.Context, roleID string) error {
	return translateErr(s.q.DeleteUserRolesByRoleID(ctx, roleID))
}

func (s *Store) DeleteUserRolesByUserID(ctx context.Context, userID string) error {
	return translateErr(s.q.DeleteUserRolesByUserID(ctx, userID))
}

func (s *Store) GetConfig(ctx context.Context, id string) (store.TConfig, error) {
	row, err := s.q.GetConfig(ctx, id)
	return store.TConfig(row), translateErr(err)
}

func (s *Store) GetConfigByKey(ctx context.Context, configKey string) (store.TConfig, error) {
	row, err := s.q.GetConfigByKey(ctx, configKey)
	return store.TConfig(row), translateErr(err)
}

func (s *Store) GetDept(ctx context.Context, id string) (store.TDept, error) {
	row, err := s.q.GetDept(ctx, id)
	return store.TDept(row), translateErr(err)
}

func (s *Store) GetDeptByCode(ctx context.Context, arg store.GetDeptByCodeParams) (store.TDept, error) {
	row, err := s.q.GetDeptByCode(ctx, mysqlgen.GetDeptByCodeParams(arg))
	return store.TDept(row), translateErr(err)
}

func (s *Store) GetDict(ctx context.Context, id string) (store.TDict, error) {
	row, err := s.q.GetDict(ctx, id)
	return store.TDict(row), translateErr(err)
}

func (s *Store) GetDictByCode(ctx context.Context, arg store.GetDictByCodeParams) (store.TDict, error) {
	row, err := s.q.GetDictByCode(ctx, mysqlgen.GetDictByCodeParams(arg))
	return store.TDict(row), translateErr(err)
}

func (s *Store) GetDictItem(ctx context.Context, id string) (store.TDictItem, error) {
	row, err := s.q.GetDictItem(ctx, id)
	return store.TDictItem(row), translateErr(err)
}

func (s *Store) GetDownloadTask(ctx context.Context, id int64) (store.SysDownloadTask, error) {
	row, err := s.q.GetDownloadTask(ctx, id)
	return store.SysDownloadTask(row), translateErr(err)
}

func (s *Store) GetDownloadTaskByQueueTaskID(ctx context.Context, queueTaskID int64) (store.SysDownloadTask, error) {
	row, err := s.q.GetDownloadTaskByQueueTaskID(ctx, queueTaskID)
	return store.SysDownloadTask(row), translateErr(err)
}

func (s *Store) GetDownloadTaskByTaskID(ctx context.Context, taskID string) (store.SysDownloadTask, error) {
	row, err := s.q.GetDownloadTaskByTaskID(ctx, taskID)
	return store.SysDownloadTask(row), translateErr(err)
}

func (s *Store) GetLog(ctx context.Context, id string) (store.SysLog, error) {
	row, err := s.q.GetLog(ctx, id)
	return store.SysLog(row), translateErr(err)
}

func (s *Store) GetMemberByID(ctx context.Context, arg store.GetMemberByIDParams) (store.TMember, error) {
	row, err := s.q.GetMemberByID(ctx, mysqlgen.GetMemberByIDParams(arg))
	return store.TMember(row), translateErr(err)
}

func (s *Store) GetMemberByUsername(ctx context.Context, arg store.GetMemberByUsernameParams) (store.TMember, error) {
	row, err := s.q.GetMemberByUsername(ctx, mysqlgen.GetMemberByUsernameParams(arg))
	return store.TMember(row), translateErr(err)
}

func (s *Store) GetMenu(ctx context.Context, id string) (store.TMenu, error) {
	row, err := s.q.GetMenu(ctx, id)
	return store.TMenu(row), translateErr(err)
}

func (s *Store) GetMenuIDsByRoleID(ctx context.Context, roleID string) ([]string, error) {
	v, err := s.q.GetMenuIDsByRoleID(ctx, roleID)
	return v, translateErr(err)
}

func (s *Store) GetNotice(ctx context.Context, id string) (store.TNotice, error) {
	row, err := s.q.GetNotice(ctx, id)
	return store.TNotice(row), translateErr(err)
}

func (s *Store) GetQueueTask(ctx context.Context, id int64) (store.SysTask, error) {
	row, err := s.q.GetQueueTask(ctx, id)
	return store.SysTask(row), translateErr(err)
}

func (s *Store) GetRole(ctx context.Context, id string) (store.TRole, error) {
	row, err := s.q.GetRole(ctx, id)
	return store.TRole(row), translateErr(err)
}

func (s *Store) GetRoleByCode(ctx context.Context, code string) (store.TRole, error) {
	row, err := s.q.GetRoleByCode(ctx, code)
	return store.TRole(row), translateErr(err)
}

func (s *Store) GetRoleIDsByUserID(ctx context.Context, userID string) ([]string, error) {
	v, err := s.q.GetRoleIDsByUserID(ctx, userID)
	return v, translateErr(err)
}

func (s *Store) GetTask(ctx context.Context, id int64) (store.SysTask, error) {
	row, err := s.q.GetTask(ctx, id)
	return store.SysTask(row), translateErr(err)
}

func (s *Store) GetTenant(ctx context.Context, id string) (store.TTenant, error) {
	row, err := s.q.GetTenant(ctx, id)
	return store.TTenant(row), translateErr(err)
}

func (s *Store) GetTenantByCode(ctx context.Context, code string) (store.TTenant, error) {
	row, err := s.q.GetTenantByCode(ctx, code)
	return store.TTenant(row), translateErr(err)
}

func (s *Store) GetUser(ctx context.Context, id string) (store.TUser, error) {
	row, err := s.q.GetUser(ctx, id)
	return store.TUser(row), translateErr(err)
}

func (s *Store) GetUserByUsername(ctx context.Context, username string) (store.TUser, error) {
	row, err := s.q.GetUserByUsername(ctx, username)
	return store.TUser(row), translateErr(err)
}

func (s *Store) GetUserIDsByRoleID(ctx context.Context, roleID string) ([]string, error) {
	v, err := s.q.GetUserIDsByRoleID(ctx, roleID)
	return v, translateErr(err)
}

func (s *Store) ListActiveDownloadTasks(ctx context.Context) ([]store.ListActiveDownloadTasksRow, error) {
	rows, err := s.q.ListActiveDownloadTasks(ctx)
	if err != nil {
		return nil, translateErr(err)
	}
	out := make([]store.ListActiveDownloadTasksRow, len(rows))
	for i := range rows {
		out[i] = store.ListActiveDownloadTasksRow(rows[i])
	}
	return out, nil
}

func (s *Store) ListAllConfigs(ctx context.Context) ([]store.TConfig, error) {
	rows, err := s.q.ListAllConfigs(ctx)
	if err != nil {
		return nil, translateErr(err)
	}
	out := make([]store.TConfig, len(rows))
	for i := range rows {
		out[i] = store.TConfig(rows[i])
	}
	return out, nil
}

func (s *Store) ListButtonPermsByRoleIDs(ctx context.Context, roleIds []string) ([]string, error) {
	v, err := s.q.ListButtonPermsByRoleIDs(ctx, roleIds)
	return v, translateErr(err)
}

func (s *Store) ListConfigs(ctx context.Context, arg store.ListConfigsParams) ([]store.TConfig, error) {
	rows, err := s.q.ListConfigs(ctx, mysqlgen.ListConfigsParams{
		Keywords: arg.Keywords,
		Limit:    limitOrAll(arg.Limit),
		Offset:   offsetOrZero(arg.Offset),
	})
	if err != nil {
		return nil, translateErr(err)
	}
	out := make([]store.TConfig, len(rows))
	for i := range rows {
		out[i] = store.TConfig(rows[i])
	}
	return out, nil
}

func (s *Store) ListDepts(ctx context.Context, arg store.ListDeptsParams) ([]store.TDept, error) {
	rows, err := s.q.ListDepts(ctx, mysqlgen.ListDeptsParams(arg))
	if err != nil {
		return nil, translateErr(err)
	}
	out := make([]store.TDept, len(rows))
	for i := range rows {
		out[i] = store.TDept(rows[i])
	}
	return out, nil
}

func (s *Store) ListDeptsByIDs(ctx context.Context, ids []string) ([]store.TDept, error) {
	rows, err := s.q.ListDeptsByIDs(ctx, ids)
	if err != nil {
		return nil, translateErr(err)
	}
	out := make([]store.TDept, len(rows))
	for i := range rows {
		out[i] = store.TDept(rows[i])
	}
	return out, nil
}

func (s *Store) ListDictItems(ctx context.Context, arg store.ListDictItemsParams) ([]store.TDictItem, error) {
	rows, err := s.q.ListDictItems(ctx, mysqlgen.ListDictItemsParams{
		DictCode: arg.DictCode,
		Keywords: arg.Keywords,
		Limit:    limitOrAll(arg.Limit),
		Offset:   offsetOrZero(arg.Offset),
	})
	if err != nil {
		return nil, translateErr(err)
	}
	out := make([]store.TDictItem, len(rows))
	for i := range rows {
		out[i] = store.TDictItem(rows[i])
	}
	return out, nil
}

func (s *Store) ListDictItemsByDictCode(ctx context.Context, dictCode string) ([]store.TDictItem, error) {
	rows, err := s.q.ListDictItemsByDictCode(ctx, dictCode)
	if err != nil {
		return nil, translateErr(err)
	}
	out := make([]store.TDictItem, len(rows))
	for i := range rows {
		out[i] = store.TDictItem(rows[i])
	}
	return out, nil
}

func (s *Store) ListDicts(ctx context.Context, arg store.ListDictsParams) ([]store.TDict, error) {
	rows, err := s.q.ListDicts(ctx, mysqlgen.ListDictsParams{
		Keywords: arg.Keywords,
		Limit:    limitOrAll(arg.Limit),
		Offset:   offsetOrZero(arg.Offset),
	})
	if err != nil {
		return nil, translateErr(err)
	}
	out := make([]store.TDict, len(rows))
	for i := range rows {
		out[i] = store.TDict(rows[i])
	}
	return out, nil
}

func (s *Store) ListDictsByIDs(ctx context.Context, ids []string) ([]store.TDict, error) {
	rows, err := s.q.ListDictsByIDs(ctx, ids)
	if err != nil {
		return nil, translateErr(err)
	}
	out := make([]store.TDict, len(rows))
	for i := range rows {
		out[i] = store.TDict(rows[i])
	}
	return out, nil
}

func (s *Store) ListDownloadStatusCounts(ctx context.Context) ([]store.ListDownloadStatusCountsRow, error) {
	rows, err := s.q.ListDownloadStatusCounts(ctx)
	if err != nil {
		return nil, translateErr(err)
	}
	out := make([]store.ListDownloadStatusCountsRow, len(rows))
	for i := range rows {
		out[i] = store.ListDownloadStatusCountsRow(rows[i])
	}
	return out, nil
}

func (s *Store) ListDownloadTasks(ctx context.Context, arg store.ListDownloadTasksParams) ([]store.SysDownloadTask, error) {
	rows, err := s.q.ListDownloadTasks(ctx, mysqlgen.ListDownloadTasksParams{
		Status:     arg.Status,
		Downloader: arg.Downloader,
		Keywords:   arg.Keywords,
		CreateFrom: arg.CreateFrom,
		CreateTo:   arg.CreateTo,
		Limit:      limitOrAll(arg.Limit),
		Offset:     offsetOrZero(arg.Offset),
	})
	if err != nil {
		return nil, translateErr(err)
	}
	out := make([]store.SysDownloadTask, len(rows))
	for i := range rows {
		out[i] = store.SysDownloadTask(rows[i])
	}
	return out, nil
}

func (s *Store) ListEnabledDepts(ctx context.Context) ([]store.TDept, error) {
	rows, err := s.q.ListEnabledDepts(ctx)
	if err != nil {
		return nil, translateErr(err)
	}
	out := make([]store.TDept, len(rows))
	for i := range rows {
		out[i] = store.TDept(rows[i])
	}
	return out, nil
}

func (s *Store) ListEnabledDicts(ctx context.Context) ([]store.TDict, error) {
	rows, err := s.q.ListEnabledDicts(ctx)
	if err != nil {
		return nil, translateErr(err)
	}
	out := make([]store.TDict, len(rows))
	for i := range rows {
		out[i] = store.TDict(rows[i])
	}
	return out, nil
}

func (s *Store) ListLogs(ctx context.Context, arg store.ListLogsParams) ([]store.SysLog, error) {
	rows, err := s.q.ListLogs(ctx, mysqlgen.ListLogsParams{
		Module:     arg.Module,
		Keywords:   arg.Keywords,
		CreateFrom: arg.CreateFrom,
		CreateTo:   arg.CreateTo,
		Limit:      limitOrAll(arg.Limit),
		Offset:     offsetOrZero(arg.Offset),
	})
	if err != nil {
		return nil, translateErr(err)
	}
	out := make([]store.SysLog, len(rows))
	for i := range rows {
		out[i] = store.SysLog(rows[i])
	}
	return out, nil
}

func (s *Store) ListMembers(ctx context.Context, arg store.ListMembersParams) ([]store.TMember, error) {
	rows, err := s.q.ListMembers(ctx, mysqlgen.ListMembersParams{
		TenantID: arg.TenantID,
		Keywords: arg.Keywords,
		Status:   arg.Status,
		Limit:    limitOrAll(arg.Limit),
		Offset:   offsetOrZero(arg.Offset),
	})
	if err != nil {
		return nil, translateErr(err)
	}
	out := make([]store.TMember, len(rows))
	for i := range rows {
		out[i] = store.TMember(rows[i])
	}
	return out, nil
}

func (s *Store) ListMenusByRoleIDs(ctx context.Context, roleIds []string) ([]store.TMenu, error) {
	rows, err := s.q.ListMenusByRoleIDs(ctx, roleIds)
	if err != nil {
		return nil, translateErr(err)
	}
	out := make([]store.TMenu, len(rows))
	for i := range rows {
		out[i] = store.TMenu(rows[i])
	}
	return out, nil
}

func (s *Store) ListMyNotices(ctx context.Context, arg store.ListMyNoticesParams) ([]store.ListMyNoticesRow, error) {
	rows, err := s.q.ListMyNotices(ctx, mysqlgen.ListMyNoticesParams{
		UserID: arg.UserID,
		Title:  arg.Title,
		Type:   arg.Type,
		Limit:  limitOrAll(arg.Limit),
		Offset: offsetOrZero(arg.Offset),
	})
	if err != nil {
		return nil, translateErr(err)
	}
	out := make([]store.ListMyNoticesRow, len(rows))
	for i := range rows {
		out[i] = store.ListMyNoticesRow(rows[i])
	}
	return out, nil
}

func (s *Store) ListNotices(ctx context.Context, arg store.ListNoticesParams) ([]store.TNotice, error) {
	rows, err := s.q.ListNotices(ctx, mysqlgen.ListNoticesParams{
		Title:         arg.Title,
		Type:          arg.Type,
		PublishStatus: arg.PublishStatus,
		Limit:         limitOrAll(arg.Limit),
		Offset:        offsetOrZero(arg.Offset),
	})
	if err != nil {
		return nil, translateErr(err)
	}
	out := make([]store.TNotice, len(rows))
	for i := range rows {
		out[i] = store.TNotice(rows[i])
	}
	return out, nil
}

func (s *Store) ListPendingQueueTasks(ctx context.Context, types []string) ([]store.SysTask, error) {
	rows, err := s.q.ListPendingQueueTasks(ctx, mysqlgen.ListPendingQueueTasksParams{
		Types: csvList(types),
	})
	if err != nil {
		return nil, translateErr(err)
	}
	out := make([]store.SysTask, len(rows))
	for i := range rows {
		out[i] = store.SysTask(rows[i])
	}
	return out, nil
}

func (s *Store) ListRoles(ctx context.Context, arg store.ListRolesParams) ([]store.TRole, error) {
	rows, err := s.q.ListRoles(ctx, mysqlgen.ListRolesParams{
		Ids:        csvList(arg.Ids),
		Name:       arg.Name,
		Code:       arg.Code,
		UserID:     arg.UserID,
		QueryValue: arg.QueryValue,
		Status:     arg.Status,
		Limit:      limitOrAll(arg.Limit),
		Offset:     offsetOrZero(arg.Offset),
	})
	if err != nil {
		return nil, translateErr(err)
	}
	out := make([]store.TRole, len(rows))
	for i := range rows {
		out[i] = store.TRole(rows[i])
	}
	return out, nil
}

func (s *Store) ListTaskStatusCounts(ctx context.Context) ([]store.ListTaskStatusCountsRow, error) {
	rows, err := s.q.ListTaskStatusCounts(ctx)
	if err != nil {
		return nil, translateErr(err)
	}
	out := make([]store.ListTaskStatusCountsRow, len(rows))
	for i := range rows {
		out[i] = store.ListTaskStatusCountsRow(rows[i])
	}
	return out, nil
}

func (s *Store) ListTaskTypes(ctx context.Context) ([]string, error) {
	v, err := s.q.ListTaskTypes(ctx)
	return v, translateErr(err)
}

func (s *Store) ListTasks(ctx context.Context, arg store.ListTasksParams) ([]store.SysTask, error) {
	rows, err := s.q.ListTasks(ctx, mysqlgen.ListTasksParams{
		Type:          arg.Type,
		Status:        arg.Status,
		CorrelationID: arg.CorrelationID,
		Keywords:      arg.Keywords,
		CreateFrom:    arg.CreateFrom,
		CreateTo:      arg.CreateTo,
		Limit:         limitOrAll(arg.Limit),
		Offset:        offsetOrZero(arg.Offset),
	})
	if err != nil {
		return nil, translateErr(err)
	}
	out := make([]store.SysTask, len(rows))
	for i := range rows {
		out[i] = store.SysTask(rows[i])
	}
	return out, nil
}

func (s *Store) ListTenants(ctx context.Context, arg store.ListTenantsParams) ([]store.TTenant, error) {
	rows, err := s.q.ListTenants(ctx, mysqlgen.ListTenantsParams{
		Keywords: arg.Keywords,
		Status:   arg.Status,
		Limit:    limitOrAll(arg.Limit),
		Offset:   offsetOrZero(arg.Offset),
	})
	if err != nil {
		return nil, translateErr(err)
	}
	out := make([]store.TTenant, len(rows))
	for i := range rows {
		out[i] = store.TTenant(rows[i])
	}
	return out, nil
}

func (s *Store) ListUserRoles(ctx context.Context, arg store.ListUserRolesParams) ([]store.TUserRole, error) {
	rows, err := s.q.ListUserRoles(ctx, mysqlgen.ListUserRolesParams{
		UserID:  arg.UserID,
		UserIds: csvList(arg.UserIds),
		Limit:   limitOrAll(arg.Limit),
		Offset:  offsetOrZero(arg.Offset),
	})
	if err != nil {
		return nil, translateErr(err)
	}
	out := make([]store.TUserRole, len(rows))
	for i := range rows {
		out[i] = store.TUserRole(rows[i])
	}
	return out, nil
}

func (s *Store) ListUsers(ctx context.Context, arg store.ListUsersParams) ([]store.TUser, error) {
	rows, err := s.q.ListUsers(ctx, mysqlgen.ListUsersParams{
		Username:   arg.Username,
		Nickname:   arg.Nickname,
		Status:     arg.Status,
		DeptID:     arg.DeptID,
		Keywords:   arg.Keywords,
		CreateFrom: arg.CreateFrom,
		CreateTo:   arg.CreateTo,
		RoleIds:    csvList(arg.RoleIds),
		Limit:      limitOrAll(arg.Limit),
		Offset:     offsetOrZero(arg.Offset),
	})
	if err != nil {
		return nil, translateErr(err)
	}
	out := make([]store.TUser, len(rows))
	for i := range rows {
		out[i] = store.TUser(rows[i])
	}
	return out, nil
}

func (s *Store) MarkAllUserNoticesRead(ctx context.Context, arg store.MarkAllUserNoticesReadParams) error {
	return translateErr(s.q.MarkAllUserNoticesRead(ctx, mysqlgen.MarkAllUserNoticesReadParams{
		Now:    &arg.Now,
		UserID: arg.UserID,
	}))
}

func (s *Store) MarkUserNoticeRead(ctx context.Context, arg store.MarkUserNoticeReadParams) error {
	return translateErr(s.q.MarkUserNoticeRead(ctx, mysqlgen.MarkUserNoticeReadParams{
		Now:      &arg.Now,
		NoticeID: arg.NoticeID,
		UserID:   arg.UserID,
	}))
}

func (s *Store) SoftDeleteConfig(ctx context.Context, arg store.SoftDeleteConfigParams) error {
	return translateErr(s.q.SoftDeleteConfig(ctx, mysqlgen.SoftDeleteConfigParams{
		UpdateBy: arg.UpdateBy,
		Now:      arg.Now,
		ID:       arg.ID,
	}))
}

func (s *Store) SoftDeleteDept(ctx context.Context, arg store.SoftDeleteDeptParams) error {
	return translateErr(s.q.SoftDeleteDept(ctx, mysqlgen.SoftDeleteDeptParams{
		UpdateBy: arg.UpdateBy,
		Now:      arg.Now,
		ID:       arg.ID,
	}))
}

func (s *Store) SoftDeleteDeptByTreePath(ctx context.Context, arg store.SoftDeleteDeptByTreePathParams) error {
	return translateErr(s.q.SoftDeleteDeptByTreePath(ctx, mysqlgen.SoftDeleteDeptByTreePathParams(arg)))
}

func (s *Store) SoftDeleteDict(ctx context.Context, arg store.SoftDeleteDictParams) error {
	return translateErr(s.q.SoftDeleteDict(ctx, mysqlgen.SoftDeleteDictParams{
		UpdateBy: arg.UpdateBy,
		Now:      arg.Now,
		ID:       arg.ID,
	}))
}

func (s *Store) SoftDeleteDictItem(ctx context.Context, arg store.SoftDeleteDictItemParams) error {
	return translateErr(s.q.SoftDeleteDictItem(ctx, mysqlgen.SoftDeleteDictItemParams{
		UpdateBy: arg.UpdateBy,
		Now:      arg.Now,
		ID:       arg.ID,
	}))
}

func (s *Store) SoftDeleteDictItemsByDictCodes(ctx context.Context, arg store.SoftDeleteDictItemsByDictCodesParams) error {
	return translateErr(s.q.SoftDeleteDictItemsByDictCodes(ctx, mysqlgen.SoftDeleteDictItemsByDictCodesParams(arg)))
}

func (s *Store) SoftDeleteDictItemsByIDs(ctx context.Context, arg store.SoftDeleteDictItemsByIDsParams) error {
	return translateErr(s.q.SoftDeleteDictItemsByIDs(ctx, mysqlgen.SoftDeleteDictItemsByIDsParams(arg)))
}

func (s *Store) SoftDeleteDictsByIDs(ctx context.Context, arg store.SoftDeleteDictsByIDsParams) error {
	return translateErr(s.q.SoftDeleteDictsByIDs(ctx, mysqlgen.SoftDeleteDictsByIDsParams(arg)))
}

func (s *Store) SoftDeleteNoticesByIDs(ctx context.Context, arg store.SoftDeleteNoticesByIDsParams) error {
	return translateErr(s.q.SoftDeleteNoticesByIDs(ctx, mysqlgen.SoftDeleteNoticesByIDsParams(arg)))
}

func (s *Store) SoftDeleteQueueTask(ctx context.Context, arg store.SoftDeleteQueueTaskParams) error {
	return translateErr(s.q.SoftDeleteQueueTask(ctx, mysqlgen.SoftDeleteQueueTaskParams{
		Now: &arg.Now,
		ID:  arg.ID,
	}))
}

func (s *Store) SoftDeleteRole(ctx context.Context, arg store.SoftDeleteRoleParams) error {
	return translateErr(s.q.SoftDeleteRole(ctx, mysqlgen.SoftDeleteRoleParams{
		Now: arg.Now,
		ID:  arg.ID,
	}))
}

func (s *Store) SoftDeleteTenant(ctx context.Context, arg store.SoftDeleteTenantParams) error {
	return translateErr(s.q.SoftDeleteTenant(ctx, mysqlgen.SoftDeleteTenantParams{
		Now: arg.Now,
		ID:  arg.ID,
	}))
}

func (s *Store) SoftDeleteUser(ctx context.Context, arg store.SoftDeleteUserParams) error {
	return translateErr(s.q.SoftDeleteUser(ctx, mysqlgen.SoftDeleteUserParams{
		Now: arg.Now,
		ID:  arg.ID,
	}))
}

func (s *Store) UpdateConfig(ctx context.Context, arg store.UpdateConfigParams) error {
	return translateErr(s.q.UpdateConfig(ctx, mysqlgen.UpdateConfigParams{
		ConfigName:  arg.ConfigName,
		ConfigKey:   arg.ConfigKey,
		ConfigValue: arg.ConfigValue,
		Remark:      arg.Remark,
		UpdateBy:    arg.UpdateBy,
		Now:         arg.Now,
		ID:          arg.ID,
	}))
}

func (s *Store) UpdateDept(ctx context.Context, arg store.UpdateDeptParams) error {
	return translateErr(s.q.UpdateDept(ctx, mysqlgen.UpdateDeptParams{
		Name:     arg.Name,
		Code:     arg.Code,
		ParentID: arg.ParentID,
		TreePath: arg.TreePath,
		Sort:     arg.Sort,
		Status:   arg.Status,
		UpdateBy: arg.UpdateBy,
		Now:      arg.Now,
		ID:       arg.ID,
	}))
}

func (s *Store) UpdateDict(ctx context.Context, arg store.UpdateDictParams) error {
	return translateErr(s.q.UpdateDict(ctx, mysqlgen.UpdateDictParams{
		DictCode: arg.DictCode,
		Name:     arg.Name,
		Status:   arg.Status,
		Remark:   arg.Remark,
		UpdateBy: arg.UpdateBy,
		Now:      arg.Now,
		ID:       arg.ID,
	}))
}

func (s *Store) UpdateDictItem(ctx context.Context, arg store.UpdateDictItemParams) error {
	return translateErr(s.q.UpdateDictItem(ctx, mysqlgen.UpdateDictItemParams{
		DictCode: arg.DictCode,
		Label:    arg.Label,
		Value:    arg.Value,
		TagType:  arg.TagType,
		Sort:     arg.Sort,
		Status:   arg.Status,
		Remark:   arg.Remark,
		UpdateBy: arg.UpdateBy,
		Now:      arg.Now,
		ID:       arg.ID,
	}))
}

func (s *Store) UpdateDictItemsDictCode(ctx context.Context, arg store.UpdateDictItemsDictCodeParams) error {
	return translateErr(s.q.UpdateDictItemsDictCode(ctx, mysqlgen.UpdateDictItemsDictCodeParams(arg)))
}

func (s *Store) UpdateDownloadTask(ctx context.Context, arg store.UpdateDownloadTaskParams) error {
	return translateErr(s.q.UpdateDownloadTask(ctx, mysqlgen.UpdateDownloadTaskParams{
		QueueTaskID:   arg.QueueTaskID,
		TaskID:        arg.TaskID,
		Hash:          arg.Hash,
		Name:          arg.Name,
		Url:           arg.Url,
		Downloader:    arg.Downloader,
		Status:        arg.Status,
		Total:         arg.Total,
		Downloaded:    arg.Downloaded,
		DownloadSpeed: arg.DownloadSpeed,
		Uploaded:      arg.Uploaded,
		UploadSpeed:   arg.UploadSpeed,
		SavePath:      arg.SavePath,
		ErrorMessage:  arg.ErrorMessage,
		OwnerID:       arg.OwnerID,
		Now:           arg.Now,
		ID:            arg.ID,
	}))
}

func (s *Store) UpdateDownloadTaskFromDownloader(ctx context.Context, arg store.UpdateDownloadTaskFromDownloaderParams) error {
	return translateErr(s.q.UpdateDownloadTaskFromDownloader(ctx, mysqlgen.UpdateDownloadTaskFromDownloaderParams(arg)))
}

func (s *Store) UpdateDownloadTaskStatus(ctx context.Context, arg store.UpdateDownloadTaskStatusParams) error {
	return translateErr(s.q.UpdateDownloadTaskStatus(ctx, mysqlgen.UpdateDownloadTaskStatusParams{
		Status:        arg.Status,
		Downloaded:    arg.Downloaded,
		Total:         arg.Total,
		DownloadSpeed: arg.DownloadSpeed,
		Uploaded:      arg.Uploaded,
		UploadSpeed:   arg.UploadSpeed,
		ErrorMessage:  arg.ErrorMessage,
		Now:           arg.Now,
		ID:            arg.ID,
	}))
}

func (s *Store) UpdateMemberLoginInfo(ctx context.Context, arg store.UpdateMemberLoginInfoParams) error {
	return translateErr(s.q.UpdateMemberLoginInfo(ctx, mysqlgen.UpdateMemberLoginInfoParams{
		LastLoginIp: arg.LastLoginIp,
		Now:         &arg.Now,
		TenantID:    arg.TenantID,
		ID:          arg.ID,
	}))
}

func (s *Store) UpdateMemberPassword(ctx context.Context, arg store.UpdateMemberPasswordParams) error {
	return translateErr(s.q.UpdateMemberPassword(ctx, mysqlgen.UpdateMemberPasswordParams{
		Password: arg.Password,
		Now:      arg.Now,
		TenantID: arg.TenantID,
		ID:       arg.ID,
	}))
}

func (s *Store) UpdateMemberProfile(ctx context.Context, arg store.UpdateMemberProfileParams) error {
	return translateErr(s.q.UpdateMemberProfile(ctx, mysqlgen.UpdateMemberProfileParams(arg)))
}

func (s *Store) UpdateMemberStatus(ctx context.Context, arg store.UpdateMemberStatusParams) error {
	return translateErr(s.q.UpdateMemberStatus(ctx, mysqlgen.UpdateMemberStatusParams{
		Status:   arg.Status,
		Now:      arg.Now,
		TenantID: arg.TenantID,
		ID:       arg.ID,
	}))
}

func (s *Store) UpdateMenu(ctx context.Context, arg store.UpdateMenuParams) error {
	return translateErr(s.q.UpdateMenu(ctx, mysqlgen.UpdateMenuParams{
		ParentID:   arg.ParentID,
		TreePath:   arg.TreePath,
		Name:       arg.Name,
		Type:       arg.Type,
		RouteName:  arg.RouteName,
		RoutePath:  arg.RoutePath,
		Component:  arg.Component,
		Perm:       arg.Perm,
		AlwaysShow: arg.AlwaysShow,
		KeepAlive:  arg.KeepAlive,
		Visible:    arg.Visible,
		Sort:       arg.Sort,
		Icon:       arg.Icon,
		Redirect:   arg.Redirect,
		Params:     arg.Params,
		Now:        arg.Now,
		ID:         arg.ID,
	}))
}

func (s *Store) UpdateMenuTreePath(ctx context.Context, arg store.UpdateMenuTreePathParams) error {
	return translateErr(s.q.UpdateMenuTreePath(ctx, mysqlgen.UpdateMenuTreePathParams{
		TreePath: arg.TreePath,
		Now:      arg.Now,
		ID:       arg.ID,
	}))
}

func (s *Store) UpdateMenuVisible(ctx context.Context, arg store.UpdateMenuVisibleParams) error {
	return translateErr(s.q.UpdateMenuVisible(ctx, mysqlgen.UpdateMenuVisibleParams{
		Visible: arg.Visible,
		Now:     arg.Now,
		ID:      arg.ID,
	}))
}

func (s *Store) UpdateNotice(ctx context.Context, arg store.UpdateNoticeParams) error {
	return translateErr(s.q.UpdateNotice(ctx, mysqlgen.UpdateNoticeParams{
		Title:         arg.Title,
		Content:       arg.Content,
		Type:          arg.Type,
		Level:         arg.Level,
		TargetType:    arg.TargetType,
		TargetUserIds: arg.TargetUserIds,
		UpdateBy:      arg.UpdateBy,
		Now:           arg.Now,
		ID:            arg.ID,
	}))
}

func (s *Store) UpdateNoticeStatus(ctx context.Context, arg store.UpdateNoticeStatusParams) error {
	return translateErr(s.q.UpdateNoticeStatus(ctx, mysqlgen.UpdateNoticeStatusParams(arg)))
}

func (s *Store) UpdateRole(ctx context.Context, arg store.UpdateRoleParams) error {
	return translateErr(s.q.UpdateRole(ctx, mysqlgen.UpdateRoleParams{
		Name:      arg.Name,
		Code:      arg.Code,
		Sort:      arg.Sort,
		Status:    arg.Status,
		DataScope: arg.DataScope,
		UpdateBy:  arg.UpdateBy,
		Now:       arg.Now,
		ID:        arg.ID,
	}))
}

func (s *Store) UpdateRoleStatus(ctx context.Context, arg store.UpdateRoleStatusParams) error {
	return translateErr(s.q.UpdateRoleStatus(ctx, mysqlgen.UpdateRoleStatusParams{
		Status: arg.Status,
		Now:    arg.Now,
		ID:     arg.ID,
	}))
}

func (s *Store) UpdateTenant(ctx context.Context, arg store.UpdateTenantParams) error {
	return translateErr(s.q.UpdateTenant(ctx, mysqlgen.UpdateTenantParams{
		Code:     arg.Code,
		Name:     arg.Name,
		Status:   arg.Status,
		UpdateBy: arg.UpdateBy,
		Now:      arg.Now,
		ID:       arg.ID,
	}))
}

func (s *Store) UpdateUser(ctx context.Context, arg store.UpdateUserParams) error {
	return translateErr(s.q.UpdateUser(ctx, mysqlgen.UpdateUserParams{
		Username: arg.Username,
		Nickname: arg.Nickname,
		Gender:   arg.Gender,
		DeptID:   arg.DeptID,
		Avatar:   arg.Avatar,
		Mobile:   arg.Mobile,
		Status:   arg.Status,
		Email:    arg.Email,
		UpdateBy: arg.UpdateBy,
		Now:      arg.Now,
		ID:       arg.ID,
	}))
}

func (s *Store) UpdateUserPassword(ctx context.Context, arg store.UpdateUserPasswordParams) error {
	return translateErr(s.q.UpdateUserPassword(ctx, mysqlgen.UpdateUserPasswordParams{
		Password: arg.Password,
		Now:      arg.Now,
		ID:       arg.ID,
	}))
}

func (s *Store) UpdateUserProfile(ctx context.Context, arg store.UpdateUserProfileParams) error {
	return translateErr(s.q.UpdateUserProfile(ctx, mysqlgen.UpdateUserProfileParams(arg)))
}

func (s *Store) UpdateUserStatus(ctx context.Context, arg store.UpdateUserStatusParams) error {
	return translateErr(s.q.UpdateUserStatus(ctx, mysqlgen.UpdateUserStatusParams{
		Status: arg.Status,
		Now:    arg.Now,
		ID:     arg.ID,
	}))
}
