// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: config.sql

package mysqlgen

import (
	"context"
	"time"
)

const countConfigs = `-- name: CountConfigs :one
SELECT COUNT(*) FROM t_config
WHERE is_deleted = 0
  AND (? IS NULL OR (config_name LIKE ? OR config_key LIKE ?))
`

type CountConfigsParams struct {
	Keywords *string
}

func (q *Queries) CountConfigs(ctx context.Context, arg CountConfigsParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countConfigs, arg.Keywords, arg.Keywords, arg.Keywords)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countConfigsByKey = `-- name: CountConfigsByKey :one
SELECT COUNT(*) FROM t_config
WHERE config_key = ? AND is_deleted = 0
  AND (? IS NULL OR id <> ?)
`

type CountConfigsByKeyParams struct {
	ConfigKey string
	ExcludeID *string
}

// Counts non-deleted configs with the given key, optionally excluding one id.
func (q *Queries) CountConfigsByKey(ctx context.Context, arg CountConfigsByKeyParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countConfigsByKey, arg.ConfigKey, arg.ExcludeID, arg.ExcludeID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createConfig = `-- name: CreateConfig :exec
INSERT INTO t_config (
    id, config_name, config_key, config_value, remark, create_by, update_by, is_deleted,
    create_time, update_time
) VALUES (
    ?, ?, ?, ?,
    ?, ?, ?, ?,
    ?, ?
)
`

type CreateConfigParams struct {
	ID          string
	ConfigName  string
	ConfigKey   string
	ConfigValue string
	Remark      string
	CreateBy    string
	UpdateBy    string
	IsDeleted   int32
	Now         time.Time
}

func (q *Queries) CreateConfig(ctx context.Context, arg CreateConfigParams) error {
	_, err := q.db.ExecContext(ctx, createConfig,
		arg.ID,
		arg.ConfigName,
		arg.ConfigKey,
		arg.ConfigValue,
		arg.Remark,
		arg.CreateBy,
		arg.UpdateBy,
		arg.IsDeleted,
		arg.Now,
		arg.Now,
	)
	return err
}

const getConfig = `-- name: GetConfig :one

SELECT id, config_name, config_key, config_value, remark, create_time, create_by, update_time, update_by, is_deleted FROM t_config WHERE id = ? AND is_deleted = 0
`

// config.sql (MySQL dialect)
// Derived from queries/postgres/config.sql per docs/multi-database-plan.md section 5:
// every parameter is a named sqlc.arg/narg (kept in lockstep with the sqlite
// dialect). LIMIT/OFFSET are non-null args because MySQL rejects LIMIT NULL;
// the adapter maps a nil store limit/offset to MaxInt64/0.
func (q *Queries) GetConfig(ctx context.Context, id string) (TConfig, error) {
	row := q.db.QueryRowContext(ctx, getConfig, id)
	var i TConfig
	err := row.Scan(
		&i.ID,
		&i.ConfigName,
		&i.ConfigKey,
		&i.ConfigValue,
		&i.Remark,
		&i.CreateTime,
		&i.CreateBy,
		&i.UpdateTime,
		&i.UpdateBy,
		&i.IsDeleted,
	)
	return i, err
}

const getConfigByKey = `-- name: GetConfigByKey :one
SELECT id, config_name, config_key, config_value, remark, create_time, create_by, update_time, update_by, is_deleted FROM t_config WHERE config_key = ? AND is_deleted = 0
`

func (q *Queries) GetConfigByKey(ctx context.Context, configKey string) (TConfig, error) {
	row := q.db.QueryRowContext(ctx, getConfigByKey, configKey)
	var i TConfig
	err := row.Scan(
		&i.ID,
		&i.ConfigName,
		&i.ConfigKey,
		&i.ConfigValue,
		&i.Remark,
		&i.CreateTime,
		&i.CreateBy,
		&i.UpdateTime,
		&i.UpdateBy,
		&i.IsDeleted,
	)
	return i, err
}

const listAllConfigs = `-- name: ListAllConfigs :many
SELECT id, config_name, config_key, config_value, remark, create_time, create_by, update_time, update_by, is_deleted FROM t_config WHERE is_deleted = 0
`

func (q *Queries) ListAllConfigs(ctx context.Context) ([]TConfig, error) {
	rows, err := q.db.QueryContext(ctx, listAllConfigs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TConfig{}
	for rows.Next() {
		var i TConfig
		if err := rows.Scan(
			&i.ID,
			&i.ConfigName,
			&i.ConfigKey,
			&i.ConfigValue,
			&i.Remark,
			&i.CreateTime,
			&i.CreateBy,
			&i.UpdateTime,
			&i.UpdateBy,
			&i.IsDeleted,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listConfigs = `-- name: ListConfigs :many
SELECT id, config_name, config_key, config_value, remark, create_time, create_by, update_time, update_by, is_deleted FROM t_config
WHERE is_deleted = 0
  AND (? IS NULL OR (config_name LIKE ? OR config_key LIKE ?))
ORDER BY id DESC
LIMIT  ?
OFFSET ?
`

type ListConfigsParams struct {
	Keywords *string
	Limit    int32
	Offset   int32
}

func (q *Queries) ListConfigs(ctx context.Context, arg ListConfigsParams) ([]TConfig, error) {
	rows, err := q.db.QueryContext(ctx, listConfigs,
		arg.Keywords,
		arg.Keywords,
		arg.Keywords,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TConfig{}
	for rows.Next() {
		var i TConfig
		if err := rows.Scan(
			&i.ID,
			&i.ConfigName,
			&i.ConfigKey,
			&i.ConfigValue,
			&i.Remark,
			&i.CreateTime,
			&i.CreateBy,
			&i.UpdateTime,
			&i.UpdateBy,
			&i.IsDeleted,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteConfig = `-- name: SoftDeleteConfig :exec
UPDATE t_config SET is_deleted = 1, update_by = ?, update_time = ? WHERE id = ?
`

type SoftDeleteConfigParams struct {
	UpdateBy string
	Now      time.Time
	ID       string
}

func (q *Queries) SoftDeleteConfig(ctx context.Context, arg SoftDeleteConfigParams) error {
	_, err := q.db.ExecContext(ctx, softDeleteConfig, arg.UpdateBy, arg.Now, arg.ID)
	return err
}

const updateConfig = `-- name: UpdateConfig :exec
UPDATE t_config SET
    config_name  = ?,
    config_key   = ?,
    config_value = ?,
    remark       = ?,
    update_by    = ?,
    update_time  = ?
WHERE id = ?
`

type UpdateConfigParams struct {
	ConfigName  string
	ConfigKey   string
	ConfigValue string
	Remark      string
	UpdateBy    string
	Now         time.Time
	ID          string
}

func (q *Queries) UpdateConfig(ctx context.Context, arg UpdateConfigParams) error {
	_, err := q.db.ExecContext(ctx, updateConfig,
		arg.ConfigName,
		arg.ConfigKey,
		arg.ConfigValue,
		arg.Remark,
		arg.UpdateBy,
		arg.Now,
		arg.ID,
	)
	return err
}
