// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: dept.sql

package mysqlgen

import (
	"context"
	"strings"
	"time"
)

const createDept = `-- name: CreateDept :exec
INSERT INTO t_dept (
    id, name, code, parent_id, tree_path, sort, status,
    create_by, update_by, is_deleted, create_time, update_time
) VALUES (
    ?, ?, ?, ?,
    ?, ?, ?,
    ?, ?, ?,
    ?, ?
)
`

type CreateDeptParams struct {
	ID        string
	Name      string
	Code      string
	ParentID  string
	TreePath  string
	Sort      int32
	Status    int32
	CreateBy  string
	UpdateBy  string
	IsDeleted int32
	Now       time.Time
}

func (q *Queries) CreateDept(ctx context.Context, arg CreateDeptParams) error {
	_, err := q.db.ExecContext(ctx, createDept,
		arg.ID,
		arg.Name,
		arg.Code,
		arg.ParentID,
		arg.TreePath,
		arg.Sort,
		arg.Status,
		arg.CreateBy,
		arg.UpdateBy,
		arg.IsDeleted,
		arg.Now,
		arg.Now,
	)
	return err
}

const getDept = `-- name: GetDept :one

SELECT id, name, code, parent_id, tree_path, sort, status, create_by, create_time, update_by, update_time, is_deleted FROM t_dept
WHERE id = ? AND is_deleted = 0
`

// dept.sql (MySQL dialect)
// Derived from queries/postgres/dept.sql. Every parameter is a named
// sqlc.arg/narg (see config.sql header). Non-null id lists use sqlc.slice;
// string concatenation uses CONCAT().
func (q *Queries) GetDept(ctx context.Context, id string) (TDept, error) {
	row := q.db.QueryRowContext(ctx, getDept, id)
	var i TDept
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Code,
		&i.ParentID,
		&i.TreePath,
		&i.Sort,
		&i.Status,
		&i.CreateBy,
		&i.CreateTime,
		&i.UpdateBy,
		&i.UpdateTime,
		&i.IsDeleted,
	)
	return i, err
}

const getDeptByCode = `-- name: GetDeptByCode :one
SELECT id, name, code, parent_id, tree_path, sort, status, create_by, create_time, update_by, update_time, is_deleted FROM t_dept
WHERE code = ? AND is_deleted = 0
  AND (? IS NULL OR id <> ?)
LIMIT 1
`

type GetDeptByCodeParams struct {
	Code      string
	ExcludeID *string
}

// exclude_id lets callers ignore a specific row (used when validating a code on
// update). A NULL exclude_id disables the exclusion.
func (q *Queries) GetDeptByCode(ctx context.Context, arg GetDeptByCodeParams) (TDept, error) {
	row := q.db.QueryRowContext(ctx, getDeptByCode, arg.Code, arg.ExcludeID, arg.ExcludeID)
	var i TDept
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Code,
		&i.ParentID,
		&i.TreePath,
		&i.Sort,
		&i.Status,
		&i.CreateBy,
		&i.CreateTime,
		&i.UpdateBy,
		&i.UpdateTime,
		&i.IsDeleted,
	)
	return i, err
}

const listDepts = `-- name: ListDepts :many
SELECT id, name, code, parent_id, tree_path, sort, status, create_by, create_time, update_by, update_time, is_deleted FROM t_dept
WHERE is_deleted = 0
  AND (? IS NULL OR name LIKE ?)
  AND (?   IS NULL OR status = ?)
ORDER BY sort ASC
`

type ListDeptsParams struct {
	Keywords *string
	Status   *int32
}

func (q *Queries) ListDepts(ctx context.Context, arg ListDeptsParams) ([]TDept, error) {
	rows, err := q.db.QueryContext(ctx, listDepts,
		arg.Keywords,
		arg.Keywords,
		arg.Status,
		arg.Status,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TDept{}
	for rows.Next() {
		var i TDept
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Code,
			&i.ParentID,
			&i.TreePath,
			&i.Sort,
			&i.Status,
			&i.CreateBy,
			&i.CreateTime,
			&i.UpdateBy,
			&i.UpdateTime,
			&i.IsDeleted,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDeptsByIDs = `-- name: ListDeptsByIDs :many
SELECT id, name, code, parent_id, tree_path, sort, status, create_by, create_time, update_by, update_time, is_deleted FROM t_dept
WHERE is_deleted = 0 AND id IN (/*SLICE:ids*/?)
`

func (q *Queries) ListDeptsByIDs(ctx context.Context, ids []string) ([]TDept, error) {
	query := listDeptsByIDs
	var queryParams []interface{}
	if len(ids) > 0 {
		for _, v := range ids {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:ids*/?", strings.Repeat(",?", len(ids))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:ids*/?", "NULL", 1)
	}
	rows, err := q.db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TDept{}
	for rows.Next() {
		var i TDept
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Code,
			&i.ParentID,
			&i.TreePath,
			&i.Sort,
			&i.Status,
			&i.CreateBy,
			&i.CreateTime,
			&i.UpdateBy,
			&i.UpdateTime,
			&i.IsDeleted,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEnabledDepts = `-- name: ListEnabledDepts :many
SELECT id, name, code, parent_id, tree_path, sort, status, create_by, create_time, update_by, update_time, is_deleted FROM t_dept
WHERE is_deleted = 0 AND status = 1
ORDER BY sort ASC
`

func (q *Queries) ListEnabledDepts(ctx context.Context) ([]TDept, error) {
	rows, err := q.db.QueryContext(ctx, listEnabledDepts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TDept{}
	for rows.Next() {
		var i TDept
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Code,
			&i.ParentID,
			&i.TreePath,
			&i.Sort,
			&i.Status,
			&i.CreateBy,
			&i.CreateTime,
			&i.UpdateBy,
			&i.UpdateTime,
			&i.IsDeleted,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteDept = `-- name: SoftDeleteDept :exec
UPDATE t_dept SET is_deleted = 1, update_by = ?, update_time = ?
WHERE id = ?
`

type SoftDeleteDeptParams struct {
	UpdateBy string
	Now      time.Time
	ID       string
}

func (q *Queries) SoftDeleteDept(ctx context.Context, arg SoftDeleteDeptParams) error {
	_, err := q.db.ExecContext(ctx, softDeleteDept, arg.UpdateBy, arg.Now, arg.ID)
	return err
}

const softDeleteDeptByTreePath = `-- name: SoftDeleteDeptByTreePath :exec
UPDATE t_dept SET is_deleted = 1, update_by = ?, update_time = ?
WHERE id = ?
   OR CONCAT(',', tree_path, ',') LIKE ?
`

type SoftDeleteDeptByTreePathParams struct {
	UpdateBy     string
	Now          time.Time
	ID           string
	TreePathLike string
}

// Soft-deletes a department and all of its descendants. A node is a descendant
// when its comma-wrapped tree_path contains ",<id>,".
func (q *Queries) SoftDeleteDeptByTreePath(ctx context.Context, arg SoftDeleteDeptByTreePathParams) error {
	_, err := q.db.ExecContext(ctx, softDeleteDeptByTreePath,
		arg.UpdateBy,
		arg.Now,
		arg.ID,
		arg.TreePathLike,
	)
	return err
}

const updateDept = `-- name: UpdateDept :exec
UPDATE t_dept SET
    name        = ?,
    code        = ?,
    parent_id   = ?,
    tree_path   = ?,
    sort        = ?,
    status      = ?,
    update_by   = ?,
    update_time = ?
WHERE id = ?
`

type UpdateDeptParams struct {
	Name     string
	Code     string
	ParentID string
	TreePath string
	Sort     int32
	Status   int32
	UpdateBy string
	Now      time.Time
	ID       string
}

// Mirrors the previous Select-scoped GORM update
// (name, code, parent_id, tree_path, sort, status, update_by).
func (q *Queries) UpdateDept(ctx context.Context, arg UpdateDeptParams) error {
	_, err := q.db.ExecContext(ctx, updateDept,
		arg.Name,
		arg.Code,
		arg.ParentID,
		arg.TreePath,
		arg.Sort,
		arg.Status,
		arg.UpdateBy,
		arg.Now,
		arg.ID,
	)
	return err
}
