// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: dict_item.sql

package mysqlgen

import (
	"context"
	"strings"
	"time"
)

const countDictItems = `-- name: CountDictItems :one
SELECT COUNT(*) FROM t_dict_item
WHERE is_deleted = 0
  AND (? IS NULL OR dict_code = ?)
  AND (?  IS NULL OR (label LIKE ? OR value LIKE ?))
`

type CountDictItemsParams struct {
	DictCode *string
	Keywords *string
}

func (q *Queries) CountDictItems(ctx context.Context, arg CountDictItemsParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countDictItems,
		arg.DictCode,
		arg.DictCode,
		arg.Keywords,
		arg.Keywords,
		arg.Keywords,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createDictItem = `-- name: CreateDictItem :exec
INSERT INTO t_dict_item (
    id, dict_code, label, value, tag_type, sort, status, remark,
    create_by, update_by, is_deleted, create_time, update_time
) VALUES (
    ?, ?, ?, ?,
    ?, ?, ?, ?,
    ?, ?, ?,
    ?, ?
)
`

type CreateDictItemParams struct {
	ID        string
	DictCode  string
	Label     string
	Value     string
	TagType   string
	Sort      int32
	Status    int32
	Remark    string
	CreateBy  string
	UpdateBy  string
	IsDeleted int32
	Now       time.Time
}

func (q *Queries) CreateDictItem(ctx context.Context, arg CreateDictItemParams) error {
	_, err := q.db.ExecContext(ctx, createDictItem,
		arg.ID,
		arg.DictCode,
		arg.Label,
		arg.Value,
		arg.TagType,
		arg.Sort,
		arg.Status,
		arg.Remark,
		arg.CreateBy,
		arg.UpdateBy,
		arg.IsDeleted,
		arg.Now,
		arg.Now,
	)
	return err
}

const getDictItem = `-- name: GetDictItem :one

SELECT id, dict_code, label, value, tag_type, sort, status, remark, create_by, create_time, update_by, update_time, is_deleted FROM t_dict_item WHERE id = ? AND is_deleted = 0
`

// dict_item.sql (MySQL dialect)
// Derived from queries/postgres/dict_item.sql. Every parameter is a named
// sqlc.arg/narg (see config.sql header).
func (q *Queries) GetDictItem(ctx context.Context, id string) (TDictItem, error) {
	row := q.db.QueryRowContext(ctx, getDictItem, id)
	var i TDictItem
	err := row.Scan(
		&i.ID,
		&i.DictCode,
		&i.Label,
		&i.Value,
		&i.TagType,
		&i.Sort,
		&i.Status,
		&i.Remark,
		&i.CreateBy,
		&i.CreateTime,
		&i.UpdateBy,
		&i.UpdateTime,
		&i.IsDeleted,
	)
	return i, err
}

const listDictItems = `-- name: ListDictItems :many
SELECT id, dict_code, label, value, tag_type, sort, status, remark, create_by, create_time, update_by, update_time, is_deleted FROM t_dict_item
WHERE is_deleted = 0
  AND (? IS NULL OR dict_code = ?)
  AND (?  IS NULL OR (label LIKE ? OR value LIKE ?))
ORDER BY sort ASC
LIMIT  ?
OFFSET ?
`

type ListDictItemsParams struct {
	DictCode *string
	Keywords *string
	Limit    int32
	Offset   int32
}

func (q *Queries) ListDictItems(ctx context.Context, arg ListDictItemsParams) ([]TDictItem, error) {
	rows, err := q.db.QueryContext(ctx, listDictItems,
		arg.DictCode,
		arg.DictCode,
		arg.Keywords,
		arg.Keywords,
		arg.Keywords,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TDictItem{}
	for rows.Next() {
		var i TDictItem
		if err := rows.Scan(
			&i.ID,
			&i.DictCode,
			&i.Label,
			&i.Value,
			&i.TagType,
			&i.Sort,
			&i.Status,
			&i.Remark,
			&i.CreateBy,
			&i.CreateTime,
			&i.UpdateBy,
			&i.UpdateTime,
			&i.IsDeleted,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDictItemsByDictCode = `-- name: ListDictItemsByDictCode :many
SELECT id, dict_code, label, value, tag_type, sort, status, remark, create_by, create_time, update_by, update_time, is_deleted FROM t_dict_item
WHERE dict_code = ? AND is_deleted = 0 AND status = 1
ORDER BY sort ASC
`

func (q *Queries) ListDictItemsByDictCode(ctx context.Context, dictCode string) ([]TDictItem, error) {
	rows, err := q.db.QueryContext(ctx, listDictItemsByDictCode, dictCode)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TDictItem{}
	for rows.Next() {
		var i TDictItem
		if err := rows.Scan(
			&i.ID,
			&i.DictCode,
			&i.Label,
			&i.Value,
			&i.TagType,
			&i.Sort,
			&i.Status,
			&i.Remark,
			&i.CreateBy,
			&i.CreateTime,
			&i.UpdateBy,
			&i.UpdateTime,
			&i.IsDeleted,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteDictItem = `-- name: SoftDeleteDictItem :exec
UPDATE t_dict_item SET is_deleted = 1, update_by = ?, update_time = ? WHERE id = ?
`

type SoftDeleteDictItemParams struct {
	UpdateBy string
	Now      time.Time
	ID       string
}

func (q *Queries) SoftDeleteDictItem(ctx context.Context, arg SoftDeleteDictItemParams) error {
	_, err := q.db.ExecContext(ctx, softDeleteDictItem, arg.UpdateBy, arg.Now, arg.ID)
	return err
}

const softDeleteDictItemsByDictCodes = `-- name: SoftDeleteDictItemsByDictCodes :exec
UPDATE t_dict_item SET is_deleted = 1, update_by = ?, update_time = ?
WHERE dict_code IN (/*SLICE:dict_codes*/?)
`

type SoftDeleteDictItemsByDictCodesParams struct {
	UpdateBy  string
	Now       time.Time
	DictCodes []string
}

func (q *Queries) SoftDeleteDictItemsByDictCodes(ctx context.Context, arg SoftDeleteDictItemsByDictCodesParams) error {
	query := softDeleteDictItemsByDictCodes
	var queryParams []interface{}
	queryParams = append(queryParams, arg.UpdateBy)
	queryParams = append(queryParams, arg.Now)
	if len(arg.DictCodes) > 0 {
		for _, v := range arg.DictCodes {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:dict_codes*/?", strings.Repeat(",?", len(arg.DictCodes))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:dict_codes*/?", "NULL", 1)
	}
	_, err := q.db.ExecContext(ctx, query, queryParams...)
	return err
}

const softDeleteDictItemsByIDs = `-- name: SoftDeleteDictItemsByIDs :exec
UPDATE t_dict_item SET is_deleted = 1, update_by = ?, update_time = ?
WHERE id IN (/*SLICE:ids*/?)
`

type SoftDeleteDictItemsByIDsParams struct {
	UpdateBy string
	Now      time.Time
	Ids      []string
}

func (q *Queries) SoftDeleteDictItemsByIDs(ctx context.Context, arg SoftDeleteDictItemsByIDsParams) error {
	query := softDeleteDictItemsByIDs
	var queryParams []interface{}
	queryParams = append(queryParams, arg.UpdateBy)
	queryParams = append(queryParams, arg.Now)
	if len(arg.Ids) > 0 {
		for _, v := range arg.Ids {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:ids*/?", strings.Repeat(",?", len(arg.Ids))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:ids*/?", "NULL", 1)
	}
	_, err := q.db.ExecContext(ctx, query, queryParams...)
	return err
}

const updateDictItem = `-- name: UpdateDictItem :exec
UPDATE t_dict_item SET
    dict_code   = ?,
    label       = ?,
    value       = ?,
    tag_type    = ?,
    sort        = ?,
    status      = ?,
    remark      = ?,
    update_by   = ?,
    update_time = ?
WHERE id = ?
`

type UpdateDictItemParams struct {
	DictCode string
	Label    string
	Value    string
	TagType  string
	Sort     int32
	Status   int32
	Remark   string
	UpdateBy string
	Now      time.Time
	ID       string
}

func (q *Queries) UpdateDictItem(ctx context.Context, arg UpdateDictItemParams) error {
	_, err := q.db.ExecContext(ctx, updateDictItem,
		arg.DictCode,
		arg.Label,
		arg.Value,
		arg.TagType,
		arg.Sort,
		arg.Status,
		arg.Remark,
		arg.UpdateBy,
		arg.Now,
		arg.ID,
	)
	return err
}

const updateDictItemsDictCode = `-- name: UpdateDictItemsDictCode :exec
UPDATE t_dict_item SET dict_code = ?, update_time = ?
WHERE dict_code = ?
`

type UpdateDictItemsDictCodeParams struct {
	NewCode string
	Now     time.Time
	OldCode string
}

// Cascade a dictionary code rename onto its items. Called by DictRepository when a
// dictionary's code changes.
func (q *Queries) UpdateDictItemsDictCode(ctx context.Context, arg UpdateDictItemsDictCodeParams) error {
	_, err := q.db.ExecContext(ctx, updateDictItemsDictCode, arg.NewCode, arg.Now, arg.OldCode)
	return err
}
