// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: log.sql

package mysqlgen

import (
	"context"
	"strings"
	"time"
)

const batchDeleteLogs = `-- name: BatchDeleteLogs :exec
DELETE FROM sys_log WHERE id IN (/*SLICE:ids*/?)
`

func (q *Queries) BatchDeleteLogs(ctx context.Context, ids []string) error {
	query := batchDeleteLogs
	var queryParams []interface{}
	if len(ids) > 0 {
		for _, v := range ids {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:ids*/?", strings.Repeat(",?", len(ids))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:ids*/?", "NULL", 1)
	}
	_, err := q.db.ExecContext(ctx, query, queryParams...)
	return err
}

const countLogs = `-- name: CountLogs :one
SELECT COUNT(*) FROM sys_log
WHERE (?   IS NULL OR module = ?)
  AND (? IS NULL OR (content LIKE ? OR request_uri LIKE ?))
  AND (? IS NULL OR create_time >= ?)
  AND (?   IS NULL OR create_time <= ?)
`

type CountLogsParams struct {
	Module     *string
	Keywords   *string
	CreateFrom *time.Time
	CreateTo   *time.Time
}

func (q *Queries) CountLogs(ctx context.Context, arg CountLogsParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countLogs,
		arg.Module,
		arg.Module,
		arg.Keywords,
		arg.Keywords,
		arg.Keywords,
		arg.CreateFrom,
		arg.CreateFrom,
		arg.CreateTo,
		arg.CreateTo,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createLog = `-- name: CreateLog :exec
INSERT INTO sys_log (
    id, module, request_method, request_params, response_content, content,
    request_uri, method, ip, province, city, execution_time,
    browser, browser_version, os, create_by, create_time
) VALUES (
    ?, ?, ?, ?,
    ?, ?,
    ?, ?, ?, ?,
    ?, ?,
    ?, ?, ?, ?,
    ?
)
`

type CreateLogParams struct {
	ID              string
	Module          string
	RequestMethod   string
	RequestParams   string
	ResponseContent string
	Content         string
	RequestUri      string
	Method          string
	Ip              string
	Province        string
	City            string
	ExecutionTime   int64
	Browser         string
	BrowserVersion  string
	Os              string
	CreateBy        string
	Now             time.Time
}

func (q *Queries) CreateLog(ctx context.Context, arg CreateLogParams) error {
	_, err := q.db.ExecContext(ctx, createLog,
		arg.ID,
		arg.Module,
		arg.RequestMethod,
		arg.RequestParams,
		arg.ResponseContent,
		arg.Content,
		arg.RequestUri,
		arg.Method,
		arg.Ip,
		arg.Province,
		arg.City,
		arg.ExecutionTime,
		arg.Browser,
		arg.BrowserVersion,
		arg.Os,
		arg.CreateBy,
		arg.Now,
	)
	return err
}

const deleteLog = `-- name: DeleteLog :exec
DELETE FROM sys_log WHERE id = ?
`

func (q *Queries) DeleteLog(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteLog, id)
	return err
}

const getLog = `-- name: GetLog :one

SELECT id, module, request_method, request_params, response_content, content, request_uri, method, ip, province, city, execution_time, browser, browser_version, os, create_by, create_time FROM sys_log WHERE id = ?
`

// log.sql (MySQL dialect)
// Derived from queries/postgres/log.sql. Every parameter is a named
// sqlc.arg/narg (see config.sql header).
func (q *Queries) GetLog(ctx context.Context, id string) (SysLog, error) {
	row := q.db.QueryRowContext(ctx, getLog, id)
	var i SysLog
	err := row.Scan(
		&i.ID,
		&i.Module,
		&i.RequestMethod,
		&i.RequestParams,
		&i.ResponseContent,
		&i.Content,
		&i.RequestUri,
		&i.Method,
		&i.Ip,
		&i.Province,
		&i.City,
		&i.ExecutionTime,
		&i.Browser,
		&i.BrowserVersion,
		&i.Os,
		&i.CreateBy,
		&i.CreateTime,
	)
	return i, err
}

const listLogs = `-- name: ListLogs :many
SELECT id, module, request_method, request_params, response_content, content, request_uri, method, ip, province, city, execution_time, browser, browser_version, os, create_by, create_time FROM sys_log
WHERE (?   IS NULL OR module = ?)
  AND (? IS NULL OR (content LIKE ? OR request_uri LIKE ?))
  AND (? IS NULL OR create_time >= ?)
  AND (?   IS NULL OR create_time <= ?)
ORDER BY create_time DESC
LIMIT  ?
OFFSET ?
`

type ListLogsParams struct {
	Module     *string
	Keywords   *string
	CreateFrom *time.Time
	CreateTo   *time.Time
	Limit      int32
	Offset     int32
}

func (q *Queries) ListLogs(ctx context.Context, arg ListLogsParams) ([]SysLog, error) {
	rows, err := q.db.QueryContext(ctx, listLogs,
		arg.Module,
		arg.Module,
		arg.Keywords,
		arg.Keywords,
		arg.Keywords,
		arg.CreateFrom,
		arg.CreateFrom,
		arg.CreateTo,
		arg.CreateTo,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SysLog{}
	for rows.Next() {
		var i SysLog
		if err := rows.Scan(
			&i.ID,
			&i.Module,
			&i.RequestMethod,
			&i.RequestParams,
			&i.ResponseContent,
			&i.Content,
			&i.RequestUri,
			&i.Method,
			&i.Ip,
			&i.Province,
			&i.City,
			&i.ExecutionTime,
			&i.Browser,
			&i.BrowserVersion,
			&i.Os,
			&i.CreateBy,
			&i.CreateTime,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
