// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: member.sql

package mysqlgen

import (
	"context"
	"time"
)

const countMembers = `-- name: CountMembers :one
SELECT COUNT(*) FROM t_member
WHERE is_deleted = 0
  AND (? IS NULL OR tenant_id = ?)
  AND (?  IS NULL OR (username LIKE ? OR nickname LIKE ? OR email LIKE ?))
  AND (?    IS NULL OR status = ?)
`

type CountMembersParams struct {
	TenantID *string
	Keywords *string
	Status   *int32
}

func (q *Queries) CountMembers(ctx context.Context, arg CountMembersParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countMembers,
		arg.TenantID,
		arg.TenantID,
		arg.Keywords,
		arg.Keywords,
		arg.Keywords,
		arg.Keywords,
		arg.Status,
		arg.Status,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countMembersByUsername = `-- name: CountMembersByUsername :one
SELECT COUNT(*) FROM t_member
WHERE tenant_id = ? AND username = ? AND is_deleted = 0
`

type CountMembersByUsernameParams struct {
	TenantID string
	Username string
}

func (q *Queries) CountMembersByUsername(ctx context.Context, arg CountMembersByUsernameParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countMembersByUsername, arg.TenantID, arg.Username)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createMember = `-- name: CreateMember :exec
INSERT INTO t_member (
    id, tenant_id, username, email, mobile, password, nickname, avatar,
    gender, status, is_deleted, create_time, update_time
) VALUES (
    ?, ?, ?, ?,
    ?, ?, ?, ?,
    ?, ?, ?,
    ?, ?
)
`

type CreateMemberParams struct {
	ID        string
	TenantID  string
	Username  string
	Email     string
	Mobile    string
	Password  string
	Nickname  string
	Avatar    string
	Gender    int32
	Status    int32
	IsDeleted int32
	Now       time.Time
}

func (q *Queries) CreateMember(ctx context.Context, arg CreateMemberParams) error {
	_, err := q.db.ExecContext(ctx, createMember,
		arg.ID,
		arg.TenantID,
		arg.Username,
		arg.Email,
		arg.Mobile,
		arg.Password,
		arg.Nickname,
		arg.Avatar,
		arg.Gender,
		arg.Status,
		arg.IsDeleted,
		arg.Now,
		arg.Now,
	)
	return err
}

const getMemberByID = `-- name: GetMemberByID :one
SELECT id, tenant_id, username, email, mobile, password, nickname, avatar, gender, status, last_login_time, last_login_ip, create_time, update_time, is_deleted FROM t_member
WHERE tenant_id = ? AND id = ? AND is_deleted = 0
`

type GetMemberByIDParams struct {
	TenantID string
	ID       string
}

func (q *Queries) GetMemberByID(ctx context.Context, arg GetMemberByIDParams) (TMember, error) {
	row := q.db.QueryRowContext(ctx, getMemberByID, arg.TenantID, arg.ID)
	var i TMember
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Username,
		&i.Email,
		&i.Mobile,
		&i.Password,
		&i.Nickname,
		&i.Avatar,
		&i.Gender,
		&i.Status,
		&i.LastLoginTime,
		&i.LastLoginIp,
		&i.CreateTime,
		&i.UpdateTime,
		&i.IsDeleted,
	)
	return i, err
}

const getMemberByUsername = `-- name: GetMemberByUsername :one

SELECT id, tenant_id, username, email, mobile, password, nickname, avatar, gender, status, last_login_time, last_login_ip, create_time, update_time, is_deleted FROM t_member
WHERE tenant_id = ? AND username = ? AND is_deleted = 0
`

type GetMemberByUsernameParams struct {
	TenantID string
	Username string
}

// member.sql (MySQL dialect)
// Derived from queries/postgres/member.sql. Every parameter is a named
// sqlc.arg/narg (see config.sql header). All member access is tenant-scoped.
func (q *Queries) GetMemberByUsername(ctx context.Context, arg GetMemberByUsernameParams) (TMember, error) {
	row := q.db.QueryRowContext(ctx, getMemberByUsername, arg.TenantID, arg.Username)
	var i TMember
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Username,
		&i.Email,
		&i.Mobile,
		&i.Password,
		&i.Nickname,
		&i.Avatar,
		&i.Gender,
		&i.Status,
		&i.LastLoginTime,
		&i.LastLoginIp,
		&i.CreateTime,
		&i.UpdateTime,
		&i.IsDeleted,
	)
	return i, err
}

const listMembers = `-- name: ListMembers :many
SELECT id, tenant_id, username, email, mobile, password, nickname, avatar, gender, status, last_login_time, last_login_ip, create_time, update_time, is_deleted FROM t_member
WHERE is_deleted = 0
  AND (? IS NULL OR tenant_id = ?)
  AND (?  IS NULL OR (username LIKE ? OR nickname LIKE ? OR email LIKE ?))
  AND (?    IS NULL OR status = ?)
ORDER BY id DESC
LIMIT  ?
OFFSET ?
`

type ListMembersParams struct {
	TenantID *string
	Keywords *string
	Status   *int32
	Limit    int32
	Offset   int32
}

func (q *Queries) ListMembers(ctx context.Context, arg ListMembersParams) ([]TMember, error) {
	rows, err := q.db.QueryContext(ctx, listMembers,
		arg.TenantID,
		arg.TenantID,
		arg.Keywords,
		arg.Keywords,
		arg.Keywords,
		arg.Keywords,
		arg.Status,
		arg.Status,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TMember{}
	for rows.Next() {
		var i TMember
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Username,
			&i.Email,
			&i.Mobile,
			&i.Password,
			&i.Nickname,
			&i.Avatar,
			&i.Gender,
			&i.Status,
			&i.LastLoginTime,
			&i.LastLoginIp,
			&i.CreateTime,
			&i.UpdateTime,
			&i.IsDeleted,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateMemberLoginInfo = `-- name: UpdateMemberLoginInfo :exec
UPDATE t_member SET last_login_ip = ?, last_login_time = ?, update_time = ?
WHERE tenant_id = ? AND id = ?
`

type UpdateMemberLoginInfoParams struct {
	LastLoginIp string
	Now         *time.Time
	TenantID    string
	ID          string
}

func (q *Queries) UpdateMemberLoginInfo(ctx context.Context, arg UpdateMemberLoginInfoParams) error {
	_, err := q.db.ExecContext(ctx, updateMemberLoginInfo,
		arg.LastLoginIp,
		arg.Now,
		arg.Now,
		arg.TenantID,
		arg.ID,
	)
	return err
}

const updateMemberPassword = `-- name: UpdateMemberPassword :exec
UPDATE t_member SET password = ?, update_time = ?
WHERE tenant_id = ? AND id = ?
`

type UpdateMemberPasswordParams struct {
	Password string
	Now      time.Time
	TenantID string
	ID       string
}

func (q *Queries) UpdateMemberPassword(ctx context.Context, arg UpdateMemberPasswordParams) error {
	_, err := q.db.ExecContext(ctx, updateMemberPassword,
		arg.Password,
		arg.Now,
		arg.TenantID,
		arg.ID,
	)
	return err
}

const updateMemberProfile = `-- name: UpdateMemberProfile :exec
UPDATE t_member SET
    nickname    = ?,
    avatar      = ?,
    gender      = ?,
    mobile      = ?,
    email       = ?,
    update_time = ?
WHERE tenant_id = ? AND id = ?
`

type UpdateMemberProfileParams struct {
	Nickname string
	Avatar   string
	Gender   int32
	Mobile   string
	Email    string
	Now      time.Time
	TenantID string
	ID       string
}

func (q *Queries) UpdateMemberProfile(ctx context.Context, arg UpdateMemberProfileParams) error {
	_, err := q.db.ExecContext(ctx, updateMemberProfile,
		arg.Nickname,
		arg.Avatar,
		arg.Gender,
		arg.Mobile,
		arg.Email,
		arg.Now,
		arg.TenantID,
		arg.ID,
	)
	return err
}

const updateMemberStatus = `-- name: UpdateMemberStatus :exec
UPDATE t_member SET status = ?, update_time = ?
WHERE tenant_id = ? AND id = ?
`

type UpdateMemberStatusParams struct {
	Status   int32
	Now      time.Time
	TenantID string
	ID       string
}

func (q *Queries) UpdateMemberStatus(ctx context.Context, arg UpdateMemberStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateMemberStatus,
		arg.Status,
		arg.Now,
		arg.TenantID,
		arg.ID,
	)
	return err
}
