// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: menu.sql

package mysqlgen

import (
	"context"
	"strings"
	"time"
)

const countMenus = `-- name: CountMenus :one
SELECT COUNT(*) FROM t_menu
WHERE (?              IS NULL OR FIND_IN_SET(id, ?))
  AND (?             IS NULL OR name = ?)
  AND (?        IS NULL OR parent_id = ?)
  AND (? IS NULL OR tree_path LIKE ?)
  AND (?             IS NULL OR type = ?)
  AND (?          IS NULL OR visible = ?)
  AND (?         IS NULL OR name LIKE ?)
`

type CountMenusParams struct {
	Ids            *string
	Name           *string
	ParentID       *string
	PrefixTreePath *string
	Type           *int32
	Visible        *int32
	Keywords       *string
}

func (q *Queries) CountMenus(ctx context.Context, arg CountMenusParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countMenus,
		arg.Ids,
		arg.Ids,
		arg.Name,
		arg.Name,
		arg.ParentID,
		arg.ParentID,
		arg.PrefixTreePath,
		arg.PrefixTreePath,
		arg.Type,
		arg.Type,
		arg.Visible,
		arg.Visible,
		arg.Keywords,
		arg.Keywords,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createMenu = `-- name: CreateMenu :exec
INSERT INTO t_menu (
    id, parent_id, tree_path, name, type, route_name, route_path, component,
    perm, always_show, keep_alive, visible, sort, icon, redirect, params,
    create_time, update_time
) VALUES (
    ?, ?, ?, ?,
    ?, ?, ?, ?,
    ?, ?, ?, ?,
    ?, ?, ?, ?,
    ?, ?
)
`

type CreateMenuParams struct {
	ID         string
	ParentID   string
	TreePath   string
	Name       string
	Type       int32
	RouteName  string
	RoutePath  string
	Component  string
	Perm       string
	AlwaysShow int32
	KeepAlive  int32
	Visible    int32
	Sort       int32
	Icon       string
	Redirect   string
	Params     string
	Now        time.Time
}

func (q *Queries) CreateMenu(ctx context.Context, arg CreateMenuParams) error {
	_, err := q.db.ExecContext(ctx, createMenu,
		arg.ID,
		arg.ParentID,
		arg.TreePath,
		arg.Name,
		arg.Type,
		arg.RouteName,
		arg.RoutePath,
		arg.Component,
		arg.Perm,
		arg.AlwaysShow,
		arg.KeepAlive,
		arg.Visible,
		arg.Sort,
		arg.Icon,
		arg.Redirect,
		arg.Params,
		arg.Now,
		arg.Now,
	)
	return err
}

const deleteMenu = `-- name: DeleteMenu :exec
DELETE FROM t_menu WHERE id = ?
`

func (q *Queries) DeleteMenu(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteMenu, id)
	return err
}

const getMenu = `-- name: GetMenu :one
SELECT id, parent_id, tree_path, name, type, route_name, route_path, component, perm, always_show, keep_alive, visible, sort, icon, redirect, params, create_time, update_time FROM t_menu WHERE id = ?
`

func (q *Queries) GetMenu(ctx context.Context, id string) (TMenu, error) {
	row := q.db.QueryRowContext(ctx, getMenu, id)
	var i TMenu
	err := row.Scan(
		&i.ID,
		&i.ParentID,
		&i.TreePath,
		&i.Name,
		&i.Type,
		&i.RouteName,
		&i.RoutePath,
		&i.Component,
		&i.Perm,
		&i.AlwaysShow,
		&i.KeepAlive,
		&i.Visible,
		&i.Sort,
		&i.Icon,
		&i.Redirect,
		&i.Params,
		&i.CreateTime,
		&i.UpdateTime,
	)
	return i, err
}

const listButtonPermsByRoleIDs = `-- name: ListButtonPermsByRoleIDs :many
SELECT perm FROM t_menu
WHERE id IN (SELECT DISTINCT menu_id FROM t_role_menu WHERE role_id IN (/*SLICE:role_ids*/?))
  AND type = 4
  AND perm <> ''
`

// Non-empty button (type = 4) permission strings for the given roles.
func (q *Queries) ListButtonPermsByRoleIDs(ctx context.Context, roleIds []string) ([]string, error) {
	query := listButtonPermsByRoleIDs
	var queryParams []interface{}
	if len(roleIds) > 0 {
		for _, v := range roleIds {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:role_ids*/?", strings.Repeat(",?", len(roleIds))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:role_ids*/?", "NULL", 1)
	}
	rows, err := q.db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var perm string
		if err := rows.Scan(&perm); err != nil {
			return nil, err
		}
		items = append(items, perm)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMenusByRoleIDs = `-- name: ListMenusByRoleIDs :many
SELECT id, parent_id, tree_path, name, type, route_name, route_path, component, perm, always_show, keep_alive, visible, sort, icon, redirect, params, create_time, update_time FROM t_menu
WHERE id IN (SELECT DISTINCT menu_id FROM t_role_menu WHERE role_id IN (/*SLICE:role_ids*/?))
ORDER BY sort ASC
`

// Menus assigned to any of the given roles, ordered by sort ASC.
func (q *Queries) ListMenusByRoleIDs(ctx context.Context, roleIds []string) ([]TMenu, error) {
	query := listMenusByRoleIDs
	var queryParams []interface{}
	if len(roleIds) > 0 {
		for _, v := range roleIds {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:role_ids*/?", strings.Repeat(",?", len(roleIds))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:role_ids*/?", "NULL", 1)
	}
	rows, err := q.db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TMenu{}
	for rows.Next() {
		var i TMenu
		if err := rows.Scan(
			&i.ID,
			&i.ParentID,
			&i.TreePath,
			&i.Name,
			&i.Type,
			&i.RouteName,
			&i.RoutePath,
			&i.Component,
			&i.Perm,
			&i.AlwaysShow,
			&i.KeepAlive,
			&i.Visible,
			&i.Sort,
			&i.Icon,
			&i.Redirect,
			&i.Params,
			&i.CreateTime,
			&i.UpdateTime,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMenusOrderByID = `-- name: ListMenusOrderByID :many
SELECT id, parent_id, tree_path, name, type, route_name, route_path, component, perm, always_show, keep_alive, visible, sort, icon, redirect, params, create_time, update_time FROM t_menu
WHERE (?              IS NULL OR FIND_IN_SET(id, ?))
  AND (?             IS NULL OR name = ?)
  AND (?        IS NULL OR parent_id = ?)
  AND (? IS NULL OR tree_path LIKE ?)
  AND (?             IS NULL OR type = ?)
  AND (?          IS NULL OR visible = ?)
  AND (?         IS NULL OR name LIKE ?)
ORDER BY id DESC
LIMIT  ?
OFFSET ?
`

type ListMenusOrderByIDParams struct {
	Ids            *string
	Name           *string
	ParentID       *string
	PrefixTreePath *string
	Type           *int32
	Visible        *int32
	Keywords       *string
	Limit          int32
	Offset         int32
}

func (q *Queries) ListMenusOrderByID(ctx context.Context, arg ListMenusOrderByIDParams) ([]TMenu, error) {
	rows, err := q.db.QueryContext(ctx, listMenusOrderByID,
		arg.Ids,
		arg.Ids,
		arg.Name,
		arg.Name,
		arg.ParentID,
		arg.ParentID,
		arg.PrefixTreePath,
		arg.PrefixTreePath,
		arg.Type,
		arg.Type,
		arg.Visible,
		arg.Visible,
		arg.Keywords,
		arg.Keywords,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TMenu{}
	for rows.Next() {
		var i TMenu
		if err := rows.Scan(
			&i.ID,
			&i.ParentID,
			&i.TreePath,
			&i.Name,
			&i.Type,
			&i.RouteName,
			&i.RoutePath,
			&i.Component,
			&i.Perm,
			&i.AlwaysShow,
			&i.KeepAlive,
			&i.Visible,
			&i.Sort,
			&i.Icon,
			&i.Redirect,
			&i.Params,
			&i.CreateTime,
			&i.UpdateTime,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMenusOrderBySort = `-- name: ListMenusOrderBySort :many

SELECT id, parent_id, tree_path, name, type, route_name, route_path, component, perm, always_show, keep_alive, visible, sort, icon, redirect, params, create_time, update_time FROM t_menu
WHERE (?              IS NULL OR FIND_IN_SET(id, ?))
  AND (?             IS NULL OR name = ?)
  AND (?        IS NULL OR parent_id = ?)
  AND (? IS NULL OR tree_path LIKE ?)
  AND (?             IS NULL OR type = ?)
  AND (?          IS NULL OR visible = ?)
  AND (?         IS NULL OR name LIKE ?)
ORDER BY sort ASC
LIMIT  ?
OFFSET ?
`

type ListMenusOrderBySortParams struct {
	Ids            *string
	Name           *string
	ParentID       *string
	PrefixTreePath *string
	Type           *int32
	Visible        *int32
	Keywords       *string
	Limit          int32
	Offset         int32
}

// menu.sql (MySQL dialect)
// Derived from queries/postgres/menu.sql. Every parameter is a named
// sqlc.arg/narg (see config.sql header). Two engine-specific deviations:
//
//   - The nullable id-list filter has no array type here: the adapter passes
//     the ids as a comma-separated string ("a,b") and FIND_IN_SET tests
//     membership; NULL disables the filter (same semantics as the postgres
//     narg text[]).
//   - The postgres ListMenus ORDER BY CASE selector is split into two queries
//     (kept in lockstep with the sqlite dialect); the mysqlstore adapter
//     dispatches on OrderBy.
func (q *Queries) ListMenusOrderBySort(ctx context.Context, arg ListMenusOrderBySortParams) ([]TMenu, error) {
	rows, err := q.db.QueryContext(ctx, listMenusOrderBySort,
		arg.Ids,
		arg.Ids,
		arg.Name,
		arg.Name,
		arg.ParentID,
		arg.ParentID,
		arg.PrefixTreePath,
		arg.PrefixTreePath,
		arg.Type,
		arg.Type,
		arg.Visible,
		arg.Visible,
		arg.Keywords,
		arg.Keywords,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TMenu{}
	for rows.Next() {
		var i TMenu
		if err := rows.Scan(
			&i.ID,
			&i.ParentID,
			&i.TreePath,
			&i.Name,
			&i.Type,
			&i.RouteName,
			&i.RoutePath,
			&i.Component,
			&i.Perm,
			&i.AlwaysShow,
			&i.KeepAlive,
			&i.Visible,
			&i.Sort,
			&i.Icon,
			&i.Redirect,
			&i.Params,
			&i.CreateTime,
			&i.UpdateTime,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateMenu = `-- name: UpdateMenu :exec
UPDATE t_menu SET
    parent_id   = ?,
    tree_path   = ?,
    name        = ?,
    type        = ?,
    route_name  = ?,
    route_path  = ?,
    component   = ?,
    perm        = ?,
    always_show = ?,
    keep_alive  = ?,
    visible     = ?,
    sort        = ?,
    icon        = ?,
    redirect    = ?,
    params      = ?,
    update_time = ?
WHERE id = ?
`

type UpdateMenuParams struct {
	ParentID   string
	TreePath   string
	Name       string
	Type       int32
	RouteName  string
	RoutePath  string
	Component  string
	Perm       string
	AlwaysShow int32
	KeepAlive  int32
	Visible    int32
	Sort       int32
	Icon       string
	Redirect   string
	Params     string
	Now        time.Time
	ID         string
}

func (q *Queries) UpdateMenu(ctx context.Context, arg UpdateMenuParams) error {
	_, err := q.db.ExecContext(ctx, updateMenu,
		arg.ParentID,
		arg.TreePath,
		arg.Name,
		arg.Type,
		arg.RouteName,
		arg.RoutePath,
		arg.Component,
		arg.Perm,
		arg.AlwaysShow,
		arg.KeepAlive,
		arg.Visible,
		arg.Sort,
		arg.Icon,
		arg.Redirect,
		arg.Params,
		arg.Now,
		arg.ID,
	)
	return err
}

const updateMenuTreePath = `-- name: UpdateMenuTreePath :exec
UPDATE t_menu SET tree_path = ?, update_time = ? WHERE id = ?
`

type UpdateMenuTreePathParams struct {
	TreePath string
	Now      time.Time
	ID       string
}

func (q *Queries) UpdateMenuTreePath(ctx context.Context, arg UpdateMenuTreePathParams) error {
	_, err := q.db.ExecContext(ctx, updateMenuTreePath, arg.TreePath, arg.Now, arg.ID)
	return err
}

const updateMenuVisible = `-- name: UpdateMenuVisible :exec
UPDATE t_menu SET visible = ?, update_time = ? WHERE id = ?
`

type UpdateMenuVisibleParams struct {
	Visible int32
	Now     time.Time
	ID      string
}

func (q *Queries) UpdateMenuVisible(ctx context.Context, arg UpdateMenuVisibleParams) error {
	_, err := q.db.ExecContext(ctx, updateMenuVisible, arg.Visible, arg.Now, arg.ID)
	return err
}
