// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queue_task.sql

package mysqlgen

import (
	"context"
	"time"
)

const createQueueTask = `-- name: CreateQueueTask :execlastid

INSERT INTO sys_tasks (
    type, status, correlation_id, owner_id, private_state,
    public_retry_count, public_executed_duration, public_error,
    public_error_history, public_resume_time, created_at, updated_at
) VALUES (
    ?, ?, ?, ?,
    ?, ?, ?,
    ?, ?, ?,
    ?, ?
)
`

type CreateQueueTaskParams struct {
	Type                   string
	Status                 string
	CorrelationID          string
	OwnerID                string
	PrivateState           string
	PublicRetryCount       int32
	PublicExecutedDuration int64
	PublicError            string
	PublicErrorHistory     string
	PublicResumeTime       int64
	Now                    time.Time
}

// queue_task.sql (MySQL dialect)
// Derived from queries/postgres/queue_task.sql. Every parameter is a named
// sqlc.arg/narg (see config.sql header). MySQL has no RETURNING: Create uses
// :execlastid and Update plain :exec; the mysqlstore adapter re-reads the row
// on the same connection/transaction. The nullable type-list filter uses the
// FIND_IN_SET membership test (see menu.sql header).
func (q *Queries) CreateQueueTask(ctx context.Context, arg CreateQueueTaskParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, createQueueTask,
		arg.Type,
		arg.Status,
		arg.CorrelationID,
		arg.OwnerID,
		arg.PrivateState,
		arg.PublicRetryCount,
		arg.PublicExecutedDuration,
		arg.PublicError,
		arg.PublicErrorHistory,
		arg.PublicResumeTime,
		arg.Now,
		arg.Now,
	)
	if err != nil {
		return 0, err
	}
	return result.LastInsertId()
}

const getQueueTask = `-- name: GetQueueTask :one
SELECT id, type, status, correlation_id, owner_id, private_state, public_retry_count, public_executed_duration, public_error, public_error_history, public_resume_time, created_at, updated_at, deleted_at FROM sys_tasks WHERE id = ? AND deleted_at IS NULL
`

func (q *Queries) GetQueueTask(ctx context.Context, id int64) (SysTask, error) {
	row := q.db.QueryRowContext(ctx, getQueueTask, id)
	var i SysTask
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.Status,
		&i.CorrelationID,
		&i.OwnerID,
		&i.PrivateState,
		&i.PublicRetryCount,
		&i.PublicExecutedDuration,
		&i.PublicError,
		&i.PublicErrorHistory,
		&i.PublicResumeTime,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listPendingQueueTasks = `-- name: ListPendingQueueTasks :many
SELECT id, type, status, correlation_id, owner_id, private_state, public_retry_count, public_executed_duration, public_error, public_error_history, public_resume_time, created_at, updated_at, deleted_at FROM sys_tasks
WHERE deleted_at IS NULL
  AND status IN ('queued', 'processing', 'suspending')
  AND (? IS NULL OR FIND_IN_SET(type, ?))
ORDER BY id
`

type ListPendingQueueTasksParams struct {
	Types *string
}

func (q *Queries) ListPendingQueueTasks(ctx context.Context, arg ListPendingQueueTasksParams) ([]SysTask, error) {
	rows, err := q.db.QueryContext(ctx, listPendingQueueTasks, arg.Types, arg.Types)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SysTask{}
	for rows.Next() {
		var i SysTask
		if err := rows.Scan(
			&i.ID,
			&i.Type,
			&i.Status,
			&i.CorrelationID,
			&i.OwnerID,
			&i.PrivateState,
			&i.PublicRetryCount,
			&i.PublicExecutedDuration,
			&i.PublicError,
			&i.PublicErrorHistory,
			&i.PublicResumeTime,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteQueueTask = `-- name: SoftDeleteQueueTask :exec
UPDATE sys_tasks SET deleted_at = ? WHERE id = ? AND deleted_at IS NULL
`

type SoftDeleteQueueTaskParams struct {
	Now *time.Time
	ID  int64
}

func (q *Queries) SoftDeleteQueueTask(ctx context.Context, arg SoftDeleteQueueTaskParams) error {
	_, err := q.db.ExecContext(ctx, softDeleteQueueTask, arg.Now, arg.ID)
	return err
}

const updateQueueTask = `-- name: UpdateQueueTask :exec
UPDATE sys_tasks SET
    type                     = ?,
    status                   = ?,
    correlation_id           = ?,
    owner_id                 = ?,
    private_state            = ?,
    public_retry_count       = ?,
    public_executed_duration = ?,
    public_error             = ?,
    public_error_history     = ?,
    public_resume_time       = ?,
    updated_at               = ?
WHERE id = ? AND deleted_at IS NULL
`

type UpdateQueueTaskParams struct {
	Type                   string
	Status                 string
	CorrelationID          string
	OwnerID                string
	PrivateState           string
	PublicRetryCount       int32
	PublicExecutedDuration int64
	PublicError            string
	PublicErrorHistory     string
	PublicResumeTime       int64
	Now                    time.Time
	ID                     int64
}

func (q *Queries) UpdateQueueTask(ctx context.Context, arg UpdateQueueTaskParams) error {
	_, err := q.db.ExecContext(ctx, updateQueueTask,
		arg.Type,
		arg.Status,
		arg.CorrelationID,
		arg.OwnerID,
		arg.PrivateState,
		arg.PublicRetryCount,
		arg.PublicExecutedDuration,
		arg.PublicError,
		arg.PublicErrorHistory,
		arg.PublicResumeTime,
		arg.Now,
		arg.ID,
	)
	return err
}
