// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: role.sql

package mysqlgen

import (
	"context"
	"time"
)

const countRoles = `-- name: CountRoles :one
SELECT COUNT(*) FROM t_role
WHERE is_deleted = 0
  AND (?     IS NULL OR FIND_IN_SET(id, ?))
  AND (?    IS NULL OR name = ?)
  AND (?    IS NULL OR code = ?)
  AND (? IS NULL OR id IN (
        SELECT role_id FROM t_user_role WHERE user_id = ?))
  AND (? IS NULL OR (
        name LIKE ? OR code LIKE ?))
  AND (?  IS NULL OR status = ?)
`

type CountRolesParams struct {
	Ids        *string
	Name       *string
	Code       *string
	UserID     *string
	QueryValue *string
	Status     *int32
}

func (q *Queries) CountRoles(ctx context.Context, arg CountRolesParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countRoles,
		arg.Ids,
		arg.Ids,
		arg.Name,
		arg.Name,
		arg.Code,
		arg.Code,
		arg.UserID,
		arg.UserID,
		arg.QueryValue,
		arg.QueryValue,
		arg.QueryValue,
		arg.Status,
		arg.Status,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createRole = `-- name: CreateRole :exec
INSERT INTO t_role (
    id, name, code, sort, status, data_scope, create_by, update_by, is_deleted,
    create_time, update_time
) VALUES (
    ?, ?, ?, ?,
    ?, ?, ?,
    ?, ?,
    ?, ?
)
`

type CreateRoleParams struct {
	ID        string
	Name      string
	Code      string
	Sort      int32
	Status    int32
	DataScope int32
	CreateBy  string
	UpdateBy  string
	IsDeleted int32
	Now       time.Time
}

func (q *Queries) CreateRole(ctx context.Context, arg CreateRoleParams) error {
	_, err := q.db.ExecContext(ctx, createRole,
		arg.ID,
		arg.Name,
		arg.Code,
		arg.Sort,
		arg.Status,
		arg.DataScope,
		arg.CreateBy,
		arg.UpdateBy,
		arg.IsDeleted,
		arg.Now,
		arg.Now,
	)
	return err
}

const getRole = `-- name: GetRole :one

SELECT id, name, code, sort, status, data_scope, create_by, create_time, update_by, update_time, is_deleted FROM t_role
WHERE id = ? AND is_deleted = 0
`

// role.sql (MySQL dialect)
// Derived from queries/postgres/role.sql. Every parameter is a named
// sqlc.arg/narg (see config.sql header). The nullable id-list filter uses the
// FIND_IN_SET membership test (see menu.sql header).
func (q *Queries) GetRole(ctx context.Context, id string) (TRole, error) {
	row := q.db.QueryRowContext(ctx, getRole, id)
	var i TRole
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Code,
		&i.Sort,
		&i.Status,
		&i.DataScope,
		&i.CreateBy,
		&i.CreateTime,
		&i.UpdateBy,
		&i.UpdateTime,
		&i.IsDeleted,
	)
	return i, err
}

const getRoleByCode = `-- name: GetRoleByCode :one
SELECT id, name, code, sort, status, data_scope, create_by, create_time, update_by, update_time, is_deleted FROM t_role
WHERE code = ? AND is_deleted = 0
LIMIT 1
`

func (q *Queries) GetRoleByCode(ctx context.Context, code string) (TRole, error) {
	row := q.db.QueryRowContext(ctx, getRoleByCode, code)
	var i TRole
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Code,
		&i.Sort,
		&i.Status,
		&i.DataScope,
		&i.CreateBy,
		&i.CreateTime,
		&i.UpdateBy,
		&i.UpdateTime,
		&i.IsDeleted,
	)
	return i, err
}

const listRoles = `-- name: ListRoles :many
SELECT id, name, code, sort, status, data_scope, create_by, create_time, update_by, update_time, is_deleted FROM t_role
WHERE is_deleted = 0
  AND (?     IS NULL OR FIND_IN_SET(id, ?))
  AND (?    IS NULL OR name = ?)
  AND (?    IS NULL OR code = ?)
  AND (? IS NULL OR id IN (
        SELECT role_id FROM t_user_role WHERE user_id = ?))
  AND (? IS NULL OR (
        name LIKE ? OR code LIKE ?))
  AND (?  IS NULL OR status = ?)
ORDER BY id DESC
LIMIT  ?
OFFSET ?
`

type ListRolesParams struct {
	Ids        *string
	Name       *string
	Code       *string
	UserID     *string
	QueryValue *string
	Status     *int32
	Limit      int32
	Offset     int32
}

func (q *Queries) ListRoles(ctx context.Context, arg ListRolesParams) ([]TRole, error) {
	rows, err := q.db.QueryContext(ctx, listRoles,
		arg.Ids,
		arg.Ids,
		arg.Name,
		arg.Name,
		arg.Code,
		arg.Code,
		arg.UserID,
		arg.UserID,
		arg.QueryValue,
		arg.QueryValue,
		arg.QueryValue,
		arg.Status,
		arg.Status,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TRole{}
	for rows.Next() {
		var i TRole
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Code,
			&i.Sort,
			&i.Status,
			&i.DataScope,
			&i.CreateBy,
			&i.CreateTime,
			&i.UpdateBy,
			&i.UpdateTime,
			&i.IsDeleted,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteRole = `-- name: SoftDeleteRole :exec
UPDATE t_role SET is_deleted = 1, update_time = ? WHERE id = ?
`

type SoftDeleteRoleParams struct {
	Now time.Time
	ID  string
}

func (q *Queries) SoftDeleteRole(ctx context.Context, arg SoftDeleteRoleParams) error {
	_, err := q.db.ExecContext(ctx, softDeleteRole, arg.Now, arg.ID)
	return err
}

const updateRole = `-- name: UpdateRole :exec
UPDATE t_role SET
    name        = ?,
    code        = ?,
    sort        = ?,
    status      = ?,
    data_scope  = ?,
    update_by   = ?,
    update_time = ?
WHERE id = ?
`

type UpdateRoleParams struct {
	Name      string
	Code      string
	Sort      int32
	Status    int32
	DataScope int32
	UpdateBy  string
	Now       time.Time
	ID        string
}

// Mirrors the previous Select-scoped GORM update
// (name, code, sort, status, data_scope, update_by).
func (q *Queries) UpdateRole(ctx context.Context, arg UpdateRoleParams) error {
	_, err := q.db.ExecContext(ctx, updateRole,
		arg.Name,
		arg.Code,
		arg.Sort,
		arg.Status,
		arg.DataScope,
		arg.UpdateBy,
		arg.Now,
		arg.ID,
	)
	return err
}

const updateRoleStatus = `-- name: UpdateRoleStatus :exec
UPDATE t_role SET status = ?, update_time = ? WHERE id = ?
`

type UpdateRoleStatusParams struct {
	Status int32
	Now    time.Time
	ID     string
}

func (q *Queries) UpdateRoleStatus(ctx context.Context, arg UpdateRoleStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateRoleStatus, arg.Status, arg.Now, arg.ID)
	return err
}
