// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: task.sql

package mysqlgen

import (
	"context"
	"strings"
	"time"
)

const batchDeleteTasks = `-- name: BatchDeleteTasks :exec
DELETE FROM sys_tasks WHERE id IN (/*SLICE:ids*/?)
`

func (q *Queries) BatchDeleteTasks(ctx context.Context, ids []int64) error {
	query := batchDeleteTasks
	var queryParams []interface{}
	if len(ids) > 0 {
		for _, v := range ids {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:ids*/?", strings.Repeat(",?", len(ids))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:ids*/?", "NULL", 1)
	}
	_, err := q.db.ExecContext(ctx, query, queryParams...)
	return err
}

const countTasks = `-- name: CountTasks :one
SELECT COUNT(*) FROM sys_tasks
WHERE (?           IS NULL OR type = ?)
  AND (?         IS NULL OR status = ?)
  AND (? IS NULL OR correlation_id = ?)
  AND (?       IS NULL OR (
        type LIKE ? OR correlation_id LIKE ? OR public_error LIKE ?))
  AND (? IS NULL OR created_at >= ?)
  AND (?   IS NULL OR created_at <= ?)
`

type CountTasksParams struct {
	Type          *string
	Status        *string
	CorrelationID *string
	Keywords      *string
	CreateFrom    *time.Time
	CreateTo      *time.Time
}

func (q *Queries) CountTasks(ctx context.Context, arg CountTasksParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countTasks,
		arg.Type,
		arg.Type,
		arg.Status,
		arg.Status,
		arg.CorrelationID,
		arg.CorrelationID,
		arg.Keywords,
		arg.Keywords,
		arg.Keywords,
		arg.Keywords,
		arg.CreateFrom,
		arg.CreateFrom,
		arg.CreateTo,
		arg.CreateTo,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteTask = `-- name: DeleteTask :exec
DELETE FROM sys_tasks WHERE id = ?
`

func (q *Queries) DeleteTask(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteTask, id)
	return err
}

const getTask = `-- name: GetTask :one

SELECT id, type, status, correlation_id, owner_id, private_state, public_retry_count, public_executed_duration, public_error, public_error_history, public_resume_time, created_at, updated_at, deleted_at FROM sys_tasks WHERE id = ?
`

// task.sql (MySQL dialect)
// Derived from queries/postgres/task.sql. Every parameter is a named
// sqlc.arg/narg (see config.sql header). These queries intentionally do NOT
// filter deleted_at, and Delete is a hard DELETE (see the postgres header).
func (q *Queries) GetTask(ctx context.Context, id int64) (SysTask, error) {
	row := q.db.QueryRowContext(ctx, getTask, id)
	var i SysTask
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.Status,
		&i.CorrelationID,
		&i.OwnerID,
		&i.PrivateState,
		&i.PublicRetryCount,
		&i.PublicExecutedDuration,
		&i.PublicError,
		&i.PublicErrorHistory,
		&i.PublicResumeTime,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listTaskStatusCounts = `-- name: ListTaskStatusCounts :many
SELECT status, COUNT(*) AS count FROM sys_tasks GROUP BY status
`

type ListTaskStatusCountsRow struct {
	Status string
	Count  int64
}

func (q *Queries) ListTaskStatusCounts(ctx context.Context) ([]ListTaskStatusCountsRow, error) {
	rows, err := q.db.QueryContext(ctx, listTaskStatusCounts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTaskStatusCountsRow{}
	for rows.Next() {
		var i ListTaskStatusCountsRow
		if err := rows.Scan(&i.Status, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTaskTypes = `-- name: ListTaskTypes :many
SELECT DISTINCT type FROM sys_tasks
`

func (q *Queries) ListTaskTypes(ctx context.Context) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listTaskTypes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var type_ string
		if err := rows.Scan(&type_); err != nil {
			return nil, err
		}
		items = append(items, type_)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTasks = `-- name: ListTasks :many
SELECT id, type, status, correlation_id, owner_id, private_state, public_retry_count, public_executed_duration, public_error, public_error_history, public_resume_time, created_at, updated_at, deleted_at FROM sys_tasks
WHERE (?           IS NULL OR type = ?)
  AND (?         IS NULL OR status = ?)
  AND (? IS NULL OR correlation_id = ?)
  AND (?       IS NULL OR (
        type LIKE ? OR correlation_id LIKE ? OR public_error LIKE ?))
  AND (? IS NULL OR created_at >= ?)
  AND (?   IS NULL OR created_at <= ?)
ORDER BY created_at DESC
LIMIT  ?
OFFSET ?
`

type ListTasksParams struct {
	Type          *string
	Status        *string
	CorrelationID *string
	Keywords      *string
	CreateFrom    *time.Time
	CreateTo      *time.Time
	Limit         int32
	Offset        int32
}

func (q *Queries) ListTasks(ctx context.Context, arg ListTasksParams) ([]SysTask, error) {
	rows, err := q.db.QueryContext(ctx, listTasks,
		arg.Type,
		arg.Type,
		arg.Status,
		arg.Status,
		arg.CorrelationID,
		arg.CorrelationID,
		arg.Keywords,
		arg.Keywords,
		arg.Keywords,
		arg.Keywords,
		arg.CreateFrom,
		arg.CreateFrom,
		arg.CreateTo,
		arg.CreateTo,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SysTask{}
	for rows.Next() {
		var i SysTask
		if err := rows.Scan(
			&i.ID,
			&i.Type,
			&i.Status,
			&i.CorrelationID,
			&i.OwnerID,
			&i.PrivateState,
			&i.PublicRetryCount,
			&i.PublicExecutedDuration,
			&i.PublicError,
			&i.PublicErrorHistory,
			&i.PublicResumeTime,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
