// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: user.sql

package mysqlgen

import (
	"context"
	"time"
)

const countUsers = `-- name: CountUsers :one
SELECT COUNT(*) FROM t_user
WHERE is_deleted = 0
  AND (? IS NULL OR username = ?)
  AND (? IS NULL OR nickname = ?)
  AND (?   IS NULL OR status   = ?)
  AND (?  IS NULL OR dept_id  = ?)
  AND (? IS NULL OR (
        username LIKE ? OR
        nickname LIKE ? OR
        mobile   LIKE ? OR
        email    LIKE ?))
  AND (? IS NULL OR create_time >= ?)
  AND (?   IS NULL OR create_time <= ?)
  AND (? IS NULL OR id IN (
        SELECT user_id FROM t_user_role WHERE FIND_IN_SET(role_id, ?)))
`

type CountUsersParams struct {
	Username   *string
	Nickname   *string
	Status     *int32
	DeptID     *string
	Keywords   *string
	CreateFrom *time.Time
	CreateTo   *time.Time
	RoleIds    *string
}

func (q *Queries) CountUsers(ctx context.Context, arg CountUsersParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countUsers,
		arg.Username,
		arg.Username,
		arg.Nickname,
		arg.Nickname,
		arg.Status,
		arg.Status,
		arg.DeptID,
		arg.DeptID,
		arg.Keywords,
		arg.Keywords,
		arg.Keywords,
		arg.Keywords,
		arg.Keywords,
		arg.CreateFrom,
		arg.CreateFrom,
		arg.CreateTo,
		arg.CreateTo,
		arg.RoleIds,
		arg.RoleIds,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createUser = `-- name: CreateUser :exec
INSERT INTO t_user (
    id, username, nickname, gender, password, dept_id, avatar,
    mobile, status, email, create_by, update_by, is_deleted, openid,
    create_time, update_time
) VALUES (
    ?, ?, ?, ?,
    ?, ?, ?,
    ?, ?, ?, ?,
    ?, ?, ?,
    ?, ?
)
`

type CreateUserParams struct {
	ID        string
	Username  string
	Nickname  string
	Gender    int32
	Password  string
	DeptID    string
	Avatar    string
	Mobile    string
	Status    int32
	Email     string
	CreateBy  string
	UpdateBy  string
	IsDeleted int32
	Openid    string
	Now       time.Time
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) error {
	_, err := q.db.ExecContext(ctx, createUser,
		arg.ID,
		arg.Username,
		arg.Nickname,
		arg.Gender,
		arg.Password,
		arg.DeptID,
		arg.Avatar,
		arg.Mobile,
		arg.Status,
		arg.Email,
		arg.CreateBy,
		arg.UpdateBy,
		arg.IsDeleted,
		arg.Openid,
		arg.Now,
		arg.Now,
	)
	return err
}

const getUser = `-- name: GetUser :one

SELECT id, username, nickname, gender, password, dept_id, avatar, mobile, status, email, create_time, create_by, update_time, update_by, is_deleted, openid FROM t_user
WHERE id = ? AND is_deleted = 0
`

// user.sql (MySQL dialect)
// Derived from queries/postgres/user.sql. Every parameter is a named
// sqlc.arg/narg (see config.sql header). ILIKE becomes LIKE (the
// utf8mb4_0900_ai_ci collation is case-insensitive). The nullable role-id list uses the
// FIND_IN_SET membership test (see menu.sql header).
func (q *Queries) GetUser(ctx context.Context, id string) (TUser, error) {
	row := q.db.QueryRowContext(ctx, getUser, id)
	var i TUser
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Nickname,
		&i.Gender,
		&i.Password,
		&i.DeptID,
		&i.Avatar,
		&i.Mobile,
		&i.Status,
		&i.Email,
		&i.CreateTime,
		&i.CreateBy,
		&i.UpdateTime,
		&i.UpdateBy,
		&i.IsDeleted,
		&i.Openid,
	)
	return i, err
}

const getUserByUsername = `-- name: GetUserByUsername :one
SELECT id, username, nickname, gender, password, dept_id, avatar, mobile, status, email, create_time, create_by, update_time, update_by, is_deleted, openid FROM t_user
WHERE username = ? AND is_deleted = 0
LIMIT 1
`

func (q *Queries) GetUserByUsername(ctx context.Context, username string) (TUser, error) {
	row := q.db.QueryRowContext(ctx, getUserByUsername, username)
	var i TUser
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Nickname,
		&i.Gender,
		&i.Password,
		&i.DeptID,
		&i.Avatar,
		&i.Mobile,
		&i.Status,
		&i.Email,
		&i.CreateTime,
		&i.CreateBy,
		&i.UpdateTime,
		&i.UpdateBy,
		&i.IsDeleted,
		&i.Openid,
	)
	return i, err
}

const listUsers = `-- name: ListUsers :many
SELECT id, username, nickname, gender, password, dept_id, avatar, mobile, status, email, create_time, create_by, update_time, update_by, is_deleted, openid FROM t_user
WHERE is_deleted = 0
  AND (? IS NULL OR username = ?)
  AND (? IS NULL OR nickname = ?)
  AND (?   IS NULL OR status   = ?)
  AND (?  IS NULL OR dept_id  = ?)
  AND (? IS NULL OR (
        username LIKE ? OR
        nickname LIKE ? OR
        mobile   LIKE ? OR
        email    LIKE ?))
  AND (? IS NULL OR create_time >= ?)
  AND (?   IS NULL OR create_time <= ?)
  AND (? IS NULL OR id IN (
        SELECT user_id FROM t_user_role WHERE FIND_IN_SET(role_id, ?)))
ORDER BY create_time DESC
LIMIT  ?
OFFSET ?
`

type ListUsersParams struct {
	Username   *string
	Nickname   *string
	Status     *int32
	DeptID     *string
	Keywords   *string
	CreateFrom *time.Time
	CreateTo   *time.Time
	RoleIds    *string
	Limit      int32
	Offset     int32
}

func (q *Queries) ListUsers(ctx context.Context, arg ListUsersParams) ([]TUser, error) {
	rows, err := q.db.QueryContext(ctx, listUsers,
		arg.Username,
		arg.Username,
		arg.Nickname,
		arg.Nickname,
		arg.Status,
		arg.Status,
		arg.DeptID,
		arg.DeptID,
		arg.Keywords,
		arg.Keywords,
		arg.Keywords,
		arg.Keywords,
		arg.Keywords,
		arg.CreateFrom,
		arg.CreateFrom,
		arg.CreateTo,
		arg.CreateTo,
		arg.RoleIds,
		arg.RoleIds,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TUser{}
	for rows.Next() {
		var i TUser
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.Nickname,
			&i.Gender,
			&i.Password,
			&i.DeptID,
			&i.Avatar,
			&i.Mobile,
			&i.Status,
			&i.Email,
			&i.CreateTime,
			&i.CreateBy,
			&i.UpdateTime,
			&i.UpdateBy,
			&i.IsDeleted,
			&i.Openid,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteUser = `-- name: SoftDeleteUser :exec
UPDATE t_user SET is_deleted = 1, update_time = ? WHERE id = ?
`

type SoftDeleteUserParams struct {
	Now time.Time
	ID  string
}

func (q *Queries) SoftDeleteUser(ctx context.Context, arg SoftDeleteUserParams) error {
	_, err := q.db.ExecContext(ctx, softDeleteUser, arg.Now, arg.ID)
	return err
}

const updateUser = `-- name: UpdateUser :exec
UPDATE t_user SET
    username    = ?,
    nickname    = ?,
    gender      = ?,
    dept_id     = ?,
    avatar      = ?,
    mobile      = ?,
    status      = ?,
    email       = ?,
    update_by   = ?,
    update_time = ?
WHERE id = ?
`

type UpdateUserParams struct {
	Username string
	Nickname string
	Gender   int32
	DeptID   string
	Avatar   string
	Mobile   string
	Status   int32
	Email    string
	UpdateBy string
	Now      time.Time
	ID       string
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) error {
	_, err := q.db.ExecContext(ctx, updateUser,
		arg.Username,
		arg.Nickname,
		arg.Gender,
		arg.DeptID,
		arg.Avatar,
		arg.Mobile,
		arg.Status,
		arg.Email,
		arg.UpdateBy,
		arg.Now,
		arg.ID,
	)
	return err
}

const updateUserPassword = `-- name: UpdateUserPassword :exec
UPDATE t_user SET password = ?, update_time = ? WHERE id = ?
`

type UpdateUserPasswordParams struct {
	Password string
	Now      time.Time
	ID       string
}

func (q *Queries) UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error {
	_, err := q.db.ExecContext(ctx, updateUserPassword, arg.Password, arg.Now, arg.ID)
	return err
}

const updateUserProfile = `-- name: UpdateUserProfile :exec
UPDATE t_user SET
    nickname    = COALESCE(?, nickname),
    gender      = COALESCE(?,   gender),
    avatar      = COALESCE(?,   avatar),
    mobile      = COALESCE(?,   mobile),
    email       = COALESCE(?,    email),
    update_time = ?
WHERE id = ?
`

type UpdateUserProfileParams struct {
	Nickname *string
	Gender   *int32
	Avatar   *string
	Mobile   *string
	Email    *string
	Now      time.Time
	ID       string
}

func (q *Queries) UpdateUserProfile(ctx context.Context, arg UpdateUserProfileParams) error {
	_, err := q.db.ExecContext(ctx, updateUserProfile,
		arg.Nickname,
		arg.Gender,
		arg.Avatar,
		arg.Mobile,
		arg.Email,
		arg.Now,
		arg.ID,
	)
	return err
}

const updateUserStatus = `-- name: UpdateUserStatus :exec
UPDATE t_user SET status = ?, update_time = ? WHERE id = ?
`

type UpdateUserStatusParams struct {
	Status int32
	Now    time.Time
	ID     string
}

func (q *Queries) UpdateUserStatus(ctx context.Context, arg UpdateUserStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateUserStatus, arg.Status, arg.Now, arg.ID)
	return err
}
