// Command gen-store generates the engine-neutral data-access layer from the
// sqlc-generated PostgreSQL package (db/pg).
//
// It emits three files:
//
//   - db/store/models.go   — neutral copies of every sqlc row/param struct
//   - db/store/store.go     — the Store interface (= sqlc Querier, store.* types)
//   - db/pgstore/store.go   — a thin adapter implementing store.Store over db/pg
//
// The adapter methods are pure delegation: because the neutral structs are
// field-for-field identical to their db/pg counterparts, Go struct conversion
// (store.T(row) / pg.T(arg)) bridges them for free. When a second engine is
// added, its own generated package gets an analogous adapter; the neutral Store
// interface and business code stay untouched.
//
// Run via `make gen-store`. Do not edit the generated files by hand.
package main

import (
	"bytes"
	"fmt"
	"go/ast"
	"go/format"
	"go/parser"
	"go/token"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

const (
	pgDir       = "db/pg"
	storeDir    = "db/store"
	pgstoreDir  = "db/pgstore"
	modulePath  = "github.com/top-system/light-admin"
	pgtypeImp   = "github.com/jackc/pgx/v5/pgtype"
	pgxImport   = "github.com/jackc/pgx/v5"
	genComment  = "// Code generated by tools/gen-store. DO NOT EDIT."
	pgPkgImport = modulePath + "/db/pg"
	stPkgImport = modulePath + "/db/store"
)

// skipTypes are the db/pg declarations that are plumbing, not data — they must
// not be mirrored into the neutral layer.
var skipTypes = map[string]bool{
	"Queries": true,
	"Querier": true,
	"DBTX":    true,
}

type method struct {
	name string
	fn   *ast.FuncType
}

func main() {
	if err := run(); err != nil {
		fmt.Fprintln(os.Stderr, "gen-store:", err)
		os.Exit(1)
	}
}

func run() error {
	fset := token.NewFileSet()
	pkgs, err := parser.ParseDir(fset, pgDir, nil, parser.ParseComments)
	if err != nil {
		return fmt.Errorf("parse %s: %w", pgDir, err)
	}
	pkg, ok := pkgs["pg"]
	if !ok {
		return fmt.Errorf("package pg not found in %s", pgDir)
	}

	// Collect every mirrored type decl and the Querier method set.
	type typeDecl struct {
		name string
		spec *ast.TypeSpec
	}
	var types []typeDecl
	mirrored := map[string]bool{}
	var methods []method

	// Iterate files in a stable order for deterministic output.
	var filenames []string
	for name := range pkg.Files {
		filenames = append(filenames, name)
	}
	sort.Strings(filenames)

	for _, fn := range filenames {
		file := pkg.Files[fn]
		for _, decl := range file.Decls {
			gd, ok := decl.(*ast.GenDecl)
			if !ok || gd.Tok != token.TYPE {
				continue
			}
			for _, spec := range gd.Specs {
				ts := spec.(*ast.TypeSpec)
				name := ts.Name.Name
				if name == "Querier" {
					it := ts.Type.(*ast.InterfaceType)
					for _, m := range it.Methods.List {
						methods = append(methods, method{
							name: m.Names[0].Name,
							fn:   m.Type.(*ast.FuncType),
						})
					}
					continue
				}
				if skipTypes[name] {
					continue
				}
				types = append(types, typeDecl{name: name, spec: ts})
				mirrored[name] = true
			}
		}
	}

	sort.Slice(types, func(i, j int) bool { return types[i].name < types[j].name })
	sort.Slice(methods, func(i, j int) bool { return methods[i].name < methods[j].name })

	// ---- db/store/models.go ----
	var mb bytes.Buffer
	for _, td := range types {
		fmt.Fprintf(&mb, "type %s %s\n\n", td.name, typeString(td.spec.Type, mirrored, ""))
	}
	// Build the import block from the types actually referenced by the mirrored
	// structs. Order matters only for gofmt, which format.Source normalizes.
	var modelImports []string
	if strings.Contains(mb.String(), "time.") {
		modelImports = append(modelImports, `"time"`)
	}
	if strings.Contains(mb.String(), "pgtype.") {
		modelImports = append(modelImports, fmt.Sprintf("%q", pgtypeImp))
	}
	imports := ""
	if len(modelImports) > 0 {
		imports = fmt.Sprintf("import (\n\t%s\n)\n\n", strings.Join(modelImports, "\n\t"))
	}
	models := fmt.Sprintf("%s\n\npackage store\n\n%s%s", genComment, imports, mb.String())
	if err := writeGo(filepath.Join(storeDir, "models.go"), models); err != nil {
		return err
	}

	// ---- db/store/store.go ----
	var sb bytes.Buffer
	sb.WriteString("type Store interface {\n")
	for _, m := range methods {
		fmt.Fprintf(&sb, "\t%s%s\n", m.name, signature(m.fn, mirrored, ""))
	}
	sb.WriteString("}\n")
	storeSrc := fmt.Sprintf("%s\n\npackage store\n\nimport \"context\"\n\n%s", genComment, sb.String())
	if err := writeGo(filepath.Join(storeDir, "store.go"), storeSrc); err != nil {
		return err
	}

	// ---- db/pgstore/store.go ----
	var pb bytes.Buffer
	pb.WriteString(genComment + "\n\npackage pgstore\n\n")
	pb.WriteString("import (\n\t\"context\"\n\t\"errors\"\n\n")
	fmt.Fprintf(&pb, "\t%q\n\n", pgxImport)
	fmt.Fprintf(&pb, "\t%q\n\t%q\n)\n\n", pgPkgImport, stPkgImport)
	pb.WriteString("// Store adapts the sqlc-generated *pg.Queries to the engine-neutral\n")
	pb.WriteString("// store.Store interface.\ntype Store struct {\n\tq *pg.Queries\n}\n\n")
	pb.WriteString("// New builds a Store over any pg.DBTX (a pool or a transaction).\n")
	pb.WriteString("func New(db pg.DBTX) *Store {\n\treturn &Store{q: pg.New(db)}\n}\n\n")
	pb.WriteString("var _ store.Store = (*Store)(nil)\n\n")
	pb.WriteString("// translateErr maps pgx sentinels to the engine-neutral store errors so\n")
	pb.WriteString("// business code never imports pgx. Currently only pgx.ErrNoRows needs mapping.\n")
	pb.WriteString("func translateErr(err error) error {\n")
	pb.WriteString("\tif err != nil && errors.Is(err, pgx.ErrNoRows) {\n\t\treturn store.ErrNoRows\n\t}\n")
	pb.WriteString("\treturn err\n}\n\n")
	for _, m := range methods {
		pb.WriteString(adapterMethod(m, mirrored))
		pb.WriteString("\n")
	}
	if err := writeGo(filepath.Join(pgstoreDir, "store.go"), pb.String()); err != nil {
		return err
	}

	fmt.Printf("gen-store: %d types, %d methods\n", len(types), len(methods))
	return nil
}

// adapterMethod renders one delegating adapter method.
func adapterMethod(m method, mirrored map[string]bool) string {
	var b strings.Builder
	// receiver + signature, qualified with the store.* package
	fmt.Fprintf(&b, "func (s *Store) %s%s {\n", m.name, signature(m.fn, mirrored, "store"))

	callArgs := make([]string, 0, len(m.fn.Params.List))
	for _, p := range m.fn.Params.List {
		name := p.Names[0].Name
		if id, ok := p.Type.(*ast.Ident); ok && mirrored[id.Name] {
			callArgs = append(callArgs, fmt.Sprintf("pg.%s(%s)", id.Name, name))
		} else {
			callArgs = append(callArgs, name)
		}
	}
	call := fmt.Sprintf("s.q.%s(%s)", m.name, strings.Join(callArgs, ", "))

	results := m.fn.Results.List
	switch {
	case len(results) == 1: // error only
		fmt.Fprintf(&b, "\treturn translateErr(%s)\n", call)
	default: // (T, error)
		rt := results[0].Type
		switch t := rt.(type) {
		case *ast.Ident:
			if mirrored[t.Name] {
				fmt.Fprintf(&b, "\trow, err := %s\n\treturn store.%s(row), translateErr(err)\n", call, t.Name)
			} else {
				fmt.Fprintf(&b, "\tv, err := %s\n\treturn v, translateErr(err)\n", call)
			}
		case *ast.ArrayType:
			if id, ok := t.Elt.(*ast.Ident); ok && mirrored[id.Name] {
				fmt.Fprintf(&b, "\trows, err := %s\n", call)
				b.WriteString("\tif err != nil {\n\t\treturn nil, translateErr(err)\n\t}\n")
				fmt.Fprintf(&b, "\tout := make([]store.%s, len(rows))\n", id.Name)
				fmt.Fprintf(&b, "\tfor i := range rows {\n\t\tout[i] = store.%s(rows[i])\n\t}\n", id.Name)
				b.WriteString("\treturn out, nil\n")
			} else {
				fmt.Fprintf(&b, "\tv, err := %s\n\treturn v, translateErr(err)\n", call)
			}
		default:
			fmt.Fprintf(&b, "\tv, err := %s\n\treturn v, translateErr(err)\n", call)
		}
	}
	b.WriteString("}\n")
	return b.String()
}

// signature renders "(params) results" for a method, qualifying mirrored named
// types with pkg (empty pkg = leave unqualified, for the store package itself).
func signature(fn *ast.FuncType, mirrored map[string]bool, pkg string) string {
	var b strings.Builder
	b.WriteByte('(')
	params := make([]string, 0, len(fn.Params.List))
	for _, p := range fn.Params.List {
		name := p.Names[0].Name
		params = append(params, name+" "+typeString(p.Type, mirrored, pkg))
	}
	b.WriteString(strings.Join(params, ", "))
	b.WriteByte(')')

	res := fn.Results.List
	if len(res) == 1 {
		b.WriteByte(' ')
		b.WriteString(typeString(res[0].Type, mirrored, pkg))
	} else {
		b.WriteString(" (")
		rs := make([]string, 0, len(res))
		for _, r := range res {
			rs = append(rs, typeString(r.Type, mirrored, pkg))
		}
		b.WriteString(strings.Join(rs, ", "))
		b.WriteByte(')')
	}
	return b.String()
}

// typeString renders a type expression to source, qualifying any mirrored named
// type with pkg (when non-empty). Struct/field bodies are rendered recursively
// so models.go reproduces the sqlc structs verbatim.
func typeString(e ast.Expr, mirrored map[string]bool, pkg string) string {
	switch t := e.(type) {
	case *ast.Ident:
		if pkg != "" && mirrored[t.Name] {
			return pkg + "." + t.Name
		}
		return t.Name
	case *ast.StarExpr:
		return "*" + typeString(t.X, mirrored, pkg)
	case *ast.ArrayType:
		if t.Len == nil {
			return "[]" + typeString(t.Elt, mirrored, pkg)
		}
		return "[" + typeString(t.Len, mirrored, pkg) + "]" + typeString(t.Elt, mirrored, pkg)
	case *ast.SelectorExpr:
		return typeString(t.X, mirrored, pkg) + "." + t.Sel.Name
	case *ast.MapType:
		return "map[" + typeString(t.Key, mirrored, pkg) + "]" + typeString(t.Value, mirrored, pkg)
	case *ast.Ellipsis:
		return "..." + typeString(t.Elt, mirrored, pkg)
	case *ast.InterfaceType:
		return "interface{}"
	case *ast.StructType:
		var b strings.Builder
		b.WriteString("struct {\n")
		for _, f := range t.Fields.List {
			names := make([]string, len(f.Names))
			for i, n := range f.Names {
				names[i] = n.Name
			}
			b.WriteByte('\t')
			b.WriteString(strings.Join(names, ", "))
			b.WriteByte(' ')
			b.WriteString(typeString(f.Type, mirrored, pkg))
			b.WriteByte('\n')
		}
		b.WriteString("}")
		return b.String()
	case *ast.BasicLit:
		return t.Value
	default:
		return fmt.Sprintf("/* unhandled %T */", e)
	}
}

func writeGo(path, src string) error {
	formatted, err := format.Source([]byte(src))
	if err != nil {
		// Write the unformatted source to aid debugging on failure.
		_ = os.WriteFile(path+".raw", []byte(src), 0o644)
		return fmt.Errorf("format %s: %w", path, err)
	}
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return err
	}
	return os.WriteFile(path, formatted, 0o644)
}
