// Command gen-store generates the engine-neutral data-access layer from the
// sqlc-generated packages.
//
// From db/pg (the reference engine) it emits:
//
//   - db/store/models.go  — neutral copies of every sqlc row/param struct
//   - db/store/store.go   — the Store interface (= sqlc Querier, store.* types)
//
// For every engine package (db/pg, db/sqlitegen, db/mysqlgen — the latter two
// only when present) it emits a thin adapter implementing store.Store:
//
//   - db/pgstore/store.go
//   - db/sqlitestore/store.go
//   - db/mysqlstore/store.go
//
// Adapter methods delegate to the engine's generated Queries. Where the
// engine's generated types differ from the neutral store types (sqlc's
// sqlite/mysql engines infer interface{} for nullable named args, int64 for
// LIMIT/OFFSET, pointers for values assigned to nullable columns), the
// generator maps struct fields by name and applies a small set of conversion
// rules; helpers such as csvWrapped/limitOrAll live in each adapter package's
// hand-written helpers.go.
//
// Store methods that an engine's Querier does not provide (e.g. the postgres
// unnest() batch inserts, or ListMenus whose ORDER BY selector must be split
// on sqlite/mysql) are skipped and must be implemented in the adapter
// package's hand-written manual.go; `var _ store.Store = (*Store)(nil)` in the
// generated file turns a forgotten method into a compile error.
//
// Run via `make gen-store`. Do not edit the generated files by hand.
package main

import (
	"bytes"
	"fmt"
	"go/ast"
	"go/format"
	"go/parser"
	"go/token"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

const (
	pgDir      = "db/pg"
	storeDir   = "db/store"
	modulePath = "github.com/top-system/light-admin"
	pgtypeImp  = "github.com/jackc/pgx/v5/pgtype"
	pgxImport  = "github.com/jackc/pgx/v5"
	genComment = "// Code generated by tools/gen-store. DO NOT EDIT."
	stPkgImp   = modulePath + "/db/store"
)

// engineSpec describes one sqlc-generated package and its adapter output.
type engineSpec struct {
	genDir   string // sqlc output package directory
	genPkg   string // sqlc output package name
	outDir   string // adapter package directory
	outPkg   string // adapter package name
	optional bool   // skip silently when genDir does not exist
	// error translation
	errImports []string // imports needed by translateErr
	errCond    string   // condition mapping the driver's not-found sentinel
}

var engines = []engineSpec{
	{
		genDir: "db/pg", genPkg: "pg", outDir: "db/pgstore", outPkg: "pgstore",
		errImports: []string{pgxImport},
		errCond:    "errors.Is(err, pgx.ErrNoRows)",
	},
	{
		genDir: "db/sqlitegen", genPkg: "sqlitegen", outDir: "db/sqlitestore", outPkg: "sqlitestore",
		optional:   true,
		errImports: []string{"database/sql"},
		errCond:    "errors.Is(err, sql.ErrNoRows)",
	},
	{
		genDir: "db/mysqlgen", genPkg: "mysqlgen", outDir: "db/mysqlstore", outPkg: "mysqlstore",
		optional:   true,
		errImports: []string{"database/sql"},
		errCond:    "errors.Is(err, sql.ErrNoRows)",
	},
}

// skipTypes are generated declarations that are plumbing, not data.
var skipTypes = map[string]bool{
	"Queries": true,
	"Querier": true,
	"DBTX":    true,
}

type method struct {
	name string
	fn   *ast.FuncType
}

// enginePkg is the parsed view of one sqlc-generated package.
type enginePkg struct {
	types   map[string]*ast.TypeSpec // struct/type decls by name
	methods map[string]*ast.FuncType // Querier methods by name
}

func main() {
	if err := run(); err != nil {
		fmt.Fprintln(os.Stderr, "gen-store:", err)
		os.Exit(1)
	}
}

func run() error {
	ref, err := parseEngine(pgDir, "pg")
	if err != nil {
		return err
	}

	// mirrored = every reference type name copied into db/store.
	mirrored := map[string]bool{}
	var typeNames []string
	for name := range ref.types {
		mirrored[name] = true
		typeNames = append(typeNames, name)
	}
	sort.Strings(typeNames)

	var methods []method
	for name, fn := range ref.methods {
		methods = append(methods, method{name: name, fn: fn})
	}
	sort.Slice(methods, func(i, j int) bool { return methods[i].name < methods[j].name })

	// ---- db/store/models.go ----
	var mb bytes.Buffer
	for _, name := range typeNames {
		fmt.Fprintf(&mb, "type %s %s\n\n", name, typeString(ref.types[name].Type, mirrored, ""))
	}
	var modelImports []string
	if strings.Contains(mb.String(), "time.") {
		modelImports = append(modelImports, `"time"`)
	}
	if strings.Contains(mb.String(), "pgtype.") {
		modelImports = append(modelImports, fmt.Sprintf("%q", pgtypeImp))
	}
	imports := ""
	if len(modelImports) > 0 {
		imports = fmt.Sprintf("import (\n\t%s\n)\n\n", strings.Join(modelImports, "\n\t"))
	}
	models := fmt.Sprintf("%s\n\npackage store\n\n%s%s", genComment, imports, mb.String())
	if err := writeGo(filepath.Join(storeDir, "models.go"), models); err != nil {
		return err
	}

	// ---- db/store/store.go ----
	var sb bytes.Buffer
	sb.WriteString("type Store interface {\n")
	for _, m := range methods {
		fmt.Fprintf(&sb, "\t%s%s\n", m.name, signature(m.fn, mirrored, ""))
	}
	sb.WriteString("}\n")
	storeSrc := fmt.Sprintf("%s\n\npackage store\n\nimport \"context\"\n\n%s", genComment, sb.String())
	if err := writeGo(filepath.Join(storeDir, "store.go"), storeSrc); err != nil {
		return err
	}

	// ---- per-engine adapters ----
	for _, spec := range engines {
		if _, statErr := os.Stat(spec.genDir); statErr != nil {
			if spec.optional {
				continue
			}
			return fmt.Errorf("engine dir %s: %w", spec.genDir, statErr)
		}
		eng, err := parseEngine(spec.genDir, spec.genPkg)
		if err != nil {
			return err
		}
		if err := emitAdapter(spec, ref, eng, methods, mirrored); err != nil {
			return err
		}
	}

	fmt.Printf("gen-store: %d types, %d methods\n", len(typeNames), len(methods))
	return nil
}

func parseEngine(dir, pkgName string) (*enginePkg, error) {
	fset := token.NewFileSet()
	pkgs, err := parser.ParseDir(fset, dir, nil, parser.ParseComments)
	if err != nil {
		return nil, fmt.Errorf("parse %s: %w", dir, err)
	}
	pkg, ok := pkgs[pkgName]
	if !ok {
		return nil, fmt.Errorf("package %s not found in %s", pkgName, dir)
	}

	out := &enginePkg{types: map[string]*ast.TypeSpec{}, methods: map[string]*ast.FuncType{}}

	var filenames []string
	for name := range pkg.Files {
		filenames = append(filenames, name)
	}
	sort.Strings(filenames)

	for _, fn := range filenames {
		file := pkg.Files[fn]
		for _, decl := range file.Decls {
			gd, ok := decl.(*ast.GenDecl)
			if !ok || gd.Tok != token.TYPE {
				continue
			}
			for _, spec := range gd.Specs {
				ts := spec.(*ast.TypeSpec)
				name := ts.Name.Name
				if name == "Querier" {
					it := ts.Type.(*ast.InterfaceType)
					for _, m := range it.Methods.List {
						out.methods[m.Names[0].Name] = m.Type.(*ast.FuncType)
					}
					continue
				}
				if skipTypes[name] {
					continue
				}
				out.types[name] = ts
			}
		}
	}
	return out, nil
}

// emitAdapter writes <outDir>/store.go implementing store.Store over the
// engine's generated Queries. Methods the engine lacks, or whose parameters
// cannot be bridged by the conversion rules, are listed in the file header and
// must be provided by a hand-written manual.go in the same package.
func emitAdapter(spec engineSpec, ref, eng *enginePkg, methods []method, mirrored map[string]bool) error {
	var manual []string
	var bodies bytes.Buffer
	usedHelpers := map[string]bool{}

	for _, m := range methods {
		engFn, ok := eng.methods[m.name]
		if !ok {
			manual = append(manual, m.name)
			continue
		}
		body, helpers, err := adapterMethod(spec, ref, eng, m, engFn, mirrored)
		if err != nil {
			manual = append(manual, fmt.Sprintf("%s (%v)", m.name, err))
			continue
		}
		for h := range helpers {
			usedHelpers[h] = true
		}
		bodies.WriteString(body)
		bodies.WriteString("\n")
	}

	genPkgImp := modulePath + "/" + spec.genDir

	var b bytes.Buffer
	b.WriteString(genComment + "\n")
	if len(manual) > 0 {
		b.WriteString("//\n// Methods implemented by hand in manual.go (not generatable for this engine):\n")
		for _, name := range manual {
			fmt.Fprintf(&b, "//   - %s\n", name)
		}
	}
	fmt.Fprintf(&b, "\npackage %s\n\n", spec.outPkg)
	b.WriteString("import (\n\t\"context\"\n\t\"errors\"\n\n")
	for _, imp := range spec.errImports {
		fmt.Fprintf(&b, "\t%q\n", imp)
	}
	fmt.Fprintf(&b, "\n\t%q\n\t%q\n)\n\n", genPkgImp, stPkgImp)
	fmt.Fprintf(&b, "// Store adapts the sqlc-generated *%s.Queries to the engine-neutral\n", spec.genPkg)
	fmt.Fprintf(&b, "// store.Store interface.\ntype Store struct {\n\tq *%s.Queries\n}\n\n", spec.genPkg)
	fmt.Fprintf(&b, "// New builds a Store over any %s.DBTX (a pool/handle or a transaction).\n", spec.genPkg)
	fmt.Fprintf(&b, "func New(db %s.DBTX) *Store {\n\treturn &Store{q: %s.New(db)}\n}\n\n", spec.genPkg, spec.genPkg)
	b.WriteString("var _ store.Store = (*Store)(nil)\n\n")
	b.WriteString("// translateErr maps the driver's sentinels to the engine-neutral store\n")
	b.WriteString("// errors so business code never imports a database driver.\n")
	b.WriteString("func translateErr(err error) error {\n")
	fmt.Fprintf(&b, "\tif err != nil && %s {\n\t\treturn store.ErrNoRows\n\t}\n", spec.errCond)
	b.WriteString("\treturn err\n}\n\n")
	b.Write(bodies.Bytes())

	if err := writeGo(filepath.Join(spec.outDir, "store.go"), b.String()); err != nil {
		return err
	}
	if len(manual) > 0 {
		fmt.Printf("gen-store: %s needs manual.go for: %s\n", spec.outPkg, strings.Join(manual, ", "))
	}
	_ = usedHelpers // helpers are hand-written per adapter package; nothing to emit
	return nil
}

// adapterMethod renders one delegating adapter method for an engine. The
// signature always comes from the store interface (the reference engine); the
// call arguments are converted to the engine's generated types.
func adapterMethod(spec engineSpec, ref, eng *enginePkg, m method, engFn *ast.FuncType, mirrored map[string]bool) (string, map[string]bool, error) {
	helpers := map[string]bool{}
	var b strings.Builder
	fmt.Fprintf(&b, "func (s *Store) %s%s {\n", m.name, signature(m.fn, mirrored, "store"))

	refParams := m.fn.Params.List
	engParams := engFn.Params.List
	if len(refParams) != len(engParams) {
		return "", nil, fmt.Errorf("param count differs")
	}

	callArgs := make([]string, 0, len(refParams))
	for i, p := range refParams {
		name := p.Names[0].Name
		refType := typeString(p.Type, mirrored, "")
		engType := typeString(engParams[i].Type, mirrored, "")

		if refType == engType {
			// Same shape. Mirrored named structs still need the package cast.
			if id, ok := p.Type.(*ast.Ident); ok && mirrored[id.Name] {
				// Identical struct decls on both sides convert directly.
				if !sameStruct(ref.types[id.Name], eng.types[id.Name], mirrored) {
					conv, err := structConversion(spec, ref, eng, id.Name, name, mirrored, helpers)
					if err != nil {
						return "", nil, err
					}
					callArgs = append(callArgs, conv)
					continue
				}
				callArgs = append(callArgs, fmt.Sprintf("%s.%s(%s)", spec.genPkg, id.Name, name))
			} else {
				callArgs = append(callArgs, name)
			}
			continue
		}

		// Named struct on both sides with the same name but different fields.
		refID, refIsIdent := p.Type.(*ast.Ident)
		engID, engIsIdent := engParams[i].Type.(*ast.Ident)
		if refIsIdent && engIsIdent && refID.Name == engID.Name && mirrored[refID.Name] {
			conv, err := structConversion(spec, ref, eng, refID.Name, name, mirrored, helpers)
			if err != nil {
				return "", nil, err
			}
			callArgs = append(callArgs, conv)
			continue
		}

		// Scalar conversion.
		expr, err := fieldConversion(name, name, refType, engType, helpers)
		if err != nil {
			return "", nil, err
		}
		callArgs = append(callArgs, expr)
	}

	call := fmt.Sprintf("s.q.%s(%s)", m.name, strings.Join(callArgs, ", "))

	results := m.fn.Results.List
	engResults := engFn.Results.List
	if len(results) != len(engResults) {
		return "", nil, fmt.Errorf("result count differs")
	}
	switch {
	case len(results) == 1: // error only
		fmt.Fprintf(&b, "\treturn translateErr(%s)\n", call)
	default: // (T, error)
		refRT := typeString(results[0].Type, mirrored, "")
		engRT := typeString(engResults[0].Type, mirrored, "")
		if refRT != engRT {
			return "", nil, fmt.Errorf("result type differs: %s vs %s", refRT, engRT)
		}
		switch t := results[0].Type.(type) {
		case *ast.Ident:
			if mirrored[t.Name] {
				if !sameStruct(ref.types[t.Name], eng.types[t.Name], mirrored) {
					return "", nil, fmt.Errorf("row struct %s differs", t.Name)
				}
				fmt.Fprintf(&b, "\trow, err := %s\n\treturn store.%s(row), translateErr(err)\n", call, t.Name)
			} else {
				fmt.Fprintf(&b, "\tv, err := %s\n\treturn v, translateErr(err)\n", call)
			}
		case *ast.ArrayType:
			if id, ok := t.Elt.(*ast.Ident); ok && mirrored[id.Name] {
				if !sameStruct(ref.types[id.Name], eng.types[id.Name], mirrored) {
					return "", nil, fmt.Errorf("row struct %s differs", id.Name)
				}
				fmt.Fprintf(&b, "\trows, err := %s\n", call)
				b.WriteString("\tif err != nil {\n\t\treturn nil, translateErr(err)\n\t}\n")
				fmt.Fprintf(&b, "\tout := make([]store.%s, len(rows))\n", id.Name)
				fmt.Fprintf(&b, "\tfor i := range rows {\n\t\tout[i] = store.%s(rows[i])\n\t}\n", id.Name)
				b.WriteString("\treturn out, nil\n")
			} else {
				fmt.Fprintf(&b, "\tv, err := %s\n\treturn v, translateErr(err)\n", call)
			}
		default:
			fmt.Fprintf(&b, "\tv, err := %s\n\treturn v, translateErr(err)\n", call)
		}
	}
	b.WriteString("}\n")
	return b.String(), helpers, nil
}

// sameStruct reports whether the reference and engine declarations of a named
// type render to identical source (field names and types).
func sameStruct(refTS, engTS *ast.TypeSpec, mirrored map[string]bool) bool {
	if refTS == nil || engTS == nil {
		return false
	}
	return typeString(refTS.Type, mirrored, "") == typeString(engTS.Type, mirrored, "")
}

// structConversion renders an engine param struct literal populated from the
// store struct `argName`, converting each field by the rules in
// fieldConversion. Every engine field must have a same-named store field.
func structConversion(spec engineSpec, ref, eng *enginePkg, typeName, argName string, mirrored map[string]bool, helpers map[string]bool) (string, error) {
	refST, ok1 := ref.types[typeName].Type.(*ast.StructType)
	engST, ok2 := eng.types[typeName].Type.(*ast.StructType)
	if !ok1 || !ok2 {
		return "", fmt.Errorf("%s is not a struct on both sides", typeName)
	}
	refFields := map[string]string{}
	for _, f := range refST.Fields.List {
		for _, n := range f.Names {
			refFields[n.Name] = typeString(f.Type, mirrored, "")
		}
	}

	var b strings.Builder
	fmt.Fprintf(&b, "%s.%s{\n", spec.genPkg, typeName)
	for _, f := range engST.Fields.List {
		engType := typeString(f.Type, mirrored, "")
		for _, n := range f.Names {
			refType, ok := refFields[n.Name]
			if !ok {
				return "", fmt.Errorf("engine field %s.%s missing in store struct", typeName, n.Name)
			}
			expr, err := fieldConversion(n.Name, argName+"."+n.Name, refType, engType, helpers)
			if err != nil {
				return "", fmt.Errorf("%s.%s: %w", typeName, n.Name, err)
			}
			fmt.Fprintf(&b, "\t\t%s: %s,\n", n.Name, expr)
		}
	}
	b.WriteString("\t}")
	return b.String(), nil
}

// fieldConversion returns the Go expression converting a store-side value
// `src` of type refType to the engine-side type engType.
//
// The rules mirror the dialect rewrites documented in
// docs/multi-database-plan.md: nullable named args become interface{} under
// the sqlite/mysql engines (pointers pass through; []string list filters are
// serialized by the adapter's csv helper), LIMIT/OFFSET become non-null int64
// (nil means "no limit"/"start at 0"), and values written to nullable columns
// become pointers.
func fieldConversion(fieldName, src, refType, engType string, helpers map[string]bool) (string, error) {
	if refType == engType {
		return src, nil
	}
	switch {
	case engType == "interface{}" && refType == "[]string":
		// Nullable list filter: the engine query tests membership against a
		// csv-serialized form (see the adapter's helpers.go).
		helpers["csvList"] = true
		return "csvList(" + src + ")", nil
	case engType == "interface{}" && !strings.HasPrefix(refType, "[]"):
		return src, nil
	case engType == "int64" && refType == "*int32" && fieldName == "Limit":
		helpers["limitOrAll"] = true
		return "limitOrAll(" + src + ")", nil
	case engType == "int64" && refType == "*int32" && fieldName == "Offset":
		helpers["offsetOrZero"] = true
		return "offsetOrZero(" + src + ")", nil
	case engType == "*time.Time" && refType == "time.Time":
		return "&" + src, nil
	case engType == "int64" && refType == "int32":
		return "int64(" + src + ")", nil
	case engType == "int32" && refType == "int64":
		return "int32(" + src + ")", nil
	case engType == "*int64" && refType == "*int32":
		helpers["i64Ptr"] = true
		return "i64Ptr(" + src + ")", nil
	}
	return "", fmt.Errorf("no conversion %s -> %s", refType, engType)
}

// signature renders "(params) results" for a method, qualifying mirrored named
// types with pkg (empty pkg = leave unqualified, for the store package itself).
func signature(fn *ast.FuncType, mirrored map[string]bool, pkg string) string {
	var b strings.Builder
	b.WriteByte('(')
	params := make([]string, 0, len(fn.Params.List))
	for _, p := range fn.Params.List {
		name := p.Names[0].Name
		params = append(params, name+" "+typeString(p.Type, mirrored, pkg))
	}
	b.WriteString(strings.Join(params, ", "))
	b.WriteByte(')')

	res := fn.Results.List
	if len(res) == 1 {
		b.WriteByte(' ')
		b.WriteString(typeString(res[0].Type, mirrored, pkg))
	} else {
		b.WriteString(" (")
		rs := make([]string, 0, len(res))
		for _, r := range res {
			rs = append(rs, typeString(r.Type, mirrored, pkg))
		}
		b.WriteString(strings.Join(rs, ", "))
		b.WriteByte(')')
	}
	return b.String()
}

// typeString renders a type expression to source, qualifying any mirrored named
// type with pkg (when non-empty). Struct/field bodies are rendered recursively
// so models.go reproduces the sqlc structs verbatim.
func typeString(e ast.Expr, mirrored map[string]bool, pkg string) string {
	switch t := e.(type) {
	case *ast.Ident:
		if pkg != "" && mirrored[t.Name] {
			return pkg + "." + t.Name
		}
		return t.Name
	case *ast.StarExpr:
		return "*" + typeString(t.X, mirrored, pkg)
	case *ast.ArrayType:
		if t.Len == nil {
			return "[]" + typeString(t.Elt, mirrored, pkg)
		}
		return "[" + typeString(t.Len, mirrored, pkg) + "]" + typeString(t.Elt, mirrored, pkg)
	case *ast.SelectorExpr:
		return typeString(t.X, mirrored, pkg) + "." + t.Sel.Name
	case *ast.MapType:
		return "map[" + typeString(t.Key, mirrored, pkg) + "]" + typeString(t.Value, mirrored, pkg)
	case *ast.Ellipsis:
		return "..." + typeString(t.Elt, mirrored, pkg)
	case *ast.InterfaceType:
		return "interface{}"
	case *ast.StructType:
		var b strings.Builder
		b.WriteString("struct {\n")
		for _, f := range t.Fields.List {
			names := make([]string, len(f.Names))
			for i, n := range f.Names {
				names[i] = n.Name
			}
			b.WriteByte('\t')
			b.WriteString(strings.Join(names, ", "))
			b.WriteByte(' ')
			b.WriteString(typeString(f.Type, mirrored, pkg))
			b.WriteByte('\n')
		}
		b.WriteString("}")
		return b.String()
	case *ast.BasicLit:
		return t.Value
	default:
		return fmt.Sprintf("/* unhandled %T */", e)
	}
}

func writeGo(path, src string) error {
	formatted, err := format.Source([]byte(src))
	if err != nil {
		// Write the unformatted source to aid debugging on failure.
		_ = os.WriteFile(path+".raw", []byte(src), 0o644)
		return fmt.Errorf("format %s: %w", path, err)
	}
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return err
	}
	return os.WriteFile(path, formatted, 0o644)
}
